lib/nerves_hub/firmwares/firmwares.ex, lib/nerves_hub_web/channels/device_channel.ex, test/nerves_hub/integration/websocket_test.exs
Why:
* That is what @fhunleth and I discussed as being the best option, but I
forgot to edit my last PR to work this way.
=> Lookup firmware by UUID

config/config.exs, config/prod.exs, lib/nerves_hub_web/controllers/account_controller.ex, lib/nerves_hub_web/plugs/allow_uninvited_signups.ex, lib/nerves_hub_web/templates/account/edit.html.eex, lib/nerves_hub_web/templates/session/new.html.eex, lib/nerves_hub_web/views/session_view.ex, test/nerves_hub_web/controllers/account_controller_test.exs, test/nerves_hub_web/plugs/allow_uninvited_signups_test.exs
addresses ticket https://github.com/nerves-hub/nerves_hub/issues/66
=> easily disable signups

.circleci/config.yml, rel/scripts/slack-notification.sh
Posts deployment messages to the slack channel.
=> Send deployment messages

apps/nerves_hub_core/priv/repo/seeds.exs
Once this runs I am going to change the password. We can then use this user to invite others.
=> Seed database with initial user

.circleci/config.yml
=> Build production container on all branches

apps/nerves_hub/lib/nerves_hub_web/templates/account/edit.html.eex, apps/nerves_hub/test/nerves_hub_web/controllers/account_controller_test.exs, apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
Why:
* The password fields were email input fields
* Fixing the template.
* Testing
=> Fix user update form

apps/nerves_hub_www/config/prod.exs, rel/scripts/ecs-cluster.sh, rel/scripts/s3-sync.sh
Update prod config to connect to certificate authority
=> Prod ca configuration

apps/nerves_hub_core/lib/nerves_hub_core/products/product.ex
Why:
* https://github.com/nerves-hub/nerves_hub_web/issues/146
=> Remove devices and deployments from product schema

apps/nerves_hub_www/assets/package-lock.json, apps/nerves_hub_www/rel/Dockerfile.build
Does the thing that the title says
=> Fix dependency paths in prod

apps/nerves_hub_www/assets/css/app.scss, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_footer.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
I lightened up the background a tad and added a footer. Some of the links work.
Looks like this:
=> Add footer and more styles

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
=> cookie confirmation bar from https://cookieconsent.insites.com/download/

apps/nerves_hub_api/.formatter.exs, apps/nerves_hub_api/config/config.exs, apps/nerves_hub_api/lib/nerves_hub_api/application.ex, apps/nerves_hub_api/lib/nerves_hub_api_web.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/user_controller.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/endpoint.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex, apps/nerves_hub_api/mix.exs, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs, apps/nerves_hub_api/test/nerves_hub_api_web/views/error_view_test.exs, apps/nerves_hub_api/test/support/channel_case.ex, apps/nerves_hub_device/.formatter.exs, apps/nerves_hub_device/config/dev.exs, apps/nerves_hub_device/lib/nerves_hub_device/presence.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/router.ex, apps/nerves_hub_device/mix.exs, apps/nerves_hub_device/test/test_helper.exs
Formatting files were missing on `device` and `api` apps.
=> Add missing formatter files and format projects

apps/nerves_hub_core/lib/nerves_hub_core/devices.ex, apps/nerves_hub_core/lib/nerves_hub_core/devices/device.ex, apps/nerves_hub_core/lib/nerves_hub_core/devices/device_certificate.ex, apps/nerves_hub_core/priv/repo/migrations/20180808172729_add_device_certificates_table.exs, apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
I guess in all my rebasing I snuck the migration in to a different PR. Sigh, oh well. Its in there. And here is the rest.
* Add device_certificates table.
* Update Device to has_many DeviceCertificates
=> Add device_certificates

apps/nerves_hub_device/lib/nerves_hub_device_web/channels/user_socket.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/endpoint.ex, mix.lock
This has been updated to include the latest changes that were made in this PR https://github.com/phoenixframework/phoenix/pull/2889
=> Update Phoenix to latest commit

mix.lock
Because if we don't deployments are broken
=> Bump phoenix

apps/nerves_hub_api/rel/Dockerfile.build
fwup needed to be added to the api container for verifying firmware
=> Add fwup to the release container for the API

apps/nerves_hub_core/config/dev.exs, apps/nerves_hub_core/config/prod.exs, apps/nerves_hub_core/config/test.exs, apps/nerves_hub_core/lib/nerves_hub_core/devices.ex, apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex, apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/file.ex, apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/s3.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/endpoint.ex, apps/nerves_hub_www/config/dev.exs, apps/nerves_hub_www/config/prod.exs, apps/nerves_hub_www/config/test.exs, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex
Also, remove the random bytes from the file path to make it easier to organize things
=> Move firmware uploader config to nerves_hub_core

apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
=> Fix version helper argument mis match

apps/nerves_hub_api/rel/Dockerfile.build
Fixes broken deployments on master
=> Update fwup on api release to 1.2.5

apps/nerves_hub_core/.gitignore, apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex, apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/file.ex, apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/s3.ex, apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs, test/support/fixtures.ex
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/195
=> Delete firmware files when deleting firmware records

apps/nerves_hub_www/.gitignore, apps/nerves_hub_www/assets/css/app.scss, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account/new.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/session/new.html.eex
Just neatened up the login and signup pages, make them look like dialogs a bit
=> cleanup login and signup

apps/nerves_hub_www/assets/css/_custom.scss, apps/nerves_hub_www/assets/css/app.scss, apps/nerves_hub_www/assets/package-lock.json, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/index.html.eex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs
@stwf Great start with the product index page. I made couple minor adjustments.
=> Update styles for product page

apps/nerves_hub_core/lib/nerves_hub_core/deployments/deployment.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/new.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/show.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
Why:
* Wasn't showing all the info, and it looked weird
* https://github.com/nerves-hub/nerves_hub_web/issues/208
* Making it show info and not look weird
=> Fix deployment show page

apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs
Fixes the tests that are breaking in master
=> Update API tests to handle running async

rel/config.exs
It helps when you start things.
=> Start apps permanent in release

apps/nerves_hub_www/lib/nerves_hub_www_web/views/email_view.ex
=> Fix emails not having a valid link

Makefile
I don't know if anyone else even uses the Makefile here, but i always forget to format files so i added a helper.
=> Add format helpers to Makefile

apps/nerves_hub_www/test/nerves_hub_www/accounts/email_test.exs
Why:
* We had none.
* https://github.com/nerves-hub/nerves_hub_web/issues/333
=> Basic email rendering tests

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
=> Fix device list table formatting

apps/nerves_hub_api/lib/nerves_hub_api_web/views/device_view.ex
Updated the device view to the additional helpful information to the cli
=> API: Add last_communication and version to device view

apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
fixes https://github.com/nerves-hub/nerves_hub_web/issues/344
=> Add route to delete deployments through the api

apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
Devices can potentially connect and provide firmware metadata for products that do not exist yet in the database.
=> Check if product exists when looking for deployments

apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware.ex, apps/nerves_hub_web_core/priv/repo/migrations/20190221141905_add_size_to_firmware.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
It wasn't being stored before. This will persist it to the db.
=> Store size on firmware record

apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_controller_test.exs, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs, apps/nerves_hub_api/test/support/conn_case.ex, apps/nerves_hub_device/test/nerves_hub_device/ssl_test.exs, apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs, apps/nerves_hub_device/test/support/conn_case.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/user.ex, apps/nerves_hub_web_core/priv/repo/seeds.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/products/products_test.exs, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/session_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex, apps/nerves_hub_www/test/nerves_hub_www_web/channels/devices_channel_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/password_reset_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs, test/support/fixtures.ex
I've finished migrating the data to the new table. This PR implements phase two, which switches the logic over to using the org_users table.
=> Switch to using OrgUser roles

apps/nerves_hub_web_core/priv/repo/migrations/20190321200632_remove_users_orgs.exs
Last PR to implementing https://github.com/nerves-hub/nerves_hub_web/pull/377
Clean up old tables
=> Remove old users_orgs join table

apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product_user.ex, apps/nerves_hub_web_core/priv/repo/migrations/20190308135003_add_product_user_roles.exs
This PR adds the `product_users` table and some helper functions for adding / removing product user roles. 
It it step 1/2 for implementing https://github.com/nerves-hub/nerves_hub_web/pull/382
=> Add ProductUser model and add / remove functions

apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/product_controller.ex, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_controller_test.exs, apps/nerves_hub_api/test/support/conn_case.ex, apps/nerves_hub_device/test/nerves_hub_device/ssl_test.exs, apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs, apps/nerves_hub_device/test/support/conn_case.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex, apps/nerves_hub_web_core/priv/repo/seeds.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/products/products_test.exs, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/product_controller.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/firmware_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_key_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs, test/support/fixtures.ex
Step 2/2 for implementing https://github.com/nerves-hub/nerves_hub_web/pull/382. This PR is to be merged after https://github.com/nerves-hub/nerves_hub_web/pull/387 and once the data has been populated.
=> Switch to using ProductRoles

apps/nerves_hub_web_core/test/nerves_hub_web_core/products/products_test.exs
Why:
* I noticed this wasn't covered when I was investigating: https://github.com/nerves-hub/nerves_hub_web/issues/390
Other Notes:
* This does not actually fix the mentioned issue.
=> Assert when a user creates a product, it shows up in their product list

.circleci/config.yml, Makefile, README.md, dev.env, mix.lock
Copy of #394 & #395 (Third times the charm... 🤞)
Updated the readme with some points I went through while setting this up locally. Also made change to CI config to hopefully allow PRs from forks to run the CI in the future.
=> Update README.md (and allow forks to run CI)

apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/firmware_controller_test.exs
Only being able to delete firmware from the command-line was sort of annoying
=> Add button to delete firmware

apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/audit_log.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
This fixes a few specs that were definitely incorrect. Still not close to Dialyzer Zero, but better.
=> Minor cleanup

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex, apps/nerves_hub_www/test/nerves_hub_www_web/views/layout_view_test.exs
Fixes #415
Show Firmware size in MiB, GiB
Show TTL in days, etc. depending on value.
=> Humanize display of organization info

apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex, apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
This fixes an issue where devices with the same product name across organizations would be checked for eligibility on deployment updates from any org for that firmware. This would cause the devices to be asked to update to a version of the firmware from another org. This would fail because of firmware signing mismatch. This PR also breaks apart the calls for fetching the eligible devices from sending them the message for better testability.
=> Fix deployment update query to add scope for org_id

apps/nerves_hub_device/lib/nerves_hub_device/presence.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
* Fixes devices#index to update firmware and last connection fields when changes detected
* Removes unused variables from DeviceLive.Index
* fix compiler warning in deployment.show.leex
=> Quick fixes for LiveView pages

apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
While trying to track down an obscure bug, I noticed that these queries could be updated. The first is to use `on` as part of the join for `firmware` so we can filter the join. The second one is for `get_device_by_certificate/1`. `device_certificate` belongs to `device` so it makes more sense to access the device record through the certificate.
=> Tighten up device queries

apps/nerves_hub_www/assets/css/_console.scss
Not perfect. Should eventually support resizing the window for people who want bigger console, but this makes things a little easier to manage.
=> Fix the console height and make it scrollable

apps/nerves_hub_web_core/lib/nerves_hub_web_core/audit_logs/audit_log.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex, apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
Fixes #474
Adds `firmware_uuid` to an Audit Log event created when a device is told to update.
Then when we use the AuditLog to check failure rates and thresholds, we check for that UUID
as well to ensure we're correctly matching failures. This allows reusuing deployments with
different firmwares and adds little more accuracy to device failure checking.
=> Scope failure queries to firmware UUID

apps/nerves_hub_api/config/config.exs, apps/nerves_hub_api/mix.exs, apps/nerves_hub_device/config/config.exs, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware_metadata.ex, apps/nerves_hub_www/config/config.exs, apps/nerves_hub_www/mix.exs
After removing poison, phoenix needs to be told what to use for Jason parsing.
=> Configure phoenix to use Jason

apps/nerves_hub_www/assets/js/app.js, apps/nerves_hub_www/assets/package.json, apps/nerves_hub_www/assets/webpack.config.js, apps/nerves_hub_www/assets/yarn.lock, apps/nerves_hub_www/lib/mix/tasks/assets.build.ex
This PR updates web assets to fix vulnerability warnings. It also updates the webpack config.
=> Update web assets

.circleci/config.yml
I deployed this on the side and it fixed production javascript issues. Magic!
=> Fix circle ci caches

crowdin.yml
=> Add Crowdin configuration

crowdin.yml
=> Update Crowdin languages

apps/nerves_hub_device/config/test.exs, apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
Changes the port for testing so that you can run tests while you have a dev server also running
=> Change testing port

apps/nerves_hub_device/lib/nerves_hub_device/presence.ex, apps/nerves_hub_device/lib/nerves_hub_device_web/channels/console_channel.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
With recent change to scope devices to product, some device channel topics were changed and a few were missed, so this just fixes that.
=> Fix device channel topics

apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/firmware_controller_test.exs
Looks like I missed the firmware download links when going through the app.
=> Fix firmware download links

apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/transfer/s3_ingress.ex
If a device requests firmware that no longer exists, a 404 may be thrown and no bytes are transferred. This results in a server access log message where bytes transferred / bytes sent is `-`. This PR updates the server access record parser to allow for these types of records.
=> Allow for S3 Ingress records with no bytes transferred

.circleci/config.yml, apps/nerves_hub_api/config/prod.exs, apps/nerves_hub_api/config/release.exs, apps/nerves_hub_device/config/prod.exs, apps/nerves_hub_device/config/release.exs, apps/nerves_hub_web_core/config/prod.exs, apps/nerves_hub_web_core/lib/nerves_hub_web_core/application.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex, apps/nerves_hub_web_core/priv/repo/seeds.exs, apps/nerves_hub_www/config/prod.exs, apps/nerves_hub_www/config/release.exs, rel/scripts/ecs-cluster.sh, rel/scripts/ecs-deploy.sh, rel/scripts/ecs-migrate.sh, rel/scripts/ecs-network-configuration.sh, rel/scripts/s3-sync.sh
This PR adds the ability to deploy to the staging environment and adds an approval phase to production deployments.
=> Staging environment

apps/nerves_hub_api/config/release.exs, apps/nerves_hub_device/config/release.exs, apps/nerves_hub_www/config/release.exs
This will allow us to alter the log level in the staging environment.
=> Allow the log level to be set at runtime

apps/nerves_hub_api/config/release.exs, apps/nerves_hub_device/config/release.exs, apps/nerves_hub_www/config/release.exs
I promise after fixing this mistake that I am done for the night.
=> Fix calls to System.to_atom/1

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
Solution found
[here](https://github.com/phoenixframework/phoenix_live_view/issues/111#issuecomment-527520195)
Fixes #558
=> Fix Device#delete from the Device index page

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
=> Update Device index to show healthy status

apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
Large firmware files were timing out in this code due to slow upload speeds to S3 after 15 seconds. This PR sets the timeout to 30.
=> Increase DB transaction timeout to accommodate for uploading to S3

apps/nerves_hub_web_core/lib/nerves_hub_web_core/views/email_view.ex
=> fixes a misspelled word

apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/session_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/ensure_logged_in.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs
=> Redirect after login

apps/nerves_hub_api/rel/Dockerfile.build, apps/nerves_hub_device/rel/Dockerfile.build, apps/nerves_hub_www/rel/Dockerfile.build
This fixes the deployment pipeline.
=> elixir: bump to v1.9.2

apps/nerves_hub_web_core/lib/nerves_hub_web_core/application.ex
I thought the wording was confusing, so I am offering a little polish. Let me know what you think!
=> Little doc improvement

apps/nerves_hub_api/rel/Dockerfile.build, apps/nerves_hub_www/rel/Dockerfile.build
This fixes the deployment pipeline.
=> fwup: bump to v1.5.1

apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/fallback_controller.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex, apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/product_controller.ex, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_controller_test.exs, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/fallback_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/product_controller.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/firmware_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs
Rebased https://github.com/nerves-hub/nerves_hub_web/pull/586
=> 345 product delete firmware error

apps/nerves_hub_www/assets/package-lock.json, apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
* fix liveview pagination
* fix device sorting
* update assets
=> Liveview fixes

apps/nerves_hub_device/lib/nerves_hub_device_web/endpoint.ex
This reverts commit 4ae4188cd5ce6df3503c99bc511e68d7441896dc.
=> Revert "Hard set device websocket messages to use V2 serializer"

.circleci/config.yml, .tool-versions, apps/nerves_hub_www/assets/package-lock.json, apps/nerves_hub_www/assets/package.json, apps/nerves_hub_www/lib/mix/tasks/assets.build.ex
I'm dealing with JS and assets right now...hopefully this helps some future pains
* Adds `.tool-version` with node 14.4.0
* Updates some JS dependencies
* fix `mix assets.build` task
* `npm audit fix`
=> Deal with assets

apps/nerves_hub_www/lib/nerves_hub_www_web.ex, test/support/default_mocks.ex, test/support/mocks.ex
This fixes a couple compiler warnings and adds a missing alias for Routes to the live views.
=> Fix compiler warnings

apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs
I found this issue while trying to delete a product from the web interface.
=> Fixes ISE when trying to delete products with devices

apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
=> Fixes deployment redirect when the name changes

apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
This fixes failing tests
cc/ @coryjewell
=> Fix failing audit event when saving a deployment from web

apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
Why:
* The device index screen would glitch when a device status updated
* Sometimes sorting/paginating would fail and display wrong data or empty data
* We were not being consistent in applying changes to displayable devices
* Consolidate sort, paginate, filter functions in one consistent display devices function
* Call consolidated function every time devices need to be displayed
=> Fix bugs with device index screen

apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/ca_certificate.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_certificate_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/edit.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/index.html.eex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_certificate_controller_test.exs
=> Adds ability to update CA descriptions

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/_header.html.leex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/console.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
=> Shows device details while showing console

apps/nerves_hub_api/rel/Dockerfile.build, apps/nerves_hub_device/rel/Dockerfile.build, apps/nerves_hub_www/rel/Dockerfile.build
=> remove fwup patch constraint

apps/nerves_hub_www/assets/css/_typography.scss
Resolves https://github.com/nerves-hub/nerves_hub_web/issues/688
=> Remove uppercasing

apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_certificate_controller.ex, apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_certificate_controller_test.exs, apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex, apps/nerves_hub_device/test/nerves_hub_device/ssl_test.exs, apps/nerves_hub_web_core/lib/nerves_hub_web_core/certificate.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device_certificate.ex, apps/nerves_hub_web_core/priv/repo/migrations/20210122175930_add_der_to_device_certificates.exs, test/support/fixtures.ex
So that exporting and trasferring can be supported
=> Add der field to DeviceCertificate

apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
=> add device identifier to page title

apps/nerves_hub_device/lib/nerves_hub_device/presence.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware_metadata.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/password_reset_controller.ex
While looking around to add a feature, I noticed that
1) dialyzer isn't run in CI
2) the existing specs were mostly wrong
3) there aren't very many existing specs
=> Begin fixing dialyzer

apps/nerves_hub_device/lib/nerves_hub_device/presence.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org_user.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/upload.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex, apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_certificate_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex, mix.exs, test/support/fixtures.ex
This doesn't enable CI, but all type checks passed on my machine. I can add it to CI if desired.
=> Finish fixing Dialyzer

apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs, apps/nerves_hub_www/test/nerves_hub_www/integration/certificate_authority_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_console_test.exs
The warnings when running tests was overwhelming. It was time to go through and cleanup..
=> fix the barrage of warnings from various tests

apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
This fixes the breaks with the new UploadPayload.
Unfortunately, it negates even having an UploadPayload structure, but only on initial reply when a device joins the Phoenix channel. This is a fault in `:nerves_hub_link` that considers the existence of `firmware_url` key to mean an update is available. When update is not actually available, that would be nil and cause `:nerves_hub_link` to completely crash.
This is fixed in https://github.com/nerves-hub/nerves_hub_link/pull/63 on the client side.
For now, this cuts up our nice structure to prevent existing devices in the field from breaking. In the future, this can be removed once enough devices have updated.
=> Adjust payload for Device Channel join reply

apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
The condition checking for a valid der stored was in the wrong spot
:facepalm:
=> fix cert download in device#show

apps/nerves_hub_www/assets/css/_typography.scss, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/index.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/_header.html.leex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/show.html.eex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/index.html.eex
For #743
Maybe could be prettier. This is a start
Thanks for reporting @pojiro ❤️ 
/cc @coryjewell @Mrjaco12
=> use monospace for serials and UUIDs

apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
Fixes #744
(Thanks @RobinBeekhof for reporting! ❤️ )
=> Fix crashing when deployment save does not succeed

apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/remove_account_test.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
=> Fix test fixture setup

apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex, apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_index_test.exs
=> Fix issue with filtering by tags

apps/nerves_hub_web_core/priv/repo/migrations/20210505153607_upgrade_oban_jobs_to_v10.exs, apps/nerves_hub_www/config/release.exs
This allows an environment variable to control if signups are allowed. I've already prepared the corresponding terraform files, too :)
=> Introduce release config for allow_signups

apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/workers/delete_firmware.ex, config/config.exs
=> Fix DeleteFirmware worker fails every 15 minutes

.tool-versions, README.md
- Point links to the next branch
- Update Elixir and Erlang version
- Add notice about the next branch
=> Update README with info about next

apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/live/product_live/import.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/import.html.leex
This implements a new uploader to process preprovisioned modules.
See the official docs for more information: https://ww1.microchip.com/downloads/en/DeviceDoc/TrustPlatformManifestFileFormat_2019-09-26_A.pdf
=> New Feature: Import microchip tpm file

apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex, apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
Only count AuditLogs for installs after a device is marked healthy
=> Reset failures after a device is marked healthy

apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org_key.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/repo.ex, apps/nerves_hub_web_core/priv/repo/migrations/20220602235038_change_org_key_index.exs, apps/nerves_hub_www/assets/css/_table.scss, apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
Replacement for #711
Support moving devices between orgs.
/cc @tonnenpinguin
=> Device moving

apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
For some reason LiveView kept sending an empty string instead of the boolean value. Maybe there's another fix for this?
=> Fix deployment toggling

apps/nerves_hub_api/lib/nerves_hub_api_web/views/product_view.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments/deployment.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex, apps/nerves_hub_web_core/priv/repo/migrations/20221014151654_move_delta_updatable_to_deployments.exs, apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs, apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/edit.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/new.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.heex, apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/form.html.heex, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs, apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs, test/support/fixtures.ex
Context: https://elixir-lang.slack.com/archives/CANV3GCAV/p1665674170768029
I haven't yet trial ran it, but it works with the test suite.
=> Move delta_updatable flag from products to deployments

apps/nerves_hub_web_core/lib/nerves_hub_web_core/certificate.ex, apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex
This commit sadly didn't come with a unit test.
=> Import devices with ders rather than pems

README.md
A minor improvement in README
Currently the latest version of asdf is `0.11.0`
=> Update asdf version in README

lib/nerves_hub/accounts.ex, lib/nerves_hub/accounts/org.ex, lib/nerves_hub_web/templates/org/edit.html.heex, lib/nerves_hub_web/templates/org_user/index.html.heex, priv/repo/migrations/20190306221354_add_type_to_org.exs, test/nerves_hub/accounts/accounts_test.exs, test/nerves_hub_web/controllers/org_user_controller_test.exs
The first org made is your username but can be edited and invited to
=> Remove org types

Dockerfile, mix.exs, rel/scripts/ecs-cluster.sh
Update ecs-cluster.sh to match the new release and not use an ENV variable
=> Generate a single release

README.md
Recommend logging in (while in development mode) via the `nerveshub` root user created in the seed script.
=> Add initial login instructions

Dockerfile
Use alpine directly instead of nerveshub/runtime. Consolidate everything into one Dockerfile
=> Migrate nerveshub/runtime into the Dockerfile

lib/nerves_hub/deployments.ex, lib/nerves_hub_web/channels/device_channel.ex
If deployment payload matches the device set the deployment directly and don't query the database.
=> Optimize devices matching against deployment changes

lib/nerves_hub_web/api_router.ex, lib/nerves_hub_web/controllers/api/device_certificate_controller.ex, lib/nerves_hub_web/controllers/api/device_controller.ex, test/nerves_hub_web/controllers/api/device_certificate_controller_test.exs, test/nerves_hub_web/controllers/api/device_controller_test.exs
And clear out controller actions / plugs that aren't used
=> Remove old API routes from the router

lib/nerves_hub_device/presence.ex, lib/nerves_hub_web/api_router.ex, lib/nerves_hub_web/controllers/api/device_controller.ex, lib/nerves_hub_web/views/api/device_view.ex
The UI has this capability and for easier scripting purposes, let's expose something similar via the API.
=> Add an API for forcing reconnect and sending code to a device

lib/nerves_hub/application.ex, lib/nerves_hub/deployments/orchestrator.ex, lib/nerves_hub_device/presence.ex, lib/nerves_hub_web/channels/device_channel.ex, test/nerves_hub_web/channels/websocket_test.exs
Skip any kind of staleness for this lookup in gproc_dist
=> Use a local registry for device updating via the deployment orchestrator

lib/nerves_hub/deployments.ex, lib/nerves_hub/deployments/deployment.ex, lib/nerves_hub/devices.ex, lib/nerves_hub_web/templates/deployment/show.html.heex, lib/nerves_hub_web/views/deployment_view.ex, priv/repo/migrations/20230524154334_add_percentage_counts_to_deployments.exs, test/nerves_hub/devices_test.exs
Progress bar on the deployment page that shows a rough percentage of how far the deployment is.
=> Display the current process of a deployment

lib/nerves_hub/application.ex, lib/nerves_hub/devices/device_link.ex, lib/nerves_hub/devices/supervisor.ex, lib/nerves_hub_web/channels/device_channel.ex
Have an internal process to eventually house most of the connected device logic, for when we have multiple transports.
=> Create a device process to subscribe to internal channels

lib/nerves_hub/tracker.ex
In the off chance that this node doesn't have this server registered, try again in a little bit. This can happen in rolling deploys the first time the application is deployed with the tracker.
=> Catch the name registration error when starting tracker syncs

lib/nerves_hub/tracker.ex, lib/nerves_hub_web/controllers/home_controller.ex, lib/nerves_hub_web/router.ex, lib/nerves_hub_web/templates/home/online_devices.html.eex
See what's in the tracker for that web node
=> Create a debug page to list out all of the devices online

lib/nerves_hub_web/api_router.ex, lib/nerves_hub_web/controllers/api/device_controller.ex, test/nerves_hub_web/controllers/api/device_controller_test.exs
Similar to the UI for a device
=> Add an API endpoint to upgrade a devices firmware manually

lib/nerves_hub_device/ssl.ex
This is mostly preparatory to updating to OTP 26 which will start enforcing the expiration check on the CA during path validation which was previously ignored when validting the device cert
In this situation, we selectively allow or disallow the expiration of the CA based on the database field and as part of the path validation flow
=> Change how we validate signer CA's that might be expired

Dockerfile
Alpine uses musl which can cause an issue to overrun the stack and heap in OTP 26.
=> Switch to debian in the Dockerfile

lib/nerves_hub/ssl.ex, test/nerves_hub/ssl_test.exs
There are some cases where the signer CA is sent on the connection request, but it is an intermediary CA (i.e. a middle cert that was signed by anoter Root CA). In those cases where only the intermediary is sent in the request, the chain is incomplete and the intermediary CA is evaluated before the device certificate.
This fails because our simple check only considers a Root CA coming in (AKI == SKI) and then prevents the device cert from even being considered.
This change fixes this situation by adding the known CA cert lookup. In these situations, you would need to manually register the intermediary so we can look it up as trusted and ignore it in the chain.
=> Allow known intermediary signer CA

assets/css/_console.scss, assets/js/console.js, lib/nerves_hub_web/templates/device/console.html.heex, lib/nerves_hub_web/user_console_channel.ex, lib/nerves_hub_web/user_socket.ex
Everyone will have the same terminal size and not be allowed to adjust it. This will prevent oddities when multiple people are connected.
=> Don't allow adjusting the iex console window

lib/nerves_hub/ssl.ex, lib/nerves_hub_web/channels/device_socket.ex
This module is the one that does most of the heavy lifting for loading a device certificate. Fail the handshake if we're being bombarded by device connects. Remove rate limiting in the socket since it's happening higher.
=> Move rate limiting into NervesHub.SSL

lib/nerves_hub/devices.ex, lib/nerves_hub/metrics.ex, lib/nerves_hub/ssl.ex
More statsd metrics than spans to keep overhead lower for this very critical section.
=> Add metrics around SSL connections

assets/css/_console.scss, assets/js/console.js, assets/package-lock.json, assets/package.json, lib/nerves_hub_web/templates/device/console.html.heex
Create an xterm.js addon that tries to make the font size fit the screen as best it can.
It's not the prettiest, but it works.
=> Console will automatically resize the font to fill the screen

lib/nerves_hub/devices.ex, lib/nerves_hub_web/controllers/api/device_controller.ex, lib/nerves_hub_web/views/api/device_view.ex
=> Include the org and product names for a device API response

assets/js/console.js, lib/nerves_hub_web/channels/console_channel.ex, lib/nerves_hub_web/channels/user_console_channel.ex, lib/nerves_hub_web/templates/device/console.html.heex
Web side of sending files to a device through the NervesHub console. Transfers files similar to how file upload chunking happens from a device.
Related: https://github.com/nerves-hub/nerves_hub_link/pull/131
=> Send files to a device through the web console

lib/nerves_hub_web/live/device_live/show.ex
=> Correct `consume_uploaded_entry/1` return for device cert upload

config/release.exs
=> Move `verify_fun` under correct options in release.exs

config/dev.exs, lib/nerves_hub/deployments/deployment.ex, lib/nerves_hub/devices/device_link.ex, lib/nerves_hub/uploads.ex, lib/nerves_hub_web/controllers/deployment_controller.ex, lib/nerves_hub_web/templates/deployment/edit.html.heex, lib/nerves_hub_web/views/deployment_view.ex, priv/repo/migrations/20231031165843_add_archive_id_to_deployments.exs, test/nerves_hub_web/channels/websocket_test.exs, test/support/socket_client.ex
And send a socket message on device connect to tell about the archive.
Related: https://github.com/nerves-hub/nerves_hub_link/pull/135
=> Assign an archive to a deployment

config/runtime.exs
Check to make sure the files exist before allowing to run.
=> Load the device key/cert via ENV or existing file path

config/runtime.exs
With existing deployments that were using HOST and PORT
=> Load from multiple ENVs to be backwards compatible

lib/nerves_hub/application.ex
Needs to be a list for appending to the list of application children
=> Wrap the SocketDrano child in a list

config/config.exs
=> Prune Oban jobs older than a week 

lib/nerves_hub/devices.ex, lib/nerves_hub/firmwares/delta_updater/default.ex, test/nerves_hub/devices_test.exs
Replicating #886 for v2.0
See also #885
=> Default delta updater can delta non-block resources

lib/nerves_hub/ssl.ex
There's a chance of still performing database lookups for devices coming in if they send the signer cert before sending the device cert.
=> Move rate limiting for devices to both `verify_fun` function heads

config/runtime.exs
=> Fix `cacertfile` in runtime.exs

config/runtime.exs, lib/nerves_hub/archives.ex
Also configure the s3 bucket to be the same bucket as the firmwares upload
=> Sign the archive URL when downloading from S3

lib/nerves_hub/archives.ex, lib/nerves_hub_web/controllers/archive_controller.ex
Also use the product when looking up an archive because uuid is unique per product.
=> Handle upload errors for archives

config/runtime.exs
dns cluster isn't used anymore, we use libcluster with postgres
=> remove the remaining dns cluster config

lib/nerves_hub_web/channels/device_channel.ex, test/nerves_hub_web/channels/device_channel_test.exs
this is related to https://github.com/nerves-hub/nerves_hub_link/pull/187
=> support sending archive public keys on device connection

lib/nerves_hub/metrics.ex, lib/nerves_hub_web/channels/device_channel.ex
To help tie the connect/disconnect together in logs for debugging
=> Log the reference id for connect/disconnect messages

lib/nerves_hub_web/channels/device_channel.ex, test/nerves_hub_web/channels/device_channel_test.exs
`handle_in` handles incoming channel messages, not `handle_info`, my bad
=> correct the unhandled message function

config/runtime.exs, lib/nerves_hub/firmwares/upload/s3.ex
required for https://www.tigrisdata.com/docs/buckets/custom-domain/
https://github.com/ex-aws/ex_aws_s3?tab=readme-ov-file#bucket-as-host-functionality
=> support S3 "buckets as hosts"

lib/nerves_hub_web/endpoint.ex
=> add `fullsweep_after` to `endpoint.ex`

config/runtime.exs, lib/nerves_hub/accounts/email.ex, lib/nerves_hub/views/email_view.ex, test/nerves_hub/accounts/email_test.exs, test/nerves_hub_web/controllers/account_controller_test.exs, test/nerves_hub_web/controllers/api/org_user_controller_test.exs, test/nerves_hub_web/controllers/org_user_controller_test.exs
- changes to the email subjects
- allow for custom signoffs
- update to the 'closing message', eg. `if you have problems, contact ....`
=> email closing/signoff updates

assets/css/_table.scss, lib/nerves_hub_web/templates/org_certificate/index.html.heex, lib/nerves_hub_web/views/org_certificate.ex
addresses #706 
if a certificate authority expires in 3 months its status is shown as "Expiring Soon"
=> emphasis if certificate authorities have expired or are expiring soon 

lib/nerves_hub/firmwares.ex, test/nerves_hub/firmwares/firmwares_test.exs
noticed this while diving into delta firmware bits
=> cleanup the delta files on transaction rollback

lib/nerves_hub/accounts.ex, lib/nerves_hub_web/live/org/users.ex, test/nerves_hub_web/live/org/users_test.exs
display a flash error if you try to rescind an invite thats already been accepted
=> rescinding an invite thats already been accepted

lib/nerves_hub/scripts/runner.ex, lib/nerves_hub_web/channels/device_channel.ex
If the device's api version is past 2.1.0 then we can push a script directly to the device to be evaluated and returned instead of over the console channel. This has much more reliable output and return capture since we're not using the same console channel as potential other users.
=> Push scripts directly to a device

lib/nerves_hub_web/router.ex, lib/nerves_hub_web/templates/layout/console.html.heex
This bug was introduced when fixing dialyzer errors.
=> Console layout bug

.dialyzer_ignore.exs, lib/nerves_hub/ssl.ex, lib/nerves_hub/uploads.ex, mix.exs
Now we have no dialyzer warnings!
=> Address dialyzer warnings

lib/nerves_hub_web/live/devices/index.html.heex, test/nerves_hub_web/live/devices/index_test.exs
I thought it wasn't working for me, so I added a test, but it seems to be working.
None the less, tests are good
=> add a test for 'set tags' on the Devices page

lib/nerves_hub/firmwares.ex, lib/nerves_hub/firmwares/firmware.ex
I'm going through the different contexts and cleaning up dead code and consistency issues.
=> Cleanup the Firmwares context

assets/js/app.js, assets/package-lock.json, assets/package.json, lib/nerves_hub_web/components/device_header.ex
This is partially cherry picked from the Health PR
The last connected at and last seen at now update using JS, eg. "1 minute ago" -> "2 minutes ago"
=> Use hooks to update the Device connection times

assets/js/app.js, lib/nerves_hub_web/components/device_header.ex
And reduce the timeout interval to 10 seconds
=> Use "just now" instead of "x seconds ago"

lib/nerves_hub/deployments.ex, lib/nerves_hub_web/channels/device_channel.ex, test/nerves_hub_web/channels/websocket_test.exs, test/support/socket_client.ex
- Device connects
- The assigned deployment's archive changed
- Device assigns itself a deployment
- Device's updates_enabled is set to true
=> Send archive payload to devices more often

README.md
username was changed to email in PR #1365
=> update readme to use email address for default dev user

config/runtime.exs
Per postgrex changelog from 0.18.0
https://hexdocs.pm/postgrex/changelog.html#v0-18-0-2024-05-18
Fixes #1445
=> Use `ssl: options` for postgrex config to fix deprecation

lib/nerves_hub/devices.ex, lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/devices/index.html.heex
Filtering and pagination will now be persisted to the query params which also means we get history and linkable filtering.
=> Change devices list to use query params

lib/nerves_hub_web/channels/device_channel.ex
Only unsubscribe and subscribe if the channel has changed
=> Improve deployment channel subscription logic

lib/nerves_hub/firmwares.ex, lib/nerves_hub/firmwares/delta_updater/default.ex
This also improves the error information and logging around deltas.
It does not hook them up to be enabled. This code is currently dead.
=> Fix broken directory creation for firmware deltas

lib/nerves_hub_web/live/devices/index.ex
Because of where the timer was set up, a new timer was added every time the filters were updated. This meant you could have a refresh every second or more often if several filter updates were made.
This also changes the refresh to only happen every 10 seconds.
=> Fix a runaway timer by moving it to `mount`

lib/nerves_hub/devices.ex, priv/repo/migrations/20240910054628_add_indexes_to_devices.exs
Based on the previous PR review. Actually use the new tag function and do some safe creates to allow us (or anyone else) to manually create indexes as needed
=> Indexes followup

lib/nerves_hub/devices/metrics.ex, lib/nerves_hub_web/components/device_health/health_header.ex, lib/nerves_hub_web/live/devices/device_health.ex, lib/nerves_hub_web/live/devices/device_health.html.heex, test/nerves_hub/device_metrics_test.exs, test/nerves_hub_web/live/devices/health_test.exs
Allows displaying other metrics than default in health liveview.
=> Add support for custom metrics

lib/nerves_hub/deployments.ex
Otherwise this broadcasts inside of a transactions and things will refresh from the database (like the calculator or device channel) with stale data.
=> Move broadcasts outside of deployment update transaction

lib/nerves_hub/audit_logs/templates.ex, lib/nerves_hub_web/channels/device_channel.ex
This is 100% a `DeviceChannel` tidy up for readability, with a couple of bits of duplicated logic encapsulated into their own functions.
=> Device channel cleanups

config/test.exs
This has eliminated test failures locally
=> Increase the Repo `queue_target` in the `test` config

.github/workflows/ci.yml
I believe this should make new docker containers get tagged with the version.
=> Add container version tagging

config/runtime.exs, lib/nerves_hub/metrics.ex
=> Remove the NodeReporter metrics logger

CHANGELOG.md
This is changes from the 2.0.0 commit 463ce1d. I don't know what our version plans are but I will continue updating and merging the changelog in the unreleased section as I make these notes for SmartRent.
=> Sync Changelog to latest commit - d8cbfc9

lib/nerves_hub_web/channels/device_socket.ex
Fixes an issue when devices connect using the web endpoint
=> Use the endpoint from the socket

lib/nerves_hub_web/live/devices/device_health.ex
- Fixes a bug where charts didn't render live updates
- Add handling of case where metric types differ between time frames and charts has to be added or removed (shouldn't happen very often though)
=> Metrics charts improvements

lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/devices/index.html.heex
Fixes a bug where selected option wasn't displayed in input.
=> Display selected option when moving device(s) to other product

lib/nerves_hub/deployments.ex, lib/nerves_hub/devices.ex, lib/nerves_hub/firmwares/delta_updater/default.ex, lib/nerves_hub/products.ex, test/support/channel_case.ex
Remade [this branch](https://github.com/nerves-hub/nerves_hub_web/pull/1499) on a fresh main.
=> Add firmware delta generation back

lib/nerves_hub/deployments.ex
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/1596.
=> Fix broken device count for deployments list

mix.exs
=> Update mix.exs Elixir version to match .tool-versions

lib/nerves_hub_web/channels/device_channel.ex
This fixes an error in Sentry when the `DeviceEndpoint` isn't used for device connections
=> Use the correct endpoint for PubSub broadcasts

lib/nerves_hub/devices/connections.ex
Dialyzer was kind enough to find this
=> Use the full module reference for some `@spec`s

assets/js/app.js, assets/package-lock.json, assets/package.json, lib/mix/tasks/gen.devices.ex, lib/nerves_hub/devices.ex, lib/nerves_hub_web/live/dashboard/index.ex, lib/nerves_hub_web/live/dashboard/index.html.heex
See video here: https://github.com/nerves-hub/nerves_hub_web/pull/1611
I tested this with 180.000 active and connected devices (faked). It loaded consistently but took a decent number of seconds. It was much faster down towards 50.000 and snappy below those types of numbers.
Once loaded it becomes easy to navigate and performant. I think this works. We could look at faster options. But the clustering makes 180K possible where it isn't without it.
We could try various things to constrain how many we load. I've looked at recommendations for performance and applied what I found. chunkedLoading option keeps it responsive while loading, renderer using Canvas makes it more performant.
I cut down heavily on non-used values because the first JSON transfer was 18 Mb and I think I got it down to …
=> World Map clustering

config/runtime.exs, lib/nerves_hub_web.ex, lib/nerves_hub_web/components/layouts/sidebar.html.heex, lib/nerves_hub_web/controllers/ui_switcher.ex, lib/nerves_hub_web/dynamic_template_renderer.ex, lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/orgs/index.ex, lib/nerves_hub_web/live_view.ex, lib/nerves_hub_web/mounts/layout_selector.ex, lib/nerves_hub_web/router.ex, lib/nerves_hub_web/templates/layout/_footer.html.heex
By using a plug to set the root layout... 
and a mount to set the inner layout...
and some trickery when selecting the live views template...
and the session to store which UI to use...
we can now allow each user to select which UI to use!
=> Support switching between the new and old UI

lib/nerves_hub/devices/metrics.ex, lib/nerves_hub_web/components/device_health/health_header.ex, lib/nerves_hub_web/components/utils.ex, lib/nerves_hub_web/live/devices/device_health.ex, lib/nerves_hub_web/live/devices/device_health.html.heex, lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/devices/index.html.heex, lib/nerves_hub_web/live/devices/show.ex, lib/nerves_hub_web/live/devices/show.html.heex, test/nerves_hub/device_metrics_test.exs, test/nerves_hub_web/live/devices/health_test.exs, test/nerves_hub_web/live/devices/show_test.exs
Remove separation of default and custom metrics in database queries and make UI handle that instead.
=> Improve metrics queries

assets/js/app.js, assets/js/console.js, assets/ui-rework/app.js
- Removed unused JS args in the two `app.js` files and `console.js`
- Added an ESLint hint to not warn on an empty catch (try-catch)
- And some minor indenting
=> Some minor JS touchups

lib/nerves_hub/devices.ex, lib/nerves_hub/extensions.ex, lib/nerves_hub/products.ex
Rename function to make its purpose clear.
=> Rename function for broadcasting extension events

lib/nerves_hub_web/live/devices/show.html.heex
Prefer the use of a trash icon button + tooltip.
=> A small `Remove from Deployment` UI tweak

lib/nerves_hub/deployments.ex, test/nerves_hub_web/live/deployments/index_test.exs
Missed this one from an earlier PR
=> Exclude deleted devices from Deployment device counts

config/runtime.exs, lib/nerves_hub_web/live/archives.ex
=> Allow for custom `Archive` file size upload limits

assets/ui-rework/app.css, lib/nerves_hub_web/components/device_page/details.ex, lib/nerves_hub_web/components/device_page/settings.ex
Found after deploying some changes
=> Tiny new UI fixes

assets/package-lock.json, assets/package.json, assets/ui-rework/app.css, assets/ui-rework/app.js, lib/nerves_hub_web/components/device_page/details.ex, lib/nerves_hub_web/components/new_ui/device_location.ex
=> New UI working device location

config/runtime.exs, lib/nerves_hub_web/components/fwup_progress.ex, lib/nerves_hub_web/live/devices/settings.html.heex, lib/nerves_hub_web/live/devices/show-new.html.heex, lib/nerves_hub_web/live/devices/show.ex, lib/nerves_hub_web/live/org/certificate_authority_templates/edit_ca_template.html.heex, lib/nerves_hub_web/live/org/certificate_authority_templates/new_ca_template.html.heex, lib/nerves_hub_web/mounts/fetch_product.ex, test/support/conn_case.ex, test/support/data_case.ex
=> New UI: Device page - Part 4

lib/nerves_hub/devices.ex, lib/nerves_hub_web/components/device_page/details.ex, lib/nerves_hub_web/components/pager.ex, lib/nerves_hub_web/controllers/api/device_controller.ex, lib/nerves_hub_web/live/devices/settings.ex, lib/nerves_hub_web/live/devices/show-new.html.heex, lib/nerves_hub_web/live/devices/show.ex
- Tweak some audit logs
- The pager bottom bar should not shrink
- Add support for removing devices from the penalty box
=> New UI: Device page - Part 5 - Getting close

assets/ui-rework/app.css, lib/nerves_hub/firmwares.ex, lib/nerves_hub/firmwares/firmware.ex, lib/nerves_hub_web/components/device_page/activity.ex, lib/nerves_hub_web/components/device_page/settings.ex, lib/nerves_hub_web/components/pager.ex, lib/nerves_hub_web/components/sorting.ex, lib/nerves_hub_web/live/devices/index-new.html.heex, lib/nerves_hub_web/live/firmware.ex, lib/nerves_hub_web/live/firmware_templates/list_firmware_template_new.html.heex, lib/nerves_hub_web/live/firmware_templates/show_firmware_template_new.html.heex
Firmware list, show, upload, and delete.
This includes some sorting options on the list page, and a count of devices using that firmware.
Some device list empty state tweaks (basic but it works)
Minor sorting and pager improvements
=> New UI: Firmwares - Part 1

assets/tailwind.config.js, lib/nerves_hub_web/components/fwup_progress.ex, lib/nerves_hub_web/live/devices/show-new.html.heex
https://github.com/user-attachments/assets/05f3a9cc-7f41-4321-b6af-deabe053f51f
=> Add very shiny progress bar for new UI

lib/nerves_hub_web/dymanic_config_multipart.ex
=> Correct the file size plug regex

lib/nerves_hub_web/components/core_components.ex, lib/nerves_hub_web/live/devices/index-new.html.heex, lib/nerves_hub_web/live/devices/new-new.html.heex, lib/nerves_hub_web/live/devices/new.ex, lib/nerves_hub_web/live/firmware_templates/list_firmware_template_new.html.heex
=> New UI: Add support for "Add Device"

lib/nerves_hub/archives.ex, lib/nerves_hub_web/live/archive_templates/list_archives_template_new.html.heex, lib/nerves_hub_web/live/archive_templates/show_archive_template_new.html.heex, lib/nerves_hub_web/live/archives.ex
Feature parity with the current/old UI
=> New UI: Support Archives

lib/nerves_hub/firmwares.ex, lib/nerves_hub_web/components/navigation.ex, lib/nerves_hub_web/components/sorting.ex, lib/nerves_hub_web/live/firmware.ex, lib/nerves_hub_web/live/firmware_templates/show_firmware_template_new.html.heex
- default ordering direction for the firmwares page
- some function naming
- and some padding that wasn't needed
=> New UI some tweaks along the way

lib/nerves_hub/scripts.ex, lib/nerves_hub_web/live/support_scripts/edit-new.html.heex, lib/nerves_hub_web/live/support_scripts/edit.ex, lib/nerves_hub_web/live/support_scripts/edit.html.heex, lib/nerves_hub_web/live/support_scripts/index-new.html.heex, lib/nerves_hub_web/live/support_scripts/index.ex, lib/nerves_hub_web/live/support_scripts/new-new.html.heex, lib/nerves_hub_web/live/support_scripts/new.ex, lib/nerves_hub_web/live/support_scripts/new.html.heex
Replicate the full Support Script functionality in the new UI.
=> New UI: Support Scripts

assets/ui-rework/app.js, lib/nerves_hub/products.ex, lib/nerves_hub_web/components/core_components.ex, lib/nerves_hub_web/live/product/settings-new.html.heex, lib/nerves_hub_web/live/product/settings.ex
Fully working product settings.
=> New UI: Product settings

lib/nerves_hub_web/components/deployment_page/summary.ex
=> Don't show a link to the archive if there is no archive

lib/nerves_hub_web/components/device_page/details.ex
Check for the various possibilities of cpu data before trying to display it.
=> Handle different metrics cases (cpu temp and usage)

assets/ui-rework/app.css, lib/nerves_hub_web.ex, lib/nerves_hub_web/components/core_components.ex, lib/nerves_hub_web/components/deployment_page/settings.ex, lib/nerves_hub_web/components/device_page/details.ex, lib/nerves_hub_web/components/device_page/settings.ex, lib/nerves_hub_web/components/icons.ex, lib/nerves_hub_web/live/archive_templates/show_archive_template_new.html.heex, lib/nerves_hub_web/live/deployments/index-new.html.heex, lib/nerves_hub_web/live/deployments/show-new.html.heex, lib/nerves_hub_web/live/devices/index-new.html.heex, lib/nerves_hub_web/live/devices/new-new.html.heex, lib/nerves_hub_web/live/firmware_templates/show_firmware_template_new.html.heex, lib/nerves_hub_web/live/product/settings-new.html.heex, lib/nerves_hub_web/live/support_scripts/edit-new.html.heex, lib/nerves_hub_web/live/support_scripts/index-new.html.heex, lib/nerves_hub_web/live/support_scripts/new-new.html.heex
And create a component just for icons
=> New UI: Consistently style buttons and button links

lib/nerves_hub_web/components/device_page/health.ex
=> Don't show the metrics last updated time if it is nil

lib/nerves_hub/archives.ex, lib/nerves_hub/audit_logs/templates/deployment_templates.ex, lib/nerves_hub/audit_logs/templates/device_templates.ex, lib/nerves_hub/deployments.ex, lib/nerves_hub/devices.ex, lib/nerves_hub/firmwares.ex, lib/nerves_hub/scripts.ex, lib/nerves_hub/scripts/script.ex, lib/nerves_hub_web/components/deployment_page/settings.ex, lib/nerves_hub_web/live/archives.ex, lib/nerves_hub_web/live/deployments/index.ex, lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/firmware.ex, lib/nerves_hub_web/live/support_scripts/index.ex
Mostly specs, some aliases and type defs, and some return types that don't match. And one function no longer used.
=> Various fixes found by Dialyzer

lib/nerves_hub/accounts/remove_account.ex, lib/nerves_hub/scripts.ex, lib/nerves_hub/scripts/script.ex, lib/nerves_hub_web/live/support_scripts/edit.ex, lib/nerves_hub_web/live/support_scripts/new.ex, priv/repo/migrations/20250124144709_add_created_and_last_updated_by_to_script.exs, test/nerves_hub/scripts_test.exs, test/nerves_hub_web/live/support_scripts_test.exs
Adds `:created_by` and `:last_updated_by` to `Script` schema.
Note: Does not take account deletion into account. Are user accounts ever deleted at all?
=> Track who created or edited script

lib/nerves_hub/audit_logs/templates/product_templates.ex, lib/nerves_hub/scripts.ex, lib/nerves_hub_web/live/support_scripts/edit-new.html.heex, lib/nerves_hub_web/live/support_scripts/edit.ex
- Delete button (with confirm box) on edit script page.
- Adds `Scripts.delete/3` function.
- Audit log when script is deleted
=> New UI: Allow deletion of scripts

lib/nerves_hub_web/channels/device_channel.ex, lib/nerves_hub_web/live/devices/show.ex
Resolves an error raised by Sentry
=> Standardize loading a device for the device show page

lib/nerves_hub_web/mounts/enrich_sentry_context.ex, lib/nerves_hub_web/router.ex
Useful for understanding how many users have been affected by a bug
=> Enrich the Sentry context with basic user info

lib/nerves_hub_web/channels/device_channel.ex
This fixes issues where socket reconnections cause us to mark a device as having updated several times.
Thankfully we have been receiving this information from Link for around 4 years (thanks to @jjcarstens), we just haven't been using it.
=> Handle cases where, upon connection, we know the device is already updating

assets/ui-rework/hooks/toolTip.js, lib/nerves_hub_web/components/device_health/health_status.ex, lib/nerves_hub_web/components/device_page/details.ex
Allow the tooltip position (and arrow) to be configured, and change the placement of the tooltip on the Device show page.
=> Tooltip improvements

lib/nerves_hub/devices.ex, lib/nerves_hub/devices/device.ex, test/nerves_hub/devices_test.exs
This fixes a DB constraint error
=> Make sure all health reports are deleted when a device is destroyed

lib/nerves_hub/deployments/deployment.ex
We will remove this from the DB schema in March
=> Comment out `recalculation_type`

lib/nerves_hub/devices/filtering.ex, lib/nerves_hub_web/live/devices/index-new.html.heex, lib/nerves_hub_web/live/devices/index.ex
And fix a crash related to device metric filtering that appeared in the old UI
=> Add device metric filtering support to the new UI

lib/nerves_hub_web/components/device_page/details.ex
=> Fix incorrect Firmware UUID shown in firmwares list

lib/nerves_hub_web/channels/user_console_channel.ex, lib/nerves_hub_web/components/device_page/console.ex, lib/nerves_hub_web/live/devices/show.ex
=> Show a toast notification when a console upload starts and finishes

lib/nerves_hub_web/live/deployments/index-new.html.heex
=> Add the deployment version constraint to the deployments list

lib/nerves_hub_web/live/deployments/newz.ex
=> Redirect to newly created deployment

lib/nerves_hub/devices/filtering.ex, lib/nerves_hub_web/live/devices/index-new.html.heex, lib/nerves_hub_web/live/devices/index.ex, test/nerves_hub_web/live/devices/index_test.exs
I think it'd be useful to filter devices without deployment.
=> Filter devices without deployment

lib/nerves_hub/managed_deployments.ex
This covers:
- Device List filters
- Device List multi actions
- Device Show eligible deployments
Closes #1959
=> Order Deployments in the various dropdowns

lib/nerves_hub_web/channels/device_channel.ex
I missed this when rebasing #1653 😬
=> Fix bug from rebase that was sending extension requests when it shouldn't be

assets/ui-rework/app.js, assets/ui-rework/hooks/supportScriptOutput.js, lib/nerves_hub_web/components/device_page/details.ex
=> Improve the support script output

lib/nerves_hub_web/components/device_page/console.ex
=> Fix an assigns check in the console component

lib/nerves_hub/devices/connections.ex
Without this fix there is an influx of false positive stale connection cleanups
=> Use the max possible jitter when cleaning stale connections

assets/ui-rework/hooks/console.js, lib/nerves_hub/tracker.ex, lib/nerves_hub_web/components/device_page/console_tab.ex, lib/nerves_hub_web/components/device_page/health_tab.ex, lib/nerves_hub_web/live/devices/show-new.html.heex, lib/nerves_hub_web/live/devices/show.ex, lib/nerves_hub_web/live/devices/show.html.heex, test/nerves_hub_web/live/devices/show_test.exs
After deploying to NervesCloud I noticed a bunch of Sentry errors (and one web inspector console error) related to some recent PRs.
=> Fixes found after a deploy

.github/workflows/ci.yml, lib/nerves_hub/utils/base62.ex, lib/nerves_hub_web/auth.ex, lib/nerves_hub_web/live/devices/show.ex, mix.exs
This adds dialyzer as a step in CI. PLTs are cached by elixir and erlang version.
=> Run dialyzer in GH actions, fix dialyzer warnings

lib/nerves_hub_web/components/device_page/details_tab.ex
=> Show a spinner when a Support Script is running

priv/repo/migrations/20250502234734_use_citext_for_user_email.exs
This takes care of case sensitivity issues for us, which we aren't currently handling correctly.
=> Use the `citext` column type for a users email

lib/nerves_hub/helpers/logging.ex, lib/nerves_hub_web/channels/presence.ex, lib/nerves_hub_web/live/devices/show.ex
Adds error handling to Presence functions.
Also adds docs and specs.
=> Handle user presence tracking failing

config/config.exs
This looks to have been removed by mistake
=> Add the `DeviceHealthTruncation` cron back

.cspell.json, README.md, priv/repo/seeds.exs
Update pre-generated account with new password to pass validation of minimum 12 characters.
Noticed this during setup.
=> Update pre-generated account

lib/nerves_hub_web/components/device_page/details_tab.ex
I broke this layout in #2103; I forgot to spot-check a device with a deployment group.
=> Fix device details deployment groups layout

.formatter.exs, lib/nerves_hub/accounts/remove_account.ex, lib/nerves_hub/accounts/user_token.ex, lib/nerves_hub/application.ex, lib/nerves_hub/devices.ex, lib/nerves_hub/devices/metrics.ex, lib/nerves_hub/firmwares/update_tool/fwup.ex, lib/nerves_hub/firmwares/upload/s3.ex, lib/nerves_hub/managed_deployments/distributed/orchestrator.ex, lib/nerves_hub/managed_deployments/distributed/orchestrator_registration.ex, lib/nerves_hub/metrics_poller.ex, lib/nerves_hub/ssl.ex, lib/nerves_hub_web.ex, lib/nerves_hub_web/api_spec.ex, lib/nerves_hub_web/channels/device_socket.ex, lib/nerves_hub_web/channels/extensions_channel.ex, lib/nerves_hub_web/components/ca_helpers.ex, lib/nerves_hub_web/components/core_components.ex, lib/nerves_hub_web/controllers/account_controller.ex, lib/nerves_hub_web/controllers/api/schemas/ca_certificate_schemas.ex, lib/nerves_hub_web/live/devices/index.ex, lib/nerves_hub_web/live/org/certificate_authorities.ex, lib/nerves_hub_web/live/orgs/index.ex, test/nerves_hub/firmwares/update_tool_test.exs, test/nerves_hub/managed_deployments_test.exs, test/nerves_hub_web/channels/websocket_test.exs, test/nerves_hub_web/live/devices/show_test.exs, test/nerves_hub_web/live/new_ui/devices/activity_tab_test.exs, test/support/fixtures.ex
This one is 👨‍🍳 💋 
So many small efficiency fixes.
=> Quokka single node fixups

lib/nerves_hub_web/components/device_page/details_tab.ex, test/nerves_hub_web/live/new_ui/devices/show_test.exs
It's essentially duplicated for some unknown reason
=> Remove the default manual update submit button

lib/nerves_hub/devices.ex, lib/nerves_hub/devices/device.ex
Just a tiny little change which caught my eye
=> Encapsulate logic related to resetting update attempts into a changeset function
