nerves-hub/nerves_hub_web

- docs/client-server.md
Why
---
It's important to have a well thought out and consistent communication
procedure.
How
---
A `/docs/` directory was added and the documentation was put in there as a
markdown file.
Closes #64
> Document client server communcation

- test/nerves_hub/integration/websocket_test.exs
Why:
* It is good to have robust tests.
* Adding `server_name_indication` for the `socket_opts` in the
`@proxy_socket_config`.
> Address test failure on some systems

- lib/nerves_hub/accounts/accounts.ex
- lib/nerves_hub_web/controllers/account_controller.ex
- test/nerves_hub/accounts/accounts_test.exs
Why:
* `create_tenant` function in `accounts.ex` had outgrown itself.
* Needed old (typical) functionality of `create_tenant`
* moving existing `create_tenant` to `create_tenant_with_user`.
* changing the (only) call to `create_tenant` to match.
* re-implementing typical `create_tenant`.
* Testing functionality around creating tenants.
Caveats:
* No controller tests.
* Could still use some more tests for `accounts.ex` in the new `accounts_test.exs`
> Help the Tenants

- lib/nerves_hub/deployments/deployment.ex
- lib/nerves_hub/deployments/deployments.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/devices/devices.ex
- lib/nerves_hub_web/controllers/deployment_controller.ex
- lib/nerves_hub_web/controllers/device_controller.ex
- test/nerves_hub/deployments/deployments_test.exs
- test/nerves_hub/devices/devices_test.exs
- test/nerves_hub/firmwares/firmwares_test.exs
- test/nerves_hub_web/controllers/deployment_controller_test.exs
- test/nerves_hub_web/controllers/device_controller_test.exs
- test/support/browser_case.ex
- test/support/fixtures.ex
Why:
* I will feel more confident developing upcoming features if there are
tests for the underlying functionality.
* `deployments_test.exs`, minor refactoring of `deployments.ex` and
`deployment.ex`, and updating `deployment_controller.ex` to match.
* `devices_test.exs`, minor refactoring of `devices.ex` and
`device.ex`, and updating `devices_controller.ex` to match.
* fixtures in `test/support/fixtures.ex`
Other Notes:
* I only added test coverage for functions that would directly impact my
upcoming feature(s).  In order to improve overall test coverage without
sacrifing velocity entirely, I will continue to follow this pattern in
the future.
> Device,Deployment tests and fixtures

- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/devices/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/device_controller.ex
- test/nerves_hub/integration/websocket_test.exs
Why:
* We want to know if a device needs new firmware ASAP.
* https://github.com/nerves-hub/nerves_hub/issues/79
* Checking if `%{"version" => version}` in the join payload matches the
target version in the database, and acting accordingly.
* Also updates the `current_version` in the database to the version that
is reported in the join payload.
Caveats:
* Cannot send out a message with instructions for updating firmware
because that is yet to be implemented.
> Device Channel checks for firmware update on join

- Makefile
It turns out that `source` wasn't available in the shell that `make` was
invoking on my Linux laptop. Apparently `.` is POSIX and `source` is or
was originally a Bash alias and is less portable.
> Replace "source" with "." in Makefile

- .circleci/config.yml
This adds support for `meta-uuid` in the firmware metadata.
> Bump to fwup v1.2.0 on CircleCI

- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/devices/devices.ex
- lib/nerves_hub/firmwares/firmwares.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/user_socket.ex
- lib/nerves_hub_web/templates/device/edit.html.eex
- lib/nerves_hub_web/templates/device/index.html.eex
- priv/repo/migrations/20180618171943_device_deployment_id.exs
- test/nerves_hub/devices/devices_test.exs
- test/nerves_hub/integration/websocket_test.exs
- test/support/fixtures.ex
Why:
* We want to make it easy to tell if a device needs an update.
* We want to be able to provide a URL when a device needs an update.
* Migration that adds `:target_deployment` and `:current_firmware` to
`Device`.
* Logic in the `device_channel` which finds the url for an update if it
is available.
Caveats:
* Web views/UI for the new fields need to be worked out.
> current_firmware and target_deployment for device

- config/prod.exs
- rel/Dockerfile.build
- rel/config.exs
- rel/scripts/docker-entrypoint.sh
- rel/scripts/ecs-cluster.sh
- rel/scripts/s3-sync.sh
- rel/vm.args
We are running at minimum two nodes in production in different availability zones and will need to cluster the group since we are using phoenix channels.
> Enable erlang distribution in production

- rel/scripts/ecs-migrate.sh
This will poll aws and wait until the task that was executed to run the migrations returns. This ensures that the data has been migrated prior to updating the application code.
> Wait for migrations and seeds to complete before upgrading servers.

- Makefile
- apps/nerves_hub/mix.exs
- mix.exs
Why:
* It got overlooked in the switch to the umbrella.
* `make reset-db` was broken for me, so I figured it was a matter of
time for others.
* fixing the path of `seeds.ex`
> Fix paths to seeds.exs

- apps/nerves_hub/lib/nerves_hub_web/controllers/firmware_controller.ex
- apps/nerves_hub/test/nerves_hub_web/controllers/firmware_controller_test.exs
Why:
* We want users to know why their firmware didn't make the cut
* Addresses: https://github.com/nerves-hub/nerves_hub/issues/109
* Checking for an error in the changeset and flashing that error.
> Let user's know if their firmware changeset was invalid

- .circleci/config.yml
This PR adds some quality assurances to the deployment process
* Switched build image to use alpine (Speed up circle tasks)
* Use `ecs-deploy` to execute deployments. Set `--enable-rollback` which will automatically roll back a failed deployment. This will prevent failed deployments from flapping in production which costs money.
* Run builds and deploys for umbrella apps in parallel.
> Run parallel builds and deploys

- Makefile
- apps/nerves_hub_core/config/dev.exs
- apps/nerves_hub_core/config/prod.exs
- apps/nerves_hub_core/config/test.exs
Why
---
* Previously dev and test were sharing the `db` database causing tests
to fail surprisingly
How
---
* Set test-specific `DATABASE_URL` env var in Makefile when running
tests
* Remove vestigial (even prior to this commit) `url: ...` and
`database: ...` mix repo configurations
PR
--
This addresses the issue of dev records being propagated "into" test and causing
tests to fail. There were a few misleading things at play here.
* Test config was configuring both `:url` and `:database`, potentially
implying some sort of merged functionality, or that the `:database` was taking
precedence. This is not the case, when `:url` is specified no other config is
aknowledged
* `:url` and friends like `:database` in mix configs were having no impact on
reality because `NervesHubCore.Repo` pulls in …
> Configure distinct db in test

- apps/nerves_hub_core/config/prod.exs
This config has no effect since the `NervesHubCore.Repo` module's init
callback reads from runtime and overrides `:url` anyway.
> Remove core prod ecto url config

- apps/nerves_hub_core/priv/repo/seeds.exs
Why:
* We were taking the whole response of `create_tenant` (`{:ok,
%Tenant{}}`)
> Make sure we pass a tenant to create_user

- apps/nerves_hub/config/prod.exs
These variables need to be replaced at runtime not compile time.
> Fix prod email config for runtime replacement

- apps/nerves_hub_device/config/config.exs
- apps/nerves_hub_device/config/dev.exs
- apps/nerves_hub_device/config/prod.exs
- apps/nerves_hub_device/config/test.exs
- apps/nerves_hub_www/config/config.exs
The pubsub group is shared across multiple umbrella apps.
> Change pubsub name to NervesHubWeb.PubSub

- apps/nerves_hub_core/lib/nerves_hub_core/application.ex
- apps/nerves_hub_core/lib/nerves_hub_core/deployments.ex
- apps/nerves_hub_core/lib/nerves_hub_core/deployments/deployment.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/test/nerves_hub_core/deployments/deployments_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
- test/support/fixtures.ex
Why:
*  We want to tell devices when they need new firmware
* On an update to a deployment, asyncronously send a message to the
`device:identifier` topic for each relevant device.
Other changes:
* Don't allow for the creation of a deployment with `%{is_active: true}`
> Eager Firmware Update Message

- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user_certificate.ex
- apps/nerves_hub_core/lib/nerves_hub_core/products/product.ex
- apps/nerves_hub_core/priv/repo/migrations/20180216143258_deployments.exs
- apps/nerves_hub_core/priv/repo/migrations/20180710140434_create_products.exs
- apps/nerves_hub_core/priv/repo/migrations/20180724191309_create_user_certificates.exs
- apps/nerves_hub_core/priv/repo/migrations/20180730195025_fix_unique_indices.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/deployments/deployments_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/products/products_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
Why:
* `create/1` was not called on `:products_tenant_id_name_index` or
`:user_certificates_user_id_serial_index`.
* Creating a new migration that _actually_ creates these indices.
* Removing the lines where they were defined, but not created in the
original migrations (to avoid developer confusion).
* Testing for uniqueness in these two indices.
> Fix unique indices

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/tenant_key.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/firmware.ex
- apps/nerves_hub_core/priv/repo/migrations/20180731143210_unique_firmware_and_tenant_keys.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
- test/support/fixtures.ex
Why:
* It's important that some things really are special.
* https://github.com/nerves-hub/nerves_hub_web/issues/152
* https://github.com/nerves-hub/nerves_hub_web/issues/153
* Enforce uniqueness on firmware uuids within the scope of a product.
* Enforce tenant key `:key` uniqueness across all tenant keys.
* Tests to back it up.
> More uniqueness

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account/edit.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/account_controller_test.exs
Why:
* It's good to have that in the UI
* The beginnings of addressing: https://github.com/nerves-hub/nerves_hub_web/issues/144
* Adding the button.
* Testing for it's presence.
> Add a button that links to the user certificates

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/user_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
Adds an API for registering new user accounts fro the CLI
post /users/register
Parameters:
* name: the username and default org name
* email: the email to use
* password: the password to set
Passwords are going to be encrypted through the ssl connection to the API and timing attacks are handled by our use of bcrypt
> Add users/registration API for creating accounts from the CLI

- apps/nerves_hub_core/config/config.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/user_socket.ex
After moving the `Phoenix.PubSub.PG2` server start to `nerves_hub_core` fastlane options were missing that are typically added by default when `Phoenix.Endpoint` would start the PubSub server. This fixes the issue where `%Phoenix.Broadcast.Socket{}` messages were being sent to the `handle_out/2`
> Fix Phoenix Presence messages by enabling fastlane

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/key_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/key_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/key_controller.test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/key_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_key_controller.ex
This PR adds routes for managing firmware keys
* get `/keys` - list all keys for the org
* post `/keys` - create a new key
* delete `/keys/:name` - delete a key by name
* get `/keys/:name` - show information about a single key
> Add API for managing firmware keys

- apps/nerves_hub_core/config/dev.exs
- apps/nerves_hub_core/config/prod.exs
- apps/nerves_hub_core/config/test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/certificate_authority.ex
- apps/nerves_hub_www/config/dev.exs
- apps/nerves_hub_www/config/prod.exs
- apps/nerves_hub_www/config/test.exs
The CA API was moved from `nerves_hub_www` to `nerves_hub_core` but the config reference were not updated. Since `nerves_hub_api` does not depend on `nerves_hub_www`, the configs for the ca under this application were stripped from the final release. This PR fixes the communication between the API and the CA.
> Move CA config to nerves_hub_core to prevent release stripping

- apps/nerves_hub_core/config/prod.exs
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/test/nerves_hub_core/deployments/deployments_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/user_socket.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
- rel/scripts/slack-notification.sh
Turns out that you can only send "disconnect" events to socket id topics. In order to differentiate the recipients we are subscribing to a `device:#{device.id}` topic inside the channel. I have also updated the topics for connecting to represent `firmware:#{uuid}` so there are no collisions between the self subscribed devices and firmwares. I have tested this in prod and its sending update messages.
> Fix channels

- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
Currently there is an issue where deployments are sending devices firmware updates for other products. This PR fixes the issue and adds some tests to ensure it doesn't happen again.
> Prevent deployments from updating devices cross product

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_certificate_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/fallback_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/plugs/org.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/plugs/product.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/plugs/user.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/error_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_certificate_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/firmware_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/key_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
- apps/nerves_hub_core/priv/repo/migrations/20180819002856_associate_users_and_orgs.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
This updates the API to support many to many on users and orgs. The biggest change is in the routing.
Here is what the new routes list looks like.
```
POST    /users/register
POST    /users/auth
POST    /users/sign
GET     /users/me
GET     /orgs/:org_name/keys
POST    /orgs/:org_name/keys
GET     /orgs/:org_name/keys/:name
DELETE  /orgs/:org_name/keys/:name
POST    /orgs/:org_name/devices
GET     /orgs/:org_name/devices/:device_identifier
GET     /orgs/:org_name/devices/:device_identifier/certificates
POST    /orgs/:org_name/devices/:device_identifier/certificates/sign
GET     /orgs/:org_name/products/:product_name/firmwares
GET     /orgs/:org_name/products/:product_name/firmwares/:uuid
POST    /orgs/:org_name/products/:product_name/firmwares
DELETE …
```
> Update API to support many to many users and orgs

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_key_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/product_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/session_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/ensure_logged_in.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/fetch_product.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/session/new.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/account_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs
- apps/nerves_hub_www/test/support/browser_case.ex
Why:
*  We want it to be easy to switch orgs
* Adding a dropdown on the left of the nav that shows your current org
and allows you to pick (not implemented) a new org.
* Storing `current_org_id` on the session.
Other Changes:
* Fix bug that overwrote previous orgs when adding new orgs to a user.
* Fix the uniqueness bug with many to many orgs.
> Multiple Org Handling in UI

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
Why:
* Calling "update" on a user while passing `%{orgs: [org1, org2]}` is
confusing and requires a lot of work _outside_ of the `nerves_hub_core`
application in order to ensure the desired effect occurs.
* I think there were some bugs (of no consequence elsewhere in the outside application yet) around updates
* adding `add_user_to_org` and `remove_user_from_org` functions which
clarify what's going on.
> Add clarity around addition/subtraction of user-orgs

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/product_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/product_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_controller_test.exs
Adds the following endpoints
* GET `orgs/<org_name>/products` - List all products for org
* POST `orgs/<org_name>/products` - Create a new product
* GET `orgs/<org_name>/products/<product_name>` - Show a product
* PUT `orgs/<org_name>/products/<product_name>` - Update a product
> Products api

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/fallback_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/firmware_controller_test.exs
Adds the following endpoint
* POST `/orgs/<org_name>/products/<product_name>/deployments`
> Add API for creating deployments

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices/device.ex
- apps/nerves_hub_core/priv/repo/migrations/20180824143209_cascading_device_cert_deletes.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/fetch_device.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
Why:
* If we want to limit devices per org/product, we need to allow users to
delete devices: https://github.com/nerves-hub/nerves_hub_web/issues/217
* routes, controller, and context functions.
* tests to verify behavior
> Delete devices via browser and API

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/session_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/form.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/new.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs
- apps/nerves_hub_www/test/support/browser_case.ex
Why:
* We want users to choose their org
* Implementing a `set_org` endpoint by the session controller which
switches the org that is on the session.
* Implementing a `create` endpoint for the org controller that creates a
new org and adds the current user to that org.
> Switch/Create org from dropdown.

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/new.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs
Why:
* https://github.com/nerves-hub/nerves_hub_web/issues/235
* It was directing to an invalid route.
* Change the href for the back button.
* Checking that we don't link to the invalid route.
> Fix the new org back button

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
Why:
* It was broken due to trying to preload attributes from a user that did
not exist.
* Move the preloads to after we're sure we have an existing user.
* Add tests to make sure that this doesn't happen again.
> Fix login with invalid email

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_core/lib/nerves_hub_core/deployments/deployment.ex
- apps/nerves_hub_core/priv/repo/migrations/20180829201933_unique_deployment_per_product.exs
- apps/nerves_hub_core/test/nerves_hub_core/deployments/deployments_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex
Why:
* Humans will reference deployments by name, not by firmware uuid.
* https://github.com/nerves-hub/nerves_hub_web/issues/225
* Adding `product_id` back onto a `Deployment`
* Adding a `unique_index` for `product_id`-`name` combinations on a
`Deployment`
* Testing that this constraint is in place.
> Deployment name is unique wrt product

- apps/nerves_hub_core/config/config.exs
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/firmware.ex
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
Why:
* S3 Billz
* Configurable limit on per-product firmwares
* Tests to enforce
> Limit firmware per product

- apps/nerves_hub_core/config/config.exs
- apps/nerves_hub_core/lib/nerves_hub_core/deployments/deployment.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices/device.ex
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
Why:
* We want to limit devices per org in a configurable way.
* Adding `validate_device_limit` to the `device` changeset.
* Write a test to enforce that the configurable device limit is
enforced.
> Add configurable per org device limit

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
Why:
* It's functionality was never implemented.
* Non-working buttons are not a feature placeholder, especially when
users will see and interact with the non-working button.
Other Notes:
* I did add an issue to address what this feature should look like: https://github.com/nerves-hub/nerves_hub_web/issues/248
> Remove device disable button

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
Why:
* It was sending you to the `home_path` when it shouldn't
* https://github.com/nerves-hub/nerves_hub_web/issues/204
* Adding a `logo_href` function in the layout view
> Fix logo href

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_core/lib/nerves_hub_core/deployments.ex
This PR addresses the following two issues
1. Could not update firmware_uuid through the API when modifying a deployment.
2. Modifications to the deployment would trigger firmware updates for devices whose firmware is already equal to the deployment target.
> Fix issues preventing updating firmware for deployments

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/js/socket.js
- apps/nerves_hub_www/lib/nerves_hub_www_web/channels/devices_channel.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/channels/user_socket.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/endpoint.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/ensure_logged_in.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/channels/devices_channel_test.exs
- test/support/fixtures.ex
Why
---
- So there is a way to hook into an organization's devices' status
lifecycles
How
---
- When a device connects to a `"firmware:#{fw_uuid}"` topic, it
`Presence.track/4`s itself on a `"devices:#{org_id}"` topic
- When a browser connects to a `devices:#{org_id}` topic, it will
receive presence state and diffs regarding all devices within that org
> Enable real time device status updates

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/user_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/user_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/invite.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user.ex
- apps/nerves_hub_core/priv/repo/migrations/20180810151416_default_user_org.exs
- apps/nerves_hub_core/priv/repo/migrations/20180819002856_associate_users_and_orgs.exs
- apps/nerves_hub_core/priv/repo/migrations/20180903222410_users_name_to_username.exs
- apps/nerves_hub_core/priv/repo/seeds.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/user_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account/invite.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account/new.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/dashboard/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/forgot_password.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/invite.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/invite.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/account_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/dashboard_controller_test.exs
- test/support/fixtures.ex
Why
---
* Addresses #242
How
---
* User schema name is now username, is unique, and can only contain url
safe characters
* Invites no longer dictate username, it can be choosen on invite
acceptance
* Update fixtures, seeds, controllers, views, and tests to respect
changes
> Rename name on user to username

- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org.ex
- apps/nerves_hub_core/priv/repo/migrations/20180920134303_unique_org_names.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
Why:
* We need to look up orgs by name via the API.
* Adding a unique index and test of uniqueness for the org name.
> Unique Org Names

- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_core/mix.exs
- apps/nerves_hub_core/priv/repo/seeds.exs
- apps/nerves_hub_core/test/nerves_hub_core/deployments/deployments_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
- test/support/fixtures.ex
Why:
* It's useful to see data in the web views to get a feel for how the app
will look/feel.
* I was trying to determine if
https://github.com/nerves-hub/nerves_hub_web/issues/10 was able to be
marked as closed, and realized that I couldn't tell without manually
creating a bunch of stuff.
* Adding a user with two orgs where each org has multiple devices,
firmwares and deployments in `seeds.exs` when `Mix.env() == :dev`
> Add richer seeds for :dev env

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/plugs/org.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/file.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/s3.ex
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex
- test/support/fixtures.ex
Resolves #258
What
----
- When creating or deleting firmware files always work inside a
transaction and act on the database record before the file persistance
to ensure a persisted file (remote or local) will not be dereferenced
but still exist
How
---
- `NervesHubCore.Firmwares`
- Remove `prepare_firmware_params/2` and roll functionality into
`create_firmware/3` to publicly ensure an atomic operation
- Add `metadata/2` to `Upload.S3` and `Upload.File` modules so that
information about about where a firmware file will be persisted to is
available before actually persisting it
- `NervesHubCore.Fixtures`
- Split firmware file creation into its own fixture apart from
firmware creation within the application
---
Not overjoyed with https://github.com/nerves-hub/nerves_hub_web/pull/274/files#dif …
> Transactional firmware creation and deletion

- apps/nerves_hub_www/assets/js/app.js
Resolves #268 
Why
---
- Connecting to this socket will fail on non-authed / non-devices pages flooding
client and server logs with failures
How
---
- Only `require` the `socket.js` code when on the devices page
---
This is a somewhat naive approach but gets the job done now while dodging
heavier front end efforts. Open to discussion about alternate approaches.
> Only open socket on devices page

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
When the device page loads all device statuses load initially as "online" and then update quickly to "offline". This is due to presence not handling the nil case for when a device is missing from presence completely. This adds the missing case. I am unsure how to add a test without making a decision on a front end testing library.
> Fix device status on load is always "online"

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
This adds the ability for `nerves_hub_cli` and other API consuming applications to update existing devices.
> Allow updating a device from the API

- apps/nerves_hub_core/config/config.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org_limit.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices/device.ex
- apps/nerves_hub_core/priv/repo/migrations/20180927020424_add_devices_org_limit.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
This PR adds `:devices` to `org_limits` and enabled setting the limit per `Org`
> Allow quantity of devices to be set per Org

- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/s3.ex
I dunno, in one of the merges last night, this some how became undone
> Fix pattern match on s3 key

- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/upload/s3.ex
Deleting firmware from S3 is currently raising. It turns out that in the past, it was just preparing a transaction and not applying the request. This fixes both the return pattern match as well as actually deleting the files.
> Fix firmware delete on S3

- apps/nerves_hub_api/lib/nerves_hub_api_web.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/fallback_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/user_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/firmware_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org_limit.ex
- apps/nerves_hub_core/lib/nerves_hub_core/application.ex
- apps/nerves_hub_core/lib/nerves_hub_core/deployments.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/firmware.ex
- apps/nerves_hub_core/lib/nerves_hub_core/firmwares/gc.ex
- apps/nerves_hub_core/priv/repo/migrations/20180927234934_add_firmware_ttl_org_limit.exs
- apps/nerves_hub_core/priv/repo/seeds.exs
- apps/nerves_hub_core/test/nerves_hub_core/firmwares/firmwares_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- test/support/fixtures.ex
Uploading test firmware from CI can quickly result in clutter and should be garbage collected. This PR introduces a "time to live" setting that is applied to firmware records upon creation. TTL is stored in seconds and represents the time to keep firmware _after_ all its associations have been removed. This is tracked by setting the `tty_until` `utc_datetime` stamp on the firmware record whenever is has been removed from all associations. If an association is made again, the timestamp is removed and it will not get garbage collected. The default `ttl` is set for 7 days and can be configured per org using `org_limits`.
As a side effect, the API needed to change how it accepts the firmware upload from the CLI in order to accept both a file and additional params like `ttl`. This way, CI can …
> Firmware TTL

- apps/nerves_hub_core/config/dev.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/endpoint.ex
This was a typo from a [previous
commit](https://github.com/nerves-hub/nerves_hub_web/commit/8669c534c5bb2d880a20e8ca5ffad7f95b096f48#diff-3ee9958556f69d386641ab916f438305R6)
Fixes  #292
> Fix wrong path for local firmware downloads

- apps/nerves_hub_core/lib/nerves_hub_core/accounts.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/org_key.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_key_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_key/form.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_key_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_key_controller_test.exs
Why:
* Server was returning 500 when users tried to delete a key that was
tied to an existing firmware: https://github.com/nerves-hub/nerves_hub_web/issues/291
* Checking the constraint in a changeset.
* Rendering a sensible error in the UI.
* Testing this behavior
> Render error for org key with existing firmware

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_certificate_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/user_controller.ex
- apps/nerves_hub_core/lib/nerves_hub_core/accounts/user_certificate.ex
- apps/nerves_hub_core/lib/nerves_hub_core/certificate.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices/device_certificate.ex
- apps/nerves_hub_core/priv/repo/migrations/20181004195340_add_certificate_info.exs
- apps/nerves_hub_core/test/nerves_hub_core/accounts/accounts_test.exs
- apps/nerves_hub_core/test/nerves_hub_core/devices/devices_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/account_certificate_controller_test.exs
- test/support/fixtures.ex
In preparation for providing our own certificate revocation lists, we need to begin to track the `authority_key_id` from the certificate in addition to the `serial_number`.
> Capture additional certificate information required for revocation

- apps/nerves_hub_core/lib/nerves_hub_core/release/tasks.ex
- apps/nerves_hub_www/rel/Dockerfile.build
The deployment was failing on the migration step because the LOCAL_IPV4 variable that is used for the node name is only being set if the node is started with clustering.
> Set local_ipv4 address for migration container

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/ca_certificate_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/ca_certificate_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/ca_certificate_controller_test.exs
- apps/nerves_hub_core/lib/nerves_hub_core/devices.ex
- apps/nerves_hub_core/lib/nerves_hub_core/devices/ca_certificate.ex
- apps/nerves_hub_core/priv/repo/migrations/20181201000818_ca_certificate_global_unique.exs
This PR adds resource endpoints for managing `ca_certificates`. 
The following endpoints are added:
* POST `/:org_name/ca_certificates` - create a new certificate from a pem.
* GET `/:org_name/ca_certificates` - list all ca_certificates
* GET `/:org_name/ca_certificates/:serial` - show information about a single certificate
* DELETE `/:org_name/ca_certificates/:serial` - delete the certificate with the specified serial
> Add API for interacting with CA certificates

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/application.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/gc.ex
- rel/config.exs
- rel/scripts/gc.sh
Moves the firmware GC task out of the `nerves_hub_web_core` application supervisor so it can be invoked from the command line. In production, since www, device, and api all run in their own containers and they all start `nerves_hub_web_core`, The firmware gc task loop is being called on all these containers. This routine should only ever be run on a single schedule in prod.
> Scheduled GC

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/release/tasks.ex
- rel/scripts/gc.sh
This shares similar logic with running the migration task.
> Ensure apps and repos are started when running GC

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/device_view.ex
- apps/nerves_hub_api/mix.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- test/support/fixtures.ex
This PR adds the following endpoint to the API for verifying. 
* POST `/orgs/:org_name/devices/auth
The payload expects to take a base64 encoded PEM formatted certificate. If the certificate is valid for a device in the org, the device record is returned. This allows 3rd party applications to perform certificate validation through the NervesHub API.
> Add endpoint for verifying device auth

- apps/nerves_hub_api/config/test.exs
- apps/nerves_hub_www/config/test.exs
The ports for test were different then dev which prevented the system from coming up, as a whole, under the test environment.
> Fix test port numbers

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/certificate.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device_certificate.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20181214143504_device_certificate_allow_lin_ski.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
Device certificates should not be required to present a subject key identifier in their certificates. This is a non critical extension.
> Allow device certificates to have a null subject key id

- apps/nerves_hub_device/config/dev.exs
- apps/nerves_hub_device/config/prod.exs
- apps/nerves_hub_device/config/test.exs
This enables `fail_if_no_peer_cert`. It's my understanding that everything that happens on the device endpoint is protected by a peer cert.
> Enable fail if no peer cert for device endpoints

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/ensure_logged_in.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex
Doesn't look the greatest in my opinion but i think this is useful. It might even be useful to display the current usage for these things in a followup.
> Add table to Org panel to display limits

- apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/plugs/device_test.exs
Why
---
* A device with no last known firmware that tries to use device apis to
fetch an update would previously fail to resolve new firmware because
eligible deployments can only be resolved if a last known firmware
exists for a device
PR
--
* Resolves #322 
* Is powered by: https://github.com/nerves-hub/nerves_hub/pull/50 but is written to be backwards compatible without it
> Set last known firmware in device plug

- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/controllers/device_controller.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/controllers/device_controller_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/plugs/device_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
Fixes #309 
This will dispatch eligible update_available channel messages when a `Device` is updated.
> Update devices when tags are updated.

- apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex
PR
--
* Resolves #327
Why
---
* Some devices poll for updates via `NervesHub.update()` which prior to
this commit would not cause the device to have a device certificate
generated for them
How
---
* Leverage `NervesHubDevice.SSL.verify_device/1` like the device socket
does
> Support just-in-time registration in device api

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_key_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/new.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_key/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_key/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_key/new.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_key/show.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_key_controller_test.exs
This only affects the UI. I didn't make any code changes especially since "org" seems clear and easy to type. Spelling out "organization" reads better to me in the docs. I saw that GitHub also uses the term "organization" rather than "org", and since our user/org setup is similar, it made sense to emulate their decision.
Note that there's a inconsistency in sentence vs. title case, but it's more than just the org/organization. I was going to make a pass at that in a future PR.
> Rename references to org to organization

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/plugs/device_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/priv/repo/seeds.exs
- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/js/dates.js
- apps/nerves_hub_www/assets/yarn.lock
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
(related to: https://github.com/nerves-hub/nerves_hub_web/issues/31)
Why:
* It's useful, especially for users whose devices are not maintaining a
constant connection.
* Updating `last_communication` in `plug` for http requests and on
`join` function for channels.
Other Notes:
* Though the DB field is named `last_communication`, it is currently only being updated on _connection_, so the language in the UI reflects that.
> Update last_communication info for devices, and render in frontend.

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
This will allow devices that don't have a known firmware connect to the channel, enabling them to get a later update.
> Allow devices with unknown firmware to connect.

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
Since the device status also contains firmware version, and when the firmware is unknown it says `unknown`. I think that we should still illustrate in the status that the device is online instead of also having it say something else.
Before:
After:
> Show online as status for unknown firmware

- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/home/index.html.eex
Why
---
* A scroll bar is showing when it isn't needed and it looks bad with the
`<pre>` as-is.
How
---
* Add `code-snippet` class to the element that sets the `overflow`
attribute.
* Some new lines got removed.
> Fix code snippet scroll bar

- apps/nerves_hub_www/assets/js/dates.js
- apps/nerves_hub_www/assets/js/dates.test.js
Why
---
* Whitespace around "never" value causes formatting to fail.
How
---
* Trim value before inspecting.
> Fix last connection whitespace

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
I think we should have a larger discussion on how we want to sort, search, and paginate tables on the front end, but in the meantime, it makes sense to at least sort the devices by the identifier ascending.
> Sort devices identifier ascending by default

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
This was noticed while doing https://github.com/nerves-hub/nerves_hub_web/issues/344 It normalizes the device delete response to be the same as others. It doesn't seem like we need to send the record back if its been successfully deleted.
> Update device delete response to omit the device record

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/ca_certificate_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/ca_certificate_controller_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/ca_certificate.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20190203000524_add_description_to_ca_certificates.exs
This adds `description` to the `CACertificate` model
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/349
> Add description to ca_certificates

- .circleci/config.yml
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/device_view.ex
- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/plugs/device_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware_metadata.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20190209173245_add_device_firmware_metadata_remove_last_link.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/channels/devices_channel_test.exs
- test/support/fixtures.ex
As detailed in https://github.com/nerves-hub/nerves_hub_web/issues/320 our desired functionality is to use the firmware version number supplied with the device connection parameters to determine deployment eligibility. After making that change, it made sense to _always_ use the metadata supplied by the device on the server side. This PR removes the linked `last_know_firmware_id` and adds an embedded schema `firmware_metadata` to the device model.
To get this to fully work, the client will need to be updated to pass the extra metadata for both PhoenixChannel and HTTP requests. The code is structured to allow the current client to remain functional. If _only_ the firmware uuid is provided (the current client), the firmware_metadata will be constructed by first looking up the firmware by …
> Embed firmware_metadata into Device

- apps/nerves_hub_web_core/priv/repo/migrations/20190209173245_add_device_firmware_metadata_remove_last_link.exs
We need to wait on removing the last known firmware id from the record until we migrate the data in the database. We need to pre populate all the device records in the database with the firmware_metadata from the last firmware record before the last firmware is garbage collected.
> Do not remove last_known_firmware_id until data has been migrated.

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
This PR fixes a few edges that were seen in the production logs.
When looking up the firmware in the db, `get_by_firmware_uuid` was expecting there to only be one result. This updates it to more then 1
> Multiple firmware

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/user_socket.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/device_channel_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_www/docs/client-server.md
This transitions devices from connecting to the topic `firmware:#{firmware.uuid}` to `device`. The existing `firmware:*` are internally routed to the `device` join logic.
> Connect devices to device topic

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/transfer/s3_ingress.ex
Ignore constraint errors for trying to insert the same record. This fixes an issue where the cluster might be in the middle of an update and a log file is processed, but not removed from the log bucket. If it fails to insert, allow it to succeed in removing the log file.
> S3 firmware transfer ingress fixes

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_certificate_controller_test.exs
- apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex
- apps/nerves_hub_device/test/nerves_hub_device/ssl_test.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_device/test/support/data_case.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
This PR updates the logic which queries the database for existing trusted device certificates to match on serial, authority key id, and validity. This fixes a case where a signer or multiple signers would create certificates with the same certificate serial number.
> Force device certificates to match on serial, aki, and validity

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex
This updates the Web interface to prevent `user` type orgs from changing their name. This also removes the ability for a user to be invited to administrate another user's default org. 
In the future, users will be given roles on individual projects.
> Prevent user orgs from changing name or inviting users

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.eex
Why:
* There's a lot of room for improvement
* https://github.com/nerves-hub/nerves_hub_web/issues/381
* Add the `uuid` to the firmware info on the devices table.
* Change the device identifier in the devices table to a link to the
show page for that device.
* Also added info do the device show page
> Show more/better device info on the frontend

- mix.lock
From the tzdata release notes
```
- tz release 2019a causing update errors due to typo in tz data. Fixed by reading version differently.
```
This will unblock releases
> Update tzdata to fix issue with 2019a

- README.md
Looks like local development expects to connect to `nerves-hub.org:4000`. When its not mapped,the logs explode with errors. I _believe_ it is required for dev cert setup, but correct me if Im wrong. Adding a note in here to help others
> add note in README.md about nerves-hub.org

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_www/lib/nerves_hub_www/accounts/email.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/org_user_created.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/invite.html.eex
- apps/nerves_hub_www/test/nerves_hub_www/accounts/email_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/317
This will now attempt a user lookup when you try to invite a user to an org.
* If user exists, adds user to the org and sends an email to user to notify
* If user does not exist, functions the same as before (sending an invitation)
* If user exists _and_ already belongs to the org, reports back to org#edit that the user is already a member
> fix invitations to support existing users

- apps/nerves_hub_www/config/prod.exs
This will move the value of this variable from being set at compile time to being set from the container runtime. It will pull it from AWS Parameter Store.
> Configure LiveView signing salt from prod runtime container environment

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/edit.html.leex
Last part of https://github.com/nerves-hub/nerves_hub_web/issues/379
Forgot to add a note when editing/adding tags to specify they are comma delimited, so adding here.
> Note tags are comma delimited in edit.leex

- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/js/dates.js
- apps/nerves_hub_www/assets/js/dates.test.js
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account_certificate/index.html.eex
* Adjusts `account_certificates#index` html to display more info about certs
* adjusts date.js to fix displaying dates in Safari
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/389
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/347
> Display more info for Account Certificates

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/audit_log.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/types.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20190403164436_create_audit_logs.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/types_test.exs
Initial structure to start saving audit logs (no implementation). Heavily inspired by [Hexpm audit log](https://github.com/hexpm/hexpm/blob/master/lib/hexpm/accounts/audit_log.ex)
* adds `NervesHubWebCore.Accounts.AuditLog` schema
* adds `NervesHubWebCore.Types.Resource` to handle the resource type of AuditLog
* migration to create table and fields for AuditLog
Few things to note:
* The `resource_type` is stored in the DB as a string, but when loaded it represented as an atom of an existing module. I went back and forth on whether to just have it as a string when loaded in the structs and changesets so if you have an opinion, speak up. My guess is we might want to do more with the atom, but maybe not? It'd also be a really easy change later on without affecting the DB
* `resource_type` is …
> Add structure for Audit Logs

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/nerves_key_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_footer.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/nerves_key_controller_test.exs
This adds support for the https://nerves-hub.org/nerves_key address for
users wanting to find out more about the NervesKey. Currently it
redirects to the GitHub location.
> Add redirect for NervesKey info

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
The authentication code previously downcased email addresses. Since the
email address downcase was only done in one place, this location was
inconsistent and it caused authentication failures.
This addresses https://github.com/nerves-hub/nerves_hub_cli/issues/113
and #423. The latter issue talks about normalizing email addresses
throughout but mentions edge cases in the RFCs that appear to make this
non-trivial. This change punts on normalization. If the user wants a
capital letter or something else odd, but legal, in their email address,
they can have it.
> Support email addresses with capital letters

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/channels/devices_channel_test.exs
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/365
This assumes that a device socket being terminated is a "last connection"
and piggy backs on that field. So looking at the status of `offline`, you
would assume the `last_connection` time being displayed is when it disconnected.
I debated adding a new field for this so open to that if others would rather that be implemented.
> Record time on device disconnect

- apps/nerves_hub_www/lib/nerves_hub_www/accounts/email.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/forgot_password.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/invite.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/org_user_created.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/email_view.ex
- apps/nerves_hub_www/test/nerves_hub_www/accounts/email_test.exs
Fixes #404
Subject contains "[NervesHub]"
Common closing.
> Standardize emails

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
I missed a group_by. This PR adds it back.  
This was causing the org list to show up with an entry for every product under the role.
> Make org list unique

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/role_validate_helpers.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/role_validate_helpers_test.exs
This PR allows a user with an equal or higher `OrgUser` role to have implicit permission when a `ProductUser` role is required. For example. Viewing a product requires a `product: :read` role but users with an `org: :read` role or higher such as [`:admin, :delete, :write`] will also work.
> Check for equal or higher Org role before Product role

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/products/products_test.exs
Viewing products require a `product: :read` role. This alters the logic to first check if the user has a comparable `org: :read` role for the organization. If so, they should be able to see all products in the org.
Fixes https://github.com/nerves-hub/nerves_hub_web/issues/390
> Return products for orgs where a user has a comparable org role

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/org_user_controller.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
This fixes up a couple things that were found when designing the CLI around the OrgUser API.
* Removing a user from an org that was `type: :user` resulted in an error. This updates the code to prevent a user from being removed from their own user org.
* Return a not found error when trying to remove a user from an org who is not an OrgUser
> OrgUser fixes

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account_certificate/index.html.eex
User of button causes an internal server error. See issue #437 for 
making user cert creation work.
> Remove the create user certificate button

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_certificate_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_certificate_controller_test.exs
Issue #348 
Device (CA) certificates are displayed on their own page. The page can be reached from the Organization Settings page via the button "Device (CA) Certificates.
No adding or deleting of these certificates are available from this page
Unit test added (only :index)
> Display Device (CA) Certificates

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_user_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_user/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_user_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_user_controller_test.exs
Issue: #427
From the Organizations Setttings page select the "Users" button. A list 
of the organization's users is shown on a separate page.
One unit test added.
> Display organization's users in web interface

- .circleci/config.yml
- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_device/rel/Dockerfile.build
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/audit_log_view.ex
- apps/nerves_hub_www/rel/Dockerfile.build
This updates the runtime container to 3.9 to match the build containers. Tested by executing the migration from the last failed deployment successfully. This also cleans up compiler warnings.
> Fix elixir 1.8.1 deployment

- apps/nerves_hub_www/lib/nerves_hub_www_web.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/deployment_live_show_test.exs
Basically the same as #444 
* Changes `deployment#show` page to use LiveView
* Adds audit log feed in view
* audits toggling deployment active/inactive
* audits deleting the deployment
> Add audit log feed to deployment#show

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/gc.ex
Fixes an issue where the database record would be cleaned up but the files would not be deleted.
> Use Firmwares.delete_firmware/1 when garbage collecting

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device.ex
- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex
resolves #416 
* Changes `devices#index` to use LiveView
* Adds sorting by clicking on the column header
* Support changing sort direction by clicking the same column
header to toggle between asc and desc
* Changes `status` to use LiveView from `presence_diff` events
* adds `status` virtual field to `NervesHubWebCore.Devices.Device` schema
As a bonus, if the view is sorted by `status`, devices changing statuses will live sort as the view gets the change (that is the last part of the gif)
> Add sorting to devices#index

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/upload/file.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
This just fixes a simple edge case of attempting to delete a firmware file stored locally
that doesn't exist anymore. Really, this only affects running NervesHub locally (or anyone
else who might use this file store instead of S3). In the case of local development, fw
files are stored in tmp locations so a restart could blow it away while the record exists
in the app. Then attempting to delete the record would fail. This just checks if it is there
first before attempting to hard delete
> fix delete_file/1 in Upload.File

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/org_user_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/org_user_controller_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www/accounts/email.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/tell_org_user_added.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/tell_org_user_removed.html.eex
- apps/nerves_hub_www/test/nerves_hub_www/accounts/email_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/account_controller_test.exs
Issue #403 
When a user is added or removed from an organization, either by an API call or (in the future) via the the web UI, an email is sent to all other users in that organization notifying them of this action. The subject line includes the username of the initiator of the action.
Unit tests added.
> Email all on add remove user

- apps/nerves_hub_api/lib/nerves_hub_api_web/views/device_view.ex
Return a device's firmware metadata on an API request.
This change is necessary to support https://github.com/nerves-hub/nerves_hub_cli/issues/102
> Return device firmware metadata

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
In anticipation of web UI registration, this fixes a bug whereby an 
email is *not* sent to an organization's users; the only user is the one 
just registered.
This bug was introduced with the PR for Issue #403 because of not understanding the difference between "create account" and accepting an invitiation.
> Do not send email on create account

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_show_test.exs
Requires https://github.com/nerves-hub/nerves_hub/pull/97
Displays a fwup progress based on messages from `nerves_hub` while the device is updating.
Shows progress in `device#show` and `device#index` views.
A good visual check that your deployment is doing what you want and devices are reacting
> Add fwup progress when device is updating

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
I forgot to change the `devices#index` to use `Map.put` to update the device with `:fwup_progress` instead of using the update syntax `%{ | }`. So there are a few cases where this would error out if the device has not gotten a fwup message or anything.
(the other route would be to add these as virtual fields on the device, but was opting for this simple change to keep device schema cleaner for now)
> Fix device#index fwup progress

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
Some messaages from remote iex session come in with an escape of `\e[22m` and it would
break the rendering. This parameter is [`Normal color or intensity`](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters) so I think just ignoring it and defaulting to the HTML coloring is fine.
Also resolves [this rollbar error](https://rollbar.com/nerves-hub/nerves_hub_www/items/1)
> Allow ANSI \e[22m in console output

- apps/nerves_hub_www/assets/css/_console.scss
- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/console.html.leex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_console_test.exs
- mix.lock
Supports a few more ANSI codes in the remote iex console that were causing crashes (via https://github.com/stephlow/ansi_to_html/pull/2/commits/7aa02d8c425e92d876616073e26af591c189ef76). That change also handles unknown ANSI a little more gracefully so things don't just 💥 
Also updates the console view a bit to make the input field larger and blend in to the "console" background.
The indentation of the command line and some responses are still a little wack...one can only handle so much CSS in one day 😑
> Support more ANSI in remote console

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/controllers/device_controller.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments/deployment.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20180903215312_unique_deployment_name_product_id.exs
- apps/nerves_hub_web_core/priv/repo/migrations/20190429171105_add_rate_and_thresholds_to_deployments.exs
- apps/nerves_hub_web_core/priv/repo/migrations/20190429173128_add_needs_attention_to_devices.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
First attempt at https://github.com/nerves-hub/nerves_hub_web/issues/418 and https://github.com/nerves-hub/nerves_hub_web/issues/419
* Adds new fields to `Deployment` schema
* :device_failure_threshold
* :device_failure_rate_seconds
* :device_failure_rate_amount
* :failure_threshold
* :failure_rate_seconds
* :failure_rate_amount
* :healthy
* Adds `healthy` bool to `Device` schema
The new `deployment` fields are to calculate a failure rate and failure threshold at both device and deployment levels.
The `failure rate` == X number of device update failures within Y seconds
The `failure threshold` is total number of devices in a `healthy == false` state that are permitted. Devices get in a `healthy == false` state when they attempt to update from the same deployment and exceed the …
> Mark deployments and devices that need attention

- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/yarn.lock
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/deployment_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
~~This is branched off of #455 that I forgot to put in, but that PR was already big enough so I decided to keep it separate.~~
~~Until #455 is merged, you'll want to just look at [this diff](https://github.com/nerves-hub/nerves_hub_web/compare/deployment_protections...deployment_health_views) for changes~~
Rebased 🎉 ☝️ 
Update deployment views
* Updates `deployment#show` to display failure rates and thresholds
* Updates `deployment#edit` to allow changing failure rates and thresholds
* adds help icons with tooltips about failure rates and thresholds
> Deployment health views

- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_www/Dockerfile
- apps/nerves_hub_www/rel/Dockerfile.build
This is needed to build prod containers. I guess there is an issue with pulling previous version from the community apk repo.
> Update fwup to 1.3.1

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/audit_logs/audit_log.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex
- apps/nerves_hub_web_core/priv/repo/add_audit_log_descriptions.exs
- apps/nerves_hub_web_core/priv/repo/migrations/20190520202940_add_description_to_audit_logs.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/audit_logs/audit_log_test.exs
- apps/nerves_hub_www/assets/css/_audit_log_feed.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/audit_log/_audit_log_feed.html.eex
Changes the audit log feed to use a more easily understandable phrase about what event occurred
that was audited instead of icons with a click-to-expand behavior. This description is generated
when creating the audit log and stored in the record.
Also changes it to look more like a feed (i guess?)
Includes a script in `apps/nerves_hub_web_core/priv/repo/migrations/20190520202940_add_description_to_audit_logs.exs` to be run after the new field is added via migration.
> Use human friendly descriptions for audit logs

- README.md
Taken from the nerves training PDF.  The documentation refers to `asdf` so I thought it might be useful to link in the instructions to getting that up and running.
> Add instructions on installing asdf

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_console_test.exs
A recent change in https://github.com/nerves-hub/nerves_hub/pull/102 added support to handle
io_requests requiring a function to be run to format the data. In some cases, that ends up
being a list of characters or numbers (representing a character) that would break the console
session because to regex is used to generate the ANSI HTML and it couldn't handle the list.
So this just calls ~~`to_string/1`~~ `IO.iodata_to_binary/1` on data that comes in from the device before attempting to convert
to HTML and display.
> Support remote iex lines that are lists

- apps/nerves_hub_www/assets/css/_console.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
I don't know what I'm doing, but this condenses lines closer to better match output
you would see in the terminal. Should make things a little easier to read for now
**Before**
**After**
> Adjust line spacing for IEx console

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/channels/devices_channel_test.exs
We recently changed update message audits to inject the firmware uuid in it. However,
on a broadcast we were not sending the full deployment struct and so we could not lookup
the firmware (or ensure it was there) to perform the audit. So, this just changes a few
things to send that full struct to the channel, but remove it before sending to the device.
The channel will also do a lazy lookup to search based on deployment id if for some reason
the deployment struct is not in the broadcast payload. Also add a couple regression tests so
this should be backwards compatible (though I didn't find anyone actually using other keys
in the payload besides `firmware_url`)
Resolves [this Rollbar error](https://rollbar.com/nerves-hub/nerves_hub_device/items/2/)
> Fix audit! failures on broadcast

- .circleci/config.yml
The various repository renames in the past ended up confusing Coveralls.
This fixes it but sadly loses coverage history.
> Fix Coveralls token

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
I guess I can't spell :man_facepalming:
So, this spells `deployment` key correct in the broadcast message to update a device. Also adds
a test in to make sure it gets broadcasted as expected.
> Fix error broadcasting update message

- apps/nerves_hub_web_core/config/config.exs
Firmware uploads are failing because ExAws needs to be told what JSON codec to use for request/response
> Set ex_aws json_codec to use Jason

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/new.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/show.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
Attempting to delete a device from the UI would error because LiveView handles CSRF token a little different and it would not match the token expected for `device#delete` endpoint in the device controller.
So this adjusts that to handle the LiveView session for DeviceLive.Index a little differently by going back to the original idea of forwarding from the controller and passing the needed csrf token.
This can probably be adjusted if needed once https://github.com/phoenixframework/phoenix_live_view/issues/111 is resolved.
> Fix deleting device from UI

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/dashboard_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/session_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/dashboard/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/new.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/dashboard_view.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/dashboard_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs
This PR removes the dashboard page and changes the initial page to the product index. The jumbotron from the dashboard will display on the product index if there are no products. Once a product is created, the index shows the product list and you are no longer presented with the "lets get started by creating a new product" screen.
> Remove dashboard and default to product index

- apps/nerves_hub_web_core/config/prod.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org_metric.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware_transfer.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20190618162113_add_org_metrics.exs
- apps/nerves_hub_web_core/priv/repo/migrations/20190618200916_remove_firmware_transfer_unique_index.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
This PR creates a new model `OrgMetric` which is to be used for storing usage metrics. The model tracks the following information:
* `devices`: total number of device records
* `bytes_transferred`: Total number of bytes transferred deploying firmware
* `bytes_stored`: Total number of bytes storing firmware on S3
A record is created for each org, each day. The intention for surfacing this data is to render current / previous usage numbers to the user and for billing.
> Add daily org metrics

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/transfer/s3_ingress.ex
This return type was removed in https://github.com/nerves-hub/nerves_hub_web/pull/495
> Clean up S3 ingress firmware transfer return case

- apps/nerves_hub_www/assets/css/_navigation.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
depends on https://github.com/nerves-hub/nerves_hub_web/pull/499
This PR restyles the navigation bar. 
The dropdown on the left lets you switch between organizations and projects. 
The dropdown on the right has the org and account settings.
> Navigation update

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/transfer/s3_ingress.ex
I am trying to debug issues with digesting the server access logs. There doesn't seem to be anything in the error logs that is useful, so I am adding this additional logger error to see if we are throwing away unmatched messages and why.
> Add more logging to Firmware Transfer ingress

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
Scopes `device` controller actions to validate the product role instead of the org
> Scope device controller actions to product role

- apps/nerves_hub_web_core/config/prod.exs
I need to debug what is happening with the firmware transfer server access log records. It doesn't appear like they are being created. Disabling them for now so they are not deleted from the server.
> Disable FT transfer ingress to debug server access logs

- crowdin.yml
The advice from Crowdin is to use locale_with_underscore and manually
put in the exceptions for locales that should just be two letters. This
helps prevent accidents where adding a locale stomps on an existing one.
[skip ci]
> crowdin: switch to locale_with_underscore

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/edit.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/deployment_live_show_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_console_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_edit_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/live/device_live_show_test.exs
When we change anything about the session structure of a LiveView, it causes tons of rollbar errors after deployment because any existing browser tabs/windows are trying to reuse the old session structure which no longer has a matching `mount/2` clause for it.
So, this adds a catch-all to redirect to the home path if that apps.
> Add catch-all for LiveView mounts

- apps/nerves_hub_web_core/config/prod.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/transfer/s3_ingress.ex
The module was compiling in application env values that were coming from the target container runtime and were not available at build time. This moves those to runtime checks.
> Fix FirmwareTransfer ingress

- apps/nerves_hub_device/lib/nerves_hub_device/presence.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
https://github.com/nerves-hub/nerves_hub/pull/109 adds ability for the device to assert more about what's happening on it and set a status. Since its already storing for itself, I thought it might be nice to send it here for the web to display also.
> Add status_update to device channel 

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
This PR fixes an error when attempting to update a stale device record. It will occur if a device connects, a modification is made to the device record while it's connected, and then the device disconnects. This modifies the logic to check to ensure the device record still exists, and refetches it to ensure that it is not stale.
> Fix device last communication stale update

- apps/nerves_hub_api/mix.exs
- apps/nerves_hub_device/mix.exs
- apps/nerves_hub_web_core/mix.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/console.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/edit.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/mix.exs
- mix.exs
If a product, device, or any other database record that a live view required to mount is deleted, and a page remains open, live view will raise and continue to attempt to mount. This will redirect any exceptions back to the home.
> Handle live view mount exceptions

- apps/nerves_hub_web_core/config/prod.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org_metric.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20190724020853_alter_org_metric.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
This PR does two things.
First: 
It removes the `bytes_transferred` from the `org_metric` records. This is being removed because it was unreliable. Firmware transfer records are delayed in their delivery and some would be missed in this setup. The purpose of these records is for understanding the counts of storage and devices on a daily basis to be used in billing calculations.
Second:
This increases the field size for `bytes_stored` to fix the following error
```
Task terminating (DBConnection.EncodeError): Postgrex expected an integer in -2147483648..2147483647, got 4820089941. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly
```
> OrgMetric remove bytes_transferred and change bytes_stored to bigint

- apps/nerves_hub_www/lib/nerves_hub_www_web/endpoint.ex
- config/dev.exs
This allows using the file store as an alternative to S3 on platforms that are not on AWS.
> Toggle file upload endpoint using config.

- apps/nerves_hub_www/assets/css/_footer.scss
- apps/nerves_hub_www/assets/css/_sidebar.scss
- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/assets/package.json
- apps/nerves_hub_www/assets/yarn.lock.old
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/home/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_footer.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_sidebar.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
This is a PR of various tweaks to the UI. There were a couple annoyances that I fixed.
* The drop down menu for device actions was behind the footer
* The footer was fixed to the bottom of the viewport making the UI feel boxed in, the footer will now default to being scrolled off the page.
* The header was set to sticky instead of fixed which means that on long scrolling pages it would move out of view.
* The footer links for docs were rendering incorrectly.
* some of the helper icons were incorrect. For example, the edit button on the device index was a page download icon instead of a pencil.
> UI Updates

- .circleci/config.yml
- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_www/Dockerfile
- apps/nerves_hub_www/rel/Dockerfile.build
fixes build errors when trying to pull an older version of fwup from apk
> fwup: bump to v1.3.2

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_device/test/support/conn_case.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/audit_logs/audit_log.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments/deployment.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device_certificate.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware.ex
- apps/nerves_hub_web_core/priv/repo/add_org_id.exs
- apps/nerves_hub_web_core/priv/repo/migrations/20191002190115_add_org_id_to_models.exs
- apps/nerves_hub_web_core/priv/repo/seeds.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/endpoint.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
- test/support/fixtures.ex
This PR adds org_id to firmwares, device_certificates, deployments, and audit_logs. This reference is being added so it is easy to get to when creating audit logs on resources of these types.
> Add org_id to Firmware, Deployment, DeviceCertificate, AuditLog

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/audit_logs/audit_log.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
Add an audit log record when a device successfully connects to NervesHub
> Add device connect audit logs.

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
Fixes #472 
I noticed this issue as well today. Turns out the conn.assigns does not hold the user info at this point, so it was raising. The username is readily available from the params though so it was an easy fix. i didnt have time to research when this might have started happening (or find the commit.) But I suspect if you have Honeybadger or Rollbar, etc hooked up it would be easier to track down by looking for when the `(KeyError) key :user not found in: %{}` errors started coming in.
> 500 on invite

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/email.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/account_controller.ex
So turns out https://github.com/nerves-hub/nerves_hub_web/pull/574 had a little more complications. The fix was actually using the new user as the instigator of the invite, but that's not always the situation.
So this shims things a bit to fix the tests and put us back in a good state. We should circle back and decide if we care to have the user add instigator in the email to everyone. And if so, how to better handle it
> Only show instigator when available

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/firmware_controller.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/firmware_controller_test.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/firmware_controller_test.exs
Closes #458 
Adds an error flash message when trying to delete a firmware that has associated deployments.
> Issue #458: Add error handling when deleting firmware with associated deployments

- apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex
- apps/nerves_hub_device/test/nerves_hub_device/ssl_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- test/support/fixtures.ex
This fixes the SSL verify_fun to support allowing certificates from devices with expired ca's. The CA cert needs to remain in the database even after it has expired for this to work.
> Fix connections for devices with trusted certificates

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/deployment_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
- apps/nerves_hub_www/test/nerves_hub_www_web/live/deployment_live_show_test.exs
Phoenix live view was updated and the behavior of `phx-value` changed to `phx-value-<var>`. This updates the show page on deployments to fix the activate / deactivate button.
> Fix live view deployment activate button

- apps/nerves_hub_device/lib/nerves_hub_device_web/endpoint.ex
Based on the [`Phoenix.Socket` docs](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket.ex#L92-L95), I assumed all websocket messages used the `Phoenix.Socket.V2.JSONSerializer`. But from some recent experiements have learned
this is not the case and the statement in the docs refers to the `phoenix.js` socket lib setting `vsn=2.0.0` for you in the connect params.
We've recently documented the websocket API which conforms to this V2 structure, so this just sets that in place to force all messages to use V2.JSONSerializer without the extra requirement of setting `vsn=2.0.0` in the connect params and removes the need to document both versions.
> Hard set device websocket messages to use V2 serializer

- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/deployments/deployments_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
When sending an update to a device, pass all firmware metadata. This information is useful to present when determining if the client should choose to apply the update.
> Send firmware metadata to device in update message

- apps/nerves_hub_web_core/priv/repo/migrations/20200425222430_add_metadata_index_to_audit_logs.exs
There are some log running queries that take place on the audit logs table from using jsonb values in the where part. I think this could help them along.
> Add an index to audit_logs params->firmware_uuid

- apps/nerves_hub_web_core/priv/repo/migrations/20200426190158_update_metadata_index_to_compound_index.exs
- config/prod.exs
I tested this on staging, the compound index cuts the response time of the query in half. I've also scaled up the database cluster so this will also increase the number of connections from 10 to 20 per node.
> Compound params

- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/org_user_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/product_user_controller_test.exs
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/deployment_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/session_controller_test.exs
It seems the nerves_hub cli cannot deal with spaces, so I added a bit of validation for that. It's way more restricting than just spaces though `~r/^[A-Za-z0-9-_]+$`. If that's to restricted feel free to adjust the regex.
> Restrict organization names

- apps/nerves_hub_www/assets/js/console.js
This will refresh the line to make it appear on the page rather than have a blank black console screen
> Send CTL-L when loading the console page

- apps/nerves_hub_web_core/priv/repo/seeds.exs
The fixtures fail because `Nerves Team` is an invalid Organization name.
Fixes:
```
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{name: "Nerves Team"}, errors: [name: {"has invalid format", [validation: :format]}], data: #NervesHubWebCore.Accounts.Org<>, valid?: false>}
(nerves_hub_api 0.1.0) /Users/acrogenesis/Development/valiot/nerves_hub_web/test/support/fixtures.ex:104: NervesHubWebCore.Fixtures.org_fixture/2
apps/nerves_hub_web_core/priv/repo/seeds.exs:56: NervesHubWebCore.SeedHelpers.nerves_team_seed/1
(elixir 1.10.4) lib/code.ex:926: Code.require_file/2
(mix 1.10.4) lib/mix/tasks/run.ex:145: Mix.Tasks.Run.run/5
(mix 1.10.4) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
(mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3 …
```
> Fix fixtures, NervesTeam org name

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/device_certificate_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/plugs/device.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/router.ex
- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_certificate_controller_test.exs
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_www/rel/Dockerfile.build
- test/support/fixtures.ex
When using pre-signed crypto auth chips such as the ATECC608A-TNGTLS, trusted device certificates are often provided from the supplier. These need to be uploaded to the server to allow them to connect and authenticate.
This adds the following endpoints to the API:
/org/product/device/certificate/create
/org/product/device/certificate/show
/org/product/device/certificate/delete
> Add support for uploading trusted device certs

- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/user_controller_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/user.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/user_test.exs
I tried to sign up as `brian.berlin` and I got a 500 error. My fix applies the same validation on orgs name that is being done to the users username. I wonder though if there are usernames in other production environments that will end up having trouble editing their account. I guess that depends on how long the bug has been around.
Other options might be to remove characters not allowed by the org name from the username before saving. Or maybe use the orgs name validation on users username.
> Fixes ISE when the default org name is invalid

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/email.ex
- config/config.exs
Why:
* Private/Custom instances may need a custom from email that is validatable
* Getting from_email from env vars
* Provide a default value if not from_email is set
> Make from_email customizable

- apps/nerves_hub_api/config/release.exs
- apps/nerves_hub_device/config/release.exs
- apps/nerves_hub_www/config/release.exs
@mobileoverlord it turns out we did need to configuration in the release.exs files because, as you described, the config.exs is already compiled when the env variables are injected into the docker build process. I left config.exs file as is, since it is still useful for regular development.
> Add from email to release config

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_certificate_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/new.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_certificate_controller_test.exs
- test/support/fixtures.ex
Why:
* Users may want to create/delete CAs from the UI
* Adding actions to the router for WWW
* Adding an action for a new screen
* Adding actions for creating/delete CAs
* Add some helpers to fixtures to easily access CA files.
* Adding tests
> Add CA Create/Delete actions

- apps/nerves_hub_www/test/nerves_hub_www_web/views/layout_view_test.exs
Fixes broken test:
```
1) test org_device_limit/1 a string representation of total devices and device limit is returned (NervesHubWWWWeb.LayoutViewTest)
apps/nerves_hub_www/test/nerves_hub_www_web/views/layout_view_test.exs:30
** (Mox.UnexpectedCallError) no expectation defined for NervesHubWebCore.PatcherMock.patchable?/1 in process #PID<0.2035.0> with args ["/var/folders/nx/_3hhhmld02jd5ft2_4p4h55m0000gn/T/signed-1551.fw"]
code: %{org: org, device: _} = Fixtures.standard_fixture()
stacktrace:
(mox 0.5.2) lib/mox.ex:693: Mox.__dispatch__/4
(nerves_hub_web_core 0.1.0) lib/nerves_hub_web_core/firmwares.ex:439: NervesHubWebCore.Firmwares.build_firmware_params/3
(nerves_hub_web_core 0.1.0) lib/nerves_hub_web_core/firmwares.ex:109: anonymous fn/4 in …
```
> Fix layout_view_tests due to missing mocks

- apps/nerves_hub_www/assets/css/_navigation.scss
New UI asserts capitalization on orgs and products in the navigation menu. However, if I name my org lowercased with other characters, I'd like to see that in the nav as well instead of having my names reformatted for me in views.
Super nit - what do you think?
/cc @Mrjaco12 @coryjewell
> Don't capitalize org and product in navigation

- apps/nerves_hub_www/assets/css/_layout.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_user_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/plugs/org_user.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/select-firmware.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org/invite.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_user/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_user/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_user_view.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_user_controller_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/plugs/org_user_test.exs
- apps/nerves_hub_www/test/nerves_hub_www_web/views/org_user_view_test.exs
Why:
* Admins may need to remove users or change user roles
* Added an edit template
* Added actions/routes for edit, update, delete
* Add a view helper to get role options
* Only show action menu for users that aren't the current user
* Add tests for each action and the new OrgUserView function
> Org User management

- apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/deployment_controller.ex
- apps/nerves_hub_api/lib/nerves_hub_api_web/views/deployment_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/deployment_controller_test.exs
Part of https://github.com/nerves-hub/nerves_hub_web/issues/641
From discussion in #639 
Deployments now display a `state` value of `on/off` string in the UI. This adds that to the API response and allows updating a deployment state as well so that changes can also be reflected in the CLI
> Allow deployment state in API requests/response

- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_device/rel/Dockerfile.build
- apps/nerves_hub_web_core/mix.exs
- apps/nerves_hub_www/rel/Dockerfile.build
What:
* Delta updates were failing for a number or reasons:
1. The `inets` application wasn't available
2. The `xdelta3` executable wasn't available
How:
* Add `inets` to extra_applications
* Make sure delta update executables are installed so they'll be accessible
> Fix delta updates failing

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- Icon for connection status on device show page is not updating when a device is connected
- If statement was looking for wrong term -- updated to check for "online" rather than "connected"
> Device connection icon looking for wrong word

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
- apps/nerves_hub_web_core/test/test_helper.exs
Addresses https://github.com/nerves-hub/nerves_hub_web/issues/665 by temporarily disabled delta updates to prevent timeouts and failing updates until a better solution can be developed.
cc/ @Mrjaco12
> Temporarily disable delta updates

- apps/nerves_hub_api/rel/Dockerfile.build
- apps/nerves_hub_device/rel/Dockerfile.build
- apps/nerves_hub_www/rel/Dockerfile.build
This should fix issues with deploying to production. I tested it in staging. The www container failed, but it was due to the health check grace period being set to a number that was much lower than it is set to for the production cluster. I updated those values and it seems to be running fine on staging.
> Bump runtime to alpine 3.12.0

- apps/nerves_hub_api/lib/nerves_hub_api_web/views/ca_certificate_view.ex
- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/ca_certificate_controller_test.exs
connects to #660 
connects to nerves-hub/nerves_hub_user_api#22 
Seems like this was in place already just not a part of the response. 🤷‍♂️
> Adds description to ca_certificate.json render function

- apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
The current code assumes that all ca certificates are root certificates by searching for one who has the same authority and subject identifier (a self signed root cert) This behavior is wrong and prevents intermediates from being used for signing. Updating the lookup to find the ca by ski will allow for both self signed and intermediates to be used.
> Find CA by ski and not aki

- apps/nerves_hub_www/assets/css/_home.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/app.html.eex
- Alerts were overlapping with content on the homepage
- Updated styles for alerts specifically on the homepage. They will now always display properly at the top and not overlap content.
> Fix alert layout on homepage

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/audit_log/_audit_log_feed.html.eex
closes #680 
Appends timestamp to the audit log to determine the exact time an event occurred
> Append timestamp to audit_log help-text message

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex
Why:
* We were not applying presence statuses to new devices from DB
* Fixes #670 
* Apply statuses from presence after a presence_diff event and devices are fetched
> Fix device index status reset bug

- apps/nerves_hub_www/assets/css/_console.scss
- apps/nerves_hub_www/assets/css/app.scss
- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/js/console.js
- apps/nerves_hub_www/assets/webpack.config.js
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/console.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/console.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/user_console_channel.ex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
Based on some discussion from slack.
Resolves #689
Resolves #696
Resolves #654
* `console` button now opens console to a new window or tab
* console is the full window with minimal details at the top
* console is resizable
* device status _should_ update with presence changes...I'm not that good at javascript, so YMMV
> Restructure Console page

- apps/nerves_hub_api/lib/nerves_hub_api_web/views/product_view.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/delta_updater/default.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20201024000822_add_patchable_flag_to_products.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
- apps/nerves_hub_www/assets/css/_buttons.scss
- apps/nerves_hub_www/assets/css/_custom.scss
- apps/nerves_hub_www/assets/css/_form.scss
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/product/form.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/product_controller_test.exs
- test/support/fixtures.ex
This fixes #674 
Why:
* We want users to be able to configure patchability of firmware per product
* Add a patchable flag in the DB
* Update the router to allow updating products
* Update the product form to use the correct endpoint
* Update product form with new fields
* Update CSS for patchable field
* Add a new condition to the fetch_firmware_url function for patchable product
* Add tests to ensure that patches are created for patchable products
* Add test for updating product
Note: The `get_firmware_url` function is getting a bit wild with parameters. If anyone has ideas about how to reorganize this to make check the check a little nicer, would be appreciated.
> Make products patchable

- apps/nerves_hub_www/lib/nerves_hub_www_web/views/deployment_view.ex
Fixes #668
Adds the firmware UUID with the displayed version when in a dropdown list or in the Deployment #show page
> Show UUID with firmware version

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/new.html.eex
Resolves #652
* Removes the `all` tag from being added by default to new devices from web UI
* Adds ability to add tags when creating device from web UI
> Remove "all" tag and allow tags on device create

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/show.html.eex
Resolves #707
Also changes the `Created on` titles to `Uploaded on` to more accurately represent what that time means (It is using the firmware records `inserted_at` field). I'm wondering if that's even correct?
> Show platform in Firmware index and show page

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/templates/email/forgot_password.html.eex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/templates/email/invite.html.eex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/templates/email/org_user_created.html.eex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/email_test.exs
When a user is created or requests a password change, the email says its an action on `nerves-hub.org`. However, if this is self hosted, that may not actually be the domain.
This changes to use the `EmailView.base_url()` instead when referencing where the email was generated which pulls from Application config variables that may have been customized in a self-hosted instance.
> Change domain shown in emails

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.leex
- Input for moving a device needs to be properly styled
- Went away from reusing the main navigation as a form input and instead am using a select organized with `optgroup`s
- This form still needs to be hooked up to perform the previous functionality (as discussed)
> Switch to select input for moving devices

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/upload/s3.ex
Firmware download URLs sent to devices are currently valid for 10
minutes. Devices that can restart downloads need the URL to be valid for
the duration of the download. This causes an issue for devices
downloading over slow cellular links that may not be able to complete
the firmware update for an hour or two.
This changes the URL valid time to be 24 hours. This should be more than
long enough for any device to download a firmware update and if it takes
a device longer than this, requiring some special case handling to fetch
a new URL seems reasonable. 
Lengthening the URL valid time only changes the signature, so this doesn't
have side effects like preventing an administrator from deleting a
firmware on NervesHub. Security-wise, the signed URL is sent over the
encrypted channel or HTTPS …
> Increase download URL valid time to 24 hours

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex
In some cases, DeviceCertificates are allowed to not have a Subject Key Identifier (ski) field. The previous implementation assumed this would always be present which breaks in these cases.
This fixes that to check for the field when exporting the CSV.
> Fix exporting devices CSV

- apps/nerves_hub_www/lib/nerves_hub_www_web/views/audit_log_view.ex
This removes the reference to the `:iex` application. The default IEx
inspect options should match the current use (80 char limit, etc.). If
nothing else, someone customizing their IEx options won't have an
unexpected effect on the audit log rendering.
> Remove unused audit_log_info/1 function

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_socket.ex
- apps/nerves_hub_device/lib/nerves_hub_device_web/endpoint.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/console_channel_test.exs
This seems to be a leftover from initial project generation a long time ago. Naming is hard.
> Rename nerves_hub_device_web UserSocket to DeviceSocket

- apps/nerves_hub_device/lib/nerves_hub_device_web/views/device_view.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/update_payload.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- test/support/fixtures.ex
this is a work around fix for an issue where the payload that gets sent to devices when an update is available is
different if the update happened on `join` or while a device is connected.
I don't believe this is a long term fix, but a work around. 
There are **two different** functions that calculate if a device should receive an update, the other being called `resolve_update` in the same module as is changed here. 
While trying to document and make sense of this payload on the [client side here](https://github.com/nerves-hub/nerves_hub_link_common/commit/db64d190f331184535c26eab253020cec24afb06#diff-3b8725c177a5e6ae0bf2f15149de38d16bf617b238617ecd7cfce5f94a503247) 
i only took that first function into account as i assumed that the other case would use the same function. I think …
> set `update_available: true` in when a deployment is updated

- apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/firmware_metadata.ex
This adds some specs and types for the payload that gets sent to the device when an update is available.
The `NervesHubWebCore.Firmwares.FirmwareMetadata.metadata` type isn't as specific as i wanted, but Dialyzer refuses to play ball. without listing the payload as `optional` which isn't actually true.
Would love a second look
> Add specs for functions involved in the firmware update payload

- .circleci/config.yml
Deployments frequently "fail" because CircleCI has an automatic 10 min timeout. However, the [`ecs-deploy` task sets a timeout for 12 minutes](https://github.com/nerves-hub/nerves_hub_web/blob/main/rel/scripts/ecs-deploy.sh#L21) which means our CI may fail before the deploy is actually done.
> Increase deploy timeout

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
This is mostly just a nuisance. This will create a failure on the server when attempting to create an audit log event for `update_available: false` and may send an unknown message to the device. However, in the situation where updates are available, everything works as expected.
> Only send update message if available

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/device_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/router.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/device_view.ex
The CLI can interact with device certificates, but the web has no
context. This adds ability to see what devices certificates are
associated and also supports downloading and deleting
> Support view, downloading, and deleting device certificates

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device_certificate.ex
Device signer CA provided by NervesHubCA are added to the DB and used when user does not supply their own Signer CA. Adding to the DB prevents someone else from claiming ownership.
Eventually be removed by https://github.com/nerves-hub/nerves_hub_web/issues/316
> Fix registrations using NervesHubCA provided signer cert

- apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex
- apps/nerves_hub_device/test/nerves_hub_device/ssl_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- docs/device_authentication.md
Right now if a device is deleted, it is a soft delete. When it
attempts to connect again, SSL verification will succeed but the
device will not show anywhere in the UI.
This instead fixes that to prevent authentication for devices that are
deleted and require the user to explicitly restore it.
> Ignore SSL auth when device has been soft deleted

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/ca_certificate.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/ca_certificate/jitp.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20210511162245_add_jitp_to_ca_certificates.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/org_certificate_controller.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/edit.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/new.html.eex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_certificate_controller_test.exs
There is a crucial fix in here that changes the JITP record migration to prevent deleting certificates when JITP profiles are deleted. see b66435c
The rest allows JITP CRUD actions on existing certificates. This will effectively grandfather in any existing CA certificates and allow them to be edited to use with JITP without the strict ownership check that was also introduced.
> Allow editing JITP for existing certificates

- apps/nerves_hub_api/test/nerves_hub_api_web/controllers/device_controller_test.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices/device.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/repo.ex
- apps/nerves_hub_web_core/priv/repo/migrations/20210603174111_require_device_uniqueness.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/show.ex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/device_controller_test.exs
099249f changes the uniqueness requirement for devices. Previously, a device identifier could be created in an org if that device was deleted. This causes lots of errors if it ever tries to connect again and leaves potential for lots of orphaned device records so we need to not exclude deleted devices in the index. Part of the migration will delete duplicate records before restoring the index.
The rest is to support being able to restore/destroy soft deleted device records in order to avoid unknown errors trying to recreate devices or connecting deleted ones
> Device uniqueness fixes

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/plugs/allow_uninvited_signups.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/plugs/allow_uninvited_signups_test.exs
- apps/nerves_hub_www/config/release.exs
- apps/nerves_hub_www/lib/nerves_hub_www_web/views/layout_view.ex
- config/config.exs
- config/prod.exs
- config/test.exs
The reason why this issue occurs is due to the fact that
the value of allow_signups is assigned in the init function of plug.
This is mentioned in [the Plug documentation](https://github.com/elixir-plug/plug/blob/fa579592ebf53306e3a4b13e2414a40997add1f7/lib/plug.ex#L22-L24).
> Note that init/1 may be called during compilation and as such
> it must not return pids, ports or values that are specific to the runtime.
> Fix allow_signups runtime config is not available

- README.md
I think a pointer to `nerves_hub_ca` repo is paramount. I remember when I started out with NervesHub I was head scratching because `nerves_hub_web` was running fine but when I tried to connect the device I'd get an error. It took a while to figure it out.
> Add information about nerves_hub_ca repo in README.md.

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/home/index.html.eex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_footer.html.eex
I've been receiving inquiries into how to pay for NervesHub and Very
hasn't worked on NervesHub for quite a while (at least in public). It
feels like it's time to make the website reflect the current state more
accurately.
> Remove references to a paid version of NervesHub

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
When finding a firmware delta, the source and target firmware ID's should be equal to `source_id` and `target_id`.
> Use equality comparison to find firmware deltas

- apps/nerves_hub_api/config/release.exs
- apps/nerves_hub_device/config/release.exs
- apps/nerves_hub_www/config/release.exs
This allows for NervesHub to be hosted outside of AWS such as Google Cloud
> Allow AWS host to be configured

- docs/deploying.md
Rest of deployment guide uses port 8443 for CA service while it was configured to use 443. Also, env vars were not used in config.
> Fix CA service's config in deployment guide

- apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/password_reset_controller.ex
Warning flash messages are not shown by the layout – only info and error are supported.
> Replace warning flash messages with info

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/account_certificate/index.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/index.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/firmware/index.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/layout/_navigation.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/index.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_user/index.html.heex
With updated bootstrap 5, the `data-toggle="dropdown"` attribute needs to be changed to `data-bs-toggle="dropdown"` for the popper lib and boostrap to work on the element
/cc @tonnenpinguin
> Fix dropdown menu toggling

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/_header.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/index.html.heex
This mirrors the tooltip for last certificate use: https://github.com/nerves-hub/nerves_hub_web/blob/5d7c4148b6d30ab663bae2658d39e21c199c6dfe/apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.heex#L131-L138
> Add tooltips for exact device last-handshake time

- .circleci/config.yml
The migrate and deploy tasks both use the versioned tag:
https://github.com/nerves-hub/nerves_hub_web/blob/f72afa9868c41519126dbe7b9ece5fb7d9688bbd/.circleci/config.yml#L57
https://github.com/nerves-hub/nerves_hub_web/blob/f72afa9868c41519126dbe7b9ece5fb7d9688bbd/.circleci/config.yml#L72
> Don't push "latest" tag to Docker Hub from next-main branch

- apps/nerves_hub_api/config/release.exs
- apps/nerves_hub_www/config/release.exs
- config/prod.exs
This may eventually be removed, but this changes the default to prevent
signups and require that a user explicitly set it. This will help cases
of orgs running their own instance of NH and not wanting to accidentally
allow a bunch of unknown accounts
> Default preventing signups

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/deployments.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/upload/file.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/workers/firmware_delta_builder.ex
- apps/nerves_hub_web_core/mix.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
- apps/nerves_hub_web_core/test/nerves_hub_web_core/firmwares/firmwares_test.exs
- config/config.exs
- test/support/fixtures.ex
(Originally written by @chrisdambrosio)
Resolves an issue where performance is degraded while updating a
deployment that triggers builds of firmware delta files. The same
firmware delta was being built many times simultaneously until one
finished.
- Moves firmware delta build to an Oban job
- Initially sends negative update payload if a delta needs to be built
- After the firmware delta is built, the job will look up relevant
deployments and restart the `fetch_and_update_relevant_devices`
cycle, and send update messages to any relevant devices
This solution has the following advantages:
- Makes the firmware delta creation idempotent: many requests can come
in and the firmware delta will only be built once, but all devices
requiring the update will be notified.
- Ability to control …
> Build firmware deltas with Oban jobs 

- apps/nerves_hub_api/config/release.exs
- apps/nerves_hub_device/config/release.exs
- apps/nerves_hub_www/config/release.exs
- config/prod.exs
- rel/scripts/ecs-cluster.sh
* Increase the log level which should be a best practice for any production instance.
* Add a qualifier to the echo statement so we can tell if the other nodes are actually found. Otherwise, this could fail and print a blank line and we wouldn't know.
* Remove empty strings from sync nodes
> Cluster fixes

- .circleci/config.yml
CircleCI defaults to not running for tags, so any dependent jobs need an
explicit, permissive tag filter in order to run. See
https://circleci.com/docs/2.0/configuration-reference#tags.
> Run CI on tagged commits

- apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex
- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
Fixes #838
We were previously requiring that the signer CA to be registered even if the
device certificate was already pinned, which was incorrect. This fixes that to
skip the check if we're being presented with a signer CA so that validation of the
device certificate can happen.
If the device cert is pinned, the check will pass. If not, it will go through the
normal validation flow and fail due to an expired, unregistered signer CA anyway
> Allow pinned device certs without a registered CA

- apps/nerves_hub_device/test/nerves_hub_device_web/channels/websocket_test.exs
Related to #838. 
As out internal issue was caused by the CA being expired we wanted to add a test for that scenario as well to prevent eventual regressions.
> Add test for expired CA

- apps/nerves_hub_www/assets/js/app.js
- apps/nerves_hub_www/assets/package-lock.json
- apps/nerves_hub_www/assets/package.json
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/home/index.html.heex
propose to stop using joshjs for issue #843
WHY: joshjs's bug prevents firmware upload by GUI
With v1.0.2, we cannot upload firmware by GUI.
This is because joshjs bug has appeared in the improvements made so far.
Fortunately, joshjs is now applied to only one location, so propose to stop using it.
> propose to stop using joshjs for issue

- mix.exs
Until now, `make test-watch` did not seem to be enabled.
```
$ make test-watch
DB=db_test \
. ./.env && \
mix test.watch
** (Mix) The task "test.watch" could not be found
make: *** [Makefile:55: test-watch] エラー 1
```
refs) https://github.com/lpil/mix-test.watch#usage
> Enable mix_test_watch in :dev for 'make test-watch'

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/org_certificate/edit.html.heex
- apps/nerves_hub_www/test/nerves_hub_www_web/controllers/org_certificate_controller_test.exs
- test/support/fixtures.ex
related commit is https://github.com/nerves-hub/nerves_hub_web/pull/804/commits/8be8a6faac40b759419771a59f49a22d5257585a?diff=split&w=0#diff-e253447b15c2a82a129c72a07aae8d99cc3c86efed4fc04bb9c6cd859a9738ee
This bug could have been prevented with tests, so added a test.
> Fix org_certificate_controller :edit cannot render

- apps/nerves_hub_www/lib/nerves_hub_www_web/live/product_live/import.ex
The function passed to `consume_uploaded_entry/3` should returned either `{:ok, result} ` or `{:postpone, my_result}`
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#consume_uploaded_entry/3
> Fix return value passed to consume_upload_entry/3

- README.md
- apps/nerves_hub_device/config/release.exs
- config/dev.exs
OTP >= 24.3 made changes to the TLS 1.3 implementation and now prefers it as the default. Some of the hardended rules break the custom client authentication setup of NervesHub in slightly confusing ways.
This sets the expected server version to TLS1.2 to hopefully reduce these errors and make things a bit more consistent and predictable for now until able to implement #852 and other changes with later OTP releases.
Thanks to @tonnenpinguin and Klaus Grössinger for help identifying this!
> Set TLS version to 1.2 for the server

- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/edit.html.heex
- apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/new.html.heex
Seems like the classes on the checkbox markup I copied weren't correct. With the `form-control` class the checkmark doesn't properly show.
> Fix checkbox class

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/accounts/accounts_test.exs
Previously the function would generate a query with the OR grouped incorrectly. This commit changes the position of the `exclude_deleted/0`
call so that the query looks for `(username: X or email: X) and not deleted`
instead of `(username: X and not deleted) or email: X)`
> Fix Accounts.get_user_by_email_or_username/1

- apps/nerves_hub_api/mix.exs
- apps/nerves_hub_web_core/mix.exs
Base62 needs to be included in extra applications for the apps using it
since the dep is in the root of the umbrella, but apps can be deployed
individually
> Fix Base62 requirement

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts/org_limit.ex
Apparently, we needed bigger limits. These limits didn't seem so large as to not
be the upstream ones as well.
Thoughts?
> make limits virtually unlimited by default

- apps/nerves_hub_api/config/release.exs
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/audit_logs.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/workers/truncate_audit_logs.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/audit_logs_test.exs
At sparkmeter we've had some very noicy devices, which generated so many logs, that it needed cleanup before the system became usable again. This adds a worker (which I hope I added correctly) to periodically cleanup the audit log, so things stay working. By default the worker is disabled, so we don't delete data for people expecting nothing to get deleted.
> Add worker for periodically cleaning up audit logs

- apps/nerves_hub_api/config/release.exs
- config/dev.exs
Similar issues to the troubles devices were having with TLS 1.3. If users are using `nerves_hub_user_api` or another Elixir/Erlang lib with <= 25.1, then requests will fail to the API.
To mitigate that, we'll just force API and Device to be TLS 1.2
> Use TLS 1.2 for API

- docs/deploying.md
Without casting the string to int, the server crash on startup.
Also a small typo fixed.
> Fix typo and port configuration

- assets/css/_layout.scss
- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/templates/device/index.html.heex
- lib/nerves_hub_web/views/device_view.ex
- Reduce device updates to the liveview that causes the page to be very difficult to work with when there's a device updating that's being displayed.
- Hide last handshake to be a tooltip for device is offline
- Rearrange bulk actions to pull tagging into the section that appears for bulk actions.
> Device index page updates

- test/nerves_hub_web/controllers/account_certificate_controller_test.exs
- test/nerves_hub_web/controllers/api/device_certificate_controller_test.exs
- test/nerves_hub_web/controllers/api/user_controller_test.exs
- test/test_helper.exs
They are excluded from `mix test` and some amount of the code behind it has been removed (due to removing NervesHubCA integration.)
> Remove `:ca_integration` tests

- lib/nerves_hub/firmwares.ex
- lib/nerves_hub_web/controllers/deployment_controller.ex
- lib/nerves_hub_web/templates/deployment/edit.html.heex
- lib/nerves_hub_web/templates/deployment/new.html.heex
When editing a deployment, limit the choices available to the same platform and architecture to reduce accidentally picking the wrong firmware and deploying something you didn't want.
> Limit firmware choices to the same platform/architecture for deployments

- lib/nerves_hub_web/live/account_live/show.ex
- lib/nerves_hub_web/live/deployment_live/show.ex
- lib/nerves_hub_web/live/device_live/console.ex
- lib/nerves_hub_web/live/device_live/edit.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/live/product_live/import.ex
Some of our LiveViews completely swallow errors and make it nearly impossible to debug and figure out what went wrong. This formats the exception as an error to have it in logs for future us.
> Log what we rescue before redirecting

- config/release.exs
Allow running a single node that handles everything. The only thing else that relies on this value in app env is already configured for it in `application.ex`
> Add `all` checks for nerves_hub_app

- Dockerfile
- rel/scripts/docker-entrypoint.sh
- rel/scripts/s3-sync.sh
Since we're not using the Nerves Hub CA anymore, we can stop running this on app boot.
> Remove s3-sync file

- config/dev.exs
- config/release.exs
With user certificates gone, we don't need this configuration and can simplify for future hosting.
> Remove TLS config around the API endpoint

- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/plugs/fetch_user.ex
- lib/nerves_hub_web/plugs/org.ex
- lib/nerves_hub_web/plugs/product.ex
- lib/nerves_hub_web/templates/device/index.html.heex
- lib/nerves_hub_web/templates/home/index.html.heex
- lib/nerves_hub_web/templates/layout/_navigation.html.heex
- lib/nerves_hub_web/templates/layout/_tabnav.html.heex
- lib/nerves_hub_web/templates/org/index.html.heex
- lib/nerves_hub_web/views/device_view.ex
- lib/nerves_hub_web/views/home_view.ex
- lib/nerves_hub_web/views/layout_view.ex
- lib/nerves_hub_web/views/org_view.ex
- Top level plug that fetches everything the layout needs when loading the user
- Update plugs below the `FetchUser` plug to use what was already loaded
- Update views to use the already loaded data instead of fetching multiple times and count on a new query
> Plugs and views should load orgs/products less

- lib/nerves_hub/firmwares.ex
- lib/nerves_hub_web/live/device_live/index.ex
If you have multiple version numbers for differing platforms (or just different UUIDs) they show up multiple times in this list.
> Select only firmware version numbers for the device filters

- Makefile
- README.md
- config/config.exs
Fixes:
- `make reset-db` was broken because of a typo
- Adds getting started commands that don't rely on make because many elixir developers may not have make installed
- Adds the `namespace: NervesHub` to the configuration
- Without this `mix phx.routes` doesn't work by default
Split out from https://github.com/nerves-hub/nerves_hub_web/pull/909
> Readme improvements and various fixes

- lib/nerves_hub_web.ex
- lib/nerves_hub_web/api_endpoint.ex
- lib/nerves_hub_web/api_router.ex
- lib/nerves_hub_web/router.ex
- test/nerves_hub_web/plugs/api/user_test.exs
- test/support/conn_case.ex
Start to deprecate the API node, since it no longer needs user certs its similar to the web node and we don't need to have separation.
> Forward the APIRouter from the web Router

- rel/scripts/ecs-cluster.sh
We don't have names per node type now, everything is `nerves_hub`
> Update ecs-cluster script for new release name

- config/config.exs
This will hopefully give it a bit more time to churn through bursts before it starts dropping connections and trigger alerts.
> Allow more DB queue time to handle connection bursts

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
The validate conditions changeset for a deployment sets the version to an empty string if its not provided.
> Version condition is an empty string, not nil

- lib/nerves_hub/deployments.ex
- test/nerves_hub/deployments_test.exs
Goes back to the previous style of matching version requirements now that the only usage is devices looking for deployments and there is a very small set of data that will be loaded (1-10 deployments.)
Closes #907
> Replace semver_match usage with Version.match? for deployments

- config/config.exs
- lib/nerves_hub/audit_logs.ex
- lib/nerves_hub/config.ex
- lib/nerves_hub/workers/truncate_audit_logs.ex
- test/nerves_hub/audit_logs_test.exs
Prune beyond a date and limit the amount of data deleted each run. Run hourly to prune a little bit every hour instead of a huge amount once a day to be night to the vacuum.
> Truncate audit logs hourly

- lib/nerves_hub_web/live/device_live/show.ex
The uuid is not guaranteed to be unique further than a product, so this was accidentally finding firmware for other organizations that happened to match (different environments essentially)
> Lookup firmware by product and uuid

- README.md
- config/config.exs
- config/dev.exs
- config/prod.exs
- config/release.exs
- config/test.exs
- lib/nerves_hub/accounts/email.ex
- lib/nerves_hub/application.ex
- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/firmwares/upload/file.ex
- lib/nerves_hub/firmwares/upload/s3.ex
- lib/nerves_hub/mailer.ex
- lib/nerves_hub/release/tasks.ex
- lib/nerves_hub/repo.ex
- lib/nerves_hub/stats.ex
- lib/nerves_hub/supervisor.ex
- lib/nerves_hub/tracer.ex
- lib/nerves_hub/workers/delete_firmware.ex
- lib/nerves_hub_web/api_endpoint.ex
- lib/nerves_hub_web/controllers/firmware_controller.ex
- lib/nerves_hub_web/device_endpoint.ex
- lib/nerves_hub_web/endpoint.ex
- lib/nerves_hub_web/gettext.ex
- lib/nerves_hub_web/plugs/set_locale.ex
- mix.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/support/fixtures.ex
:nerves_hub_www went "deprecated" when we dropped the umbrella and this makes more sense to go with.
> Rename OTP app to :nerves_hub

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
Check the incoming payload to see if it still matches the old deployment and set back to that deployment. If not, delay looking up for a spaced out amount of time to not cause a thundering herd of devices checking the database (they still will but it will be a little better)
> Optimize device deployment reassignment when previously assigned

- lib/nerves_hub_web/channels/console_channel.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/show.html.heex
Force a NervesHub reconnect by using a button on the device page. This won't reboot the device, just force a `NervesHubLink.reconnect/0`
> Add a reconnect button to device page

- lib/nerves_hub/application.ex
- lib/nerves_hub/deployments.ex
- lib/nerves_hub/deployments/monitor.ex
- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/deployments/supervisor.ex
- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
Don't push deployment updates directly to the device channel, introduce a process between the two in order to have a hook for rolling updates going forward.
There's no specific tests for this because I'm not entirely sure how to test it. But I've done manual testing with my ~200 devices and they upgraded without issue. This _shouldn't_ be any different than how things currently are.
> Push deployment updates through an orchestrator process

- lib/nerves_hub_web/controllers/api/device_controller.ex
- lib/nerves_hub_web/views/api/device_view.ex
Don't return all results in this endpoint, and allow for filtering to limit the results to a certain set of tags / platforms / arch / etc
> Device index endpoint can filter and paginate

- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub_web/channels/device_channel.ex
And check for a new matching deployment in the product
> When moving devices between products, clear the assigned deployment

- lib/nerves_hub/deployments/deployment.ex
- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/inflight_update.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/deployment_controller.ex
- lib/nerves_hub_web/templates/deployment/show.html.heex
- priv/repo/migrations/20230512142158_create_inflight_updates.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
When a deployment tells the device to update, track its progress and display on the deployment page.
This is not paginated because the next step of rolling deployments is to limit the amount of inflight updates at any given time.
There is a potential issue of getting stuck while updating and not being able to create a new inflight update because one exists for a deployment already. Right now it just logs that there was a problem. We could make a clear all progress button on the deployment, a little "X" for each identifier to clear just that one, or do the same on the device page. I'm not sure which one is better or if there's a better way.
> Track inflight updates for devices based on a deployment

- lib/nerves_hub/deployments/deployment.ex
- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/deployment_controller.ex
- lib/nerves_hub_web/templates/deployment/edit.html.heex
- lib/nerves_hub_web/templates/deployment/show.html.heex
- priv/repo/migrations/20230515201055_add_rolling_update_fields_to_deployments.exs
- priv/repo/migrations/20230523153509_add_index_to_deployment_id_for_inflight_updates.exs
- test/nerves_hub_web/channels/websocket_test.exs
Adds a new field `concurrent_updates` that sets the maximum number of updating devices that NH will tell to update at any given time. There is still a spike for reconnecting devices, this is expected for now. We're going to see how it works with that and come back later.
Devices will be told one at a time on deployment update for each node. They will grab a slot and tell the device to update. When the device comes back online, it will tell its new orchestrator that it updated and the orchestrator will tell another device to update if there's a slot.
There's a 5 minute tick to trigger deployment again as a catch all if devices don't evenly connect to nodes.
> Rolling Device Updates

- lib/nerves_hub_web/channels/device_channel.ex
Since we were clearing in the after_join an in progress update was being cleared if it was handed to the device on connect. We still want the device to be allowed to spike past the rolling deploy but be tracked.
> Clear the inflight updates before potentially making a new one

- lib/nerves_hub_web/views/layout_view.ex
The ellipsis check is broken because `page` contains a safe tuple.
> Display pagination links better

- config/config.exs
- lib/nerves_hub/deployments/deployment.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/inflight_update.ex
- lib/nerves_hub/workers/expire_inflight_updates.ex
- lib/nerves_hub_web/templates/deployment/edit.html.heex
- lib/nerves_hub_web/templates/deployment/show.html.heex
- priv/repo/migrations/20230606174815_add_expires_at_to_inflight_updates.exs
Worker to clear inflight updates every 5 minutes based on the expiration from the deployment. This should help clear out devices that are clogging the rolling update queue and are just offline for unrelated reasons.
> Worker to expire inflight updates after a set amount of time

- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/console_channel.ex
- lib/nerves_hub_web/channels/device_channel.ex
:crossed_fingers:  gracefully shutdown device sockets if there's an issue during a deployment and gproc times out.
> Wrap :gproc calls in try/catch and raise a custom exception

- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
Force the orchestrator to not consider these devices when picking a device to send an update to. Set a timer to clear out the penalty box after it's time is up. Also ignore devices that are set to disable updates entirely by a user.
> Trigger an update after the penalty box is cleared

- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/device_controller.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/_header.html.heex
- lib/nerves_hub_web/templates/device/index.html.heex
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/nerves_hub_web/controllers/device_controller_test.exs
Reducing the amount stored in gproc should help with staleness in gproc, since there's less data shuffling around. There's also less updates if we're not storing the deployment_id and product_id.
> Track less information in gproc

- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/device_controller.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/_header.html.heex
- lib/nerves_hub_web/templates/device/console.html.heex
- lib/nerves_hub_web/templates/device/show.html.heex
- lib/nerves_hub_web/views/api/device_view.ex
- test/nerves_hub_web/controllers/device_controller_test.exs
Preparing for a new way of tracking presence that doesn't use gproc, and the less we store, the better this will work out. We only really need to know that something is online for presence tracking. The rest is stored or we can get live while it happens as a broadcast.
> Remove all keys from presence tracking except for status

- lib/nerves_hub/devices/device.ex
- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/_header.html.heex
- lib/nerves_hub_web/templates/device/index.html.heex
- lib/nerves_hub_web/templates/device/show.html.heex
- test/nerves_hub_web/live/device_live_index_test.exs
It's used in the device liveviews and is merged in from the presence server as merging in metadta. Instead, store the status separately which can be more easily updated via a map on the device id.
> Don't store device status on the ecto struct

- lib/nerves_hub/devices/device.ex
- lib/nerves_hub_device/presence.ex
- lib/nerves_hub_web/channels/console_channel.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/api/device_controller.ex
- lib/nerves_hub_web/live/device_live/index.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/_header.html.heex
- lib/nerves_hub_web/templates/device/index.html.heex
- lib/nerves_hub_web/templates/device/show.html.heex
- test/nerves_hub_web/live/device_live_index_test.exs
Disconnect the socket so the device channel isn't the only thing terminated. Leaving the console channel open and having the device not try to reconnect the main channel.
> Reconnect button disconnects the socket

- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/device/show.html.heex
- test/nerves_hub_web/live/device_live_show_test.exs
Broadcast the messages regardless of if the liveview node thinks the device is online. It might be and the tracker is out of sync. Something might be listening so let it try to happen.
> Always allow the device header buttons to be clicked

- lib/nerves_hub/application.ex
- lib/nerves_hub/devices/device_link.ex
Causing the online device count to be doubled because the same registry is being used more than once. They should probably be separate anyways.
> Use a separate registry for DeviceLinks

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/views/api/device_view.ex
- test/nerves_hub/devices_test.exs
- latest: updates disabled, no deployment, matching the deployment
- updating: update attempts are present and it doesn't match the above
- pending: anything else, which should be only devices that haven't started updating and don't match the current deployment firmare
> Add device firmware update status to the API

- lib/nerves_hub/devices/device.ex
- priv/repo/migrations/20230726201750_create_unique_index_on_devices.exs
Since we're moving towards a single company running a single NervesHub, this constraint doesn't make a ton of sense now.
> Remove `org_id` from the unique constraint on devices

- lib/nerves_hub/tracker.ex
When a lot of new nodes come online during a deploy, we will have a large number of nodes that don't have the tracker online and start getting GenServer calls that exit because the new node hasn't fully started yet.
> Catch `noproc` exits in trackers for lots of new nodes

- lib/nerves_hub/audit_logs.ex
- lib/nerves_hub/audit_logs/audit_log.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/device_socket.ex
- lib/nerves_hub_web/templates/audit_log/_audit_log_feed.html.heex
- priv/repo/migrations/20230801181852_add_reference_id_to_audit_logs.exs
- test/nerves_hub/audit_logs/audit_log_test.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/controllers/api/deployment_controller_test.exs
- test/nerves_hub_web/controllers/deployment_controller_test.exs
Mostly around device connections. So we can tie device actions to a specific connection, like a connect and disconnect message.
> Add a reference id to audit logs

- lib/nerves_hub/audit_logs.ex
- lib/nerves_hub/audit_logs/audit_log.ex
- lib/nerves_hub/deployments.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/controllers/api/deployment_controller.ex
- lib/nerves_hub_web/controllers/api/device_controller.ex
- lib/nerves_hub_web/controllers/deployment_controller.ex
- lib/nerves_hub_web/controllers/device_controller.ex
- lib/nerves_hub_web/live/device_live/show.ex
- lib/nerves_hub_web/templates/audit_log/_audit_log_feed.html.heex
- priv/repo/migrations/20190403164436_create_audit_logs.exs
- priv/repo/migrations/20230801185335_null_true_on_action_and_params_for_audit_logs.exs
- test/nerves_hub/audit_logs/audit_log_test.exs
- test/nerves_hub/audit_logs_test.exs
- test/nerves_hub_web/controllers/api/deployment_controller_test.exs
- test/nerves_hub_web/controllers/deployment_controller_test.exs
Nothing uses those fields and they just make the function call to audit logs very long.
> Remove action and params from audit logs

- config/dev.exs
- config/release.exs
- lib/nerves_hub_device/ssl.ex
- test/nerves_hub_device/ssl_test.exs
Older versions of OTP that may be on devices have a harder time connecting to a server which allows TLS 1.3. For improved backwards compatibility, this sets the default TLS 1.2 for the DeviceEndpoint which should only have issues with devices using OTP 24.3.2 TLS v1.3
> Enforce TLS 1.2 for most backward compatibility

- priv/repo/migrations/20230801185335_null_true_on_action_and_params_for_audit_logs.exs
Ecto might lock the table with this method and that would not be good with this table.
> Don't use `alter table(:audit_logs)`, directly execute the sql

- lib/nerves_hub/ssl.ex
If a device certificate doesn't have an SKI, then the `NervesHub.SSL` verification function will fail silently and return `unknown_ca` making for confusing behavior.
This protects against `nil` and ensures an SKI is available to lookup when needed
> Protect against missing SKI

- lib/nerves_hub/deployments.ex
- test/nerves_hub/deployments_test.exs
If a device has never connected, the `firmware_metadata` is `nil`. We were previously attempting to ignore this case before, but it would only apply if used as a single airily. If someone used `Deployments.alternate_deployment/2` without the default (like when updating tags on a device), the things would 💥 
This fixes the default definition so `firmware_metadata: nil` is properly skipped
<details><summary>Exception</summary>
<p>
```
Request: POST /org/poser/poser/devices/poser-bad
** (exit) an exception was raised:
** (KeyError) key :platform not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(nerves_hub 0.1.0) lib/nerves_hub/deployments.ex:238: NervesHub.Deployments.alternate_deployments/2
(nerves_hub 0.1.0) …
```
> Fix crash when updating tags on device without firmware metadata

- assets/js/console.js
In OTP 26, [`CTRL-L` now clears the screen](https://github.com/erlang/otp/commit/14555ef0440843a7ad1b879a15f9c6236fc597ca). If you (and others) are using a console page, the next person to reload the page will wipe the screen of all connected users with that page open.
Not sure why that was in there, so this removes that initial request so screens don't clear!
> Don't `CTRL-L` on console start

- lib/nerves_hub_web/user_console_channel.ex
For other users to know when you've left (since we post when you join)
> Post an event when the console is closed

- assets/js/console.js
- lib/nerves_hub_web/channels/user_console_channel.ex
- lib/nerves_hub_web/channels/user_socket.ex
- lib/nerves_hub_web/templates/device/console.html.heex
It was a global chat previously, so any device could chat with another device. This limits to specific devices.
> Use unique channels to limit the chat to that device

- assets/js/console.js
- lib/nerves_hub_web/channels/console_channel.ex
Server side to allow uploading files from devices to your open console page. This is handy for grabbing logs or binary files for inspection.
NHL PR: https://github.com/nerves-hub/nerves_hub_link/pull/130
> Handle incoming files from NervesHubLink

- config/prod.exs
- config/release.exs
- lib/nerves_hub_web/endpoint.ex
- lib/nerves_hub_web/plugs/file_upload.ex
This previously wouldn't allow for running in single node mode without S3 because of a compile env warning.
To remove the Plug.Static from the endpoint because we need information determined at runtime (past compile time which is what this uses)
> Create a plug for local file uploads

- lib/nerves_hub/tracker.ex
When a device comes online, and they have multiple connections (e.g. wifi and cellular), the previous failed connection may terminate before the fallback connection fully comes online causing a noproc error.
This could happen by the tracker state being slightly out of date from replication across the cluster.
> Handle noproc error when a device comes online

- lib/nerves_hub/accounts.ex
- lib/nerves_hub_web/controllers/org_controller.ex
- lib/nerves_hub_web/controllers/org_user_controller.ex
- lib/nerves_hub_web/router.ex
- lib/nerves_hub_web/templates/org_user/index.html.heex
Allow to rescind outstanding invites to clear the list out.
This includes the invite link currently because email is being funky. This will eventually go away when we figure out what's going on.
> List outstanding invites for an organization

- lib/nerves_hub/accounts.ex
If a user is deleted and the org_user row still exists, this will create a 500 error on the listing page because the preload for the user doesn't load the user.
> Filter out deleted users from the list of org users

- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/device_socket.ex
Based on #1040
`NervesHub.SSL` preps the device existence before letting it connect socket. By that point, we should have strong confidence we can find the device in the DB.
Previously, the DeviceSocket was _only_ querying the certificate and then doing another query when the device joined the channel. This instead does a single lookup on device connect and remvoes extra queries run when the channel starts
> Remove extra certificate and device lookup queries in channel

- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/device_socket.ex
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
This topic was used in the earliest version of NervesHub and the device client connection. However, the lib it was used in ([`nerves_hub`](https://github.com/nerves-hub/nerves_hub)) has been deprecated since 2020-04-14. The last version of that lib to use this topic was [v0.4.0](https://github.com/nerves-hub/nerves_hub/releases/tag/v0.4.0) published 2019-02-14. The latest version available in Hex is v0.7.4 released 2019-06-21.
Since this was completely replaced by `nerves_hub_link` and it's been 4 years, I think it's safe to remove support for this topic which we don't have intentions on reusing in 2.0
> Remove `firmware:<uuid>` topic from DeviceChannel

- lib/nerves_hub/metrics.ex
- lib/nerves_hub/tracker.ex
- lib/nerves_hub_web/channels/device_channel.ex
During a deploy we might trip the "device did not go offline" exception, so we can just expect this and start making metrics. It has thus far only triggered during a deploy.
Also expect a `{:shutdown, reason}` exit from stopping an existing device, this happens when a device has a flapping network connection that bounces between cell/wifi/ethernet quickly. Since the other process is dead anyways, ignore it, goal accomplished.
> Expect new errors when a device connects

- config/dev.exs
- config/release.exs
- config/test.exs
- lib/nerves_hub/metrics.ex
Instead of using the compile time environment, load it from the
environment variables.
> Update :env for statsd metrics to use DEPLOY_ENV

- lib/nerves_hub/metrics.ex
Exports the metrics provided by ecto and then the phoenix metrics that are generated for new applications now.
> Add phoenix and ecto statsd metrics to export

- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/metrics.ex
And also export simple metrics around how often a trigger happens and how many devices are happening.
> Wrap the deployment orchestrator with traces

- assets/css/_console.scss
- assets/js/console.js
- lib/nerves_hub_web/templates/device/console.html.heex
The chat window didn't have css set up to scroll messages so it just grew forever down the page.
> When the console chat fills up we should scroll it

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/controllers/api/device_controller.ex
- lib/nerves_hub_web/views/api/device_view.ex
Surface the information for users to know what the device is expected to update to if the firmware update status is `pending`
> Add deployment information to the API response for devices

- lib/nerves_hub/application.ex
- lib/nerves_hub/load_balancer.ex
Simply logs if the current node would shutdown due to increased device counts. This will help balance devices during a deploy, refusing devices to join an older node that is saturated with devices while the new nodes have very few devices on them.
> Start to a load balancer for devices

- lib/nerves_hub/deployments.ex
- test/nerves_hub/deployments_test.exs
The version change is the limiting factor of when a device can be matched to a deployment fully in a db transaction. This adds a minor optimization to do the deployment calculation for devices in the DB when the deployment does not have a version condition.
Doing this also helps devices that might be offline when the deployment is updated by reducing the load of DB lookups when a device connects. It is especially useful for cases where many devices are coming online at once
> Add minor deployment update optimization

- config/dev.exs
- config/prod.exs
- config/release.exs
- config/test.exs
- lib/nerves_hub/archives.ex
- lib/nerves_hub/archives/archive.ex
- lib/nerves_hub/fwup.ex
- lib/nerves_hub/products/product.ex
- lib/nerves_hub/uploads.ex
- lib/nerves_hub_web/controllers/archive_controller.ex
- lib/nerves_hub_web/endpoint.ex
- lib/nerves_hub_web/plugs/static_uploads.ex
- lib/nerves_hub_web/router.ex
- lib/nerves_hub_web/templates/archive/index.html.heex
- lib/nerves_hub_web/templates/archive/new.html.eex
- lib/nerves_hub_web/templates/archive/show.html.eex
- lib/nerves_hub_web/views/archive_view.ex
- lib/nerves_hub_web/views/layout_view.ex
- priv/repo/migrations/20231023200256_create_archives.exs
- test/nerves_hub/archives_test.exs
- test/nerves_hub_web/controllers/archive_controller_test.exs
- test/support/archives.ex
- test/support/fixtures.ex
Archives are extra firmware files that the device will be told about on connection. This can hold extra data that can be updated out of band from the main firmware.
This also includes a more generic style of uploading that we can convert the previous firmware uploads to in a separate PR. We would need to copy paste the uploader anyways so I went with a style I'm more comfortable with and have used in the past.
> Upload archives to a product

- priv/repo/seeds.exs
while running the seeds I saw:
```
warning: unused alias Firmwares
priv/repo/seeds.exs:16
```
this fixes the warning.
> remove an unused alias in `seeds.exs`

- lib/nerves_hub_web/templates/layout/_footer.html.heex
- remove the status page link, which goes nowhere
- remove the support email link, GitHub issues are the preferred means of help
- link to this repos for the issues link, and not the smartrent repo, which 404s
and these last two might be a bit presumptuous 
- remove the `nerves_hub` hexdocs link
- and remove the nerves key link
these both are very specific and are better served by using the docs.
> update footer links

- config/dev.exs
- config/test.exs
When running the tests I came across:
```
warning: :included_environments option is deprecated. Use :dsn to control whether to send events to Sentry.
(nimble_options 1.0.2) lib/nimble_options.ex:556: NimbleOptions.validate_value/3
(nimble_options 1.0.2) lib/nimble_options.ex:542: NimbleOptions.validate_option/3
(nimble_options 1.0.2) lib/nimble_options.ex:524: NimbleOptions.reduce_options/2
(elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
(elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
(nimble_options 1.0.2) lib/nimble_options.ex:517: NimbleOptions.validate_options/2
```
This PR fixes the issue, and brings `dev.exs` and `test.exs` Sentry config inline with each other.
> fixes a Sentry warning when running the tests

- lib/nerves_hub_web/router.ex
- lib/nerves_hub_web/views/layout_view.ex
I found it a bit odd that Org settings were setup as `/settings/:org_name` instead of `/org/:org_name/settings`
This PR updates the routes to used the nested approach.
> Change the org settings routes to be nested under `/orgs/:name`

- Dockerfile
- config/release.exs
Following the [Sentry 10.x upgrade guide](https://hexdocs.pm/sentry/upgrade-10-x.html)
* Runs `sentry.package_source_code` before the release
* Removes `included_environments`
> Update Sentry config for 10.x.x

- lib/nerves_hub_web/endpoint.ex
`:inet6` needs to be passed to the ThousandIsland transport directly as the `Bandit.PhoenixAdapter` is unable to parse it from a mismatched proplist as it currently is
> Alter `:inet6` opt for Bandit

- .github/workflows/ci.yml
This PR uses GitHub Actions and Container Registry for testing and publishing Docker images.
By publishing Docker images we can reduce the complexity for setting up your own Nerves Hub.
This opens the door for people to use PaaS's to run Nerves Hub without having to clone the repo.
In fact, people can run Nerves Hub locally with a simple `docker pull ghcr.io/nerves-hub/nerves-hub` 
There is a little duplication with Circle CI as we are also running the tests here, but on the plus side, this whole test and build workflow takes half the time than Circle.
Docker images are only pushed to the Container Registry for the main branch (latest) and tags.
> Build and publish Docker images to GitHub Container Registry

- config/runtime.exs
Only load if provided, ECS uses role based permissions and this won't be set in that deployment environment.
> Don't require S3 access key id or secret access key

- config/runtime.exs
If other database SSL is not configured, use the `:public_key.cacerts_get()` function to load the system CA certs and explicitly use with DB connection.
Defaulting to `[]` effectively prevents any default system certs from being used. `:public_key.cacerts_get` is a preference here as well since some deployments load their specific CA store into the system path and may not be signed with globally registered CA in `CAStore` file. However, most systems include the same certificates as well anyway.
> Use system CA certs explicitly for DB connections

- config/runtime.exs
This doesn't appear to be an option in ThousandIsland and it's messing up starting the DeviceEndpoint because this needs to be a keyword list.
Update: it is an option deeper down in gen_tcp and ssl but something in Bandit is treating it as a keyword list still
> Remove inet6 option from the DeviceEndpoint

- lib/nerves_hub/devices/device_link.ex
- lib/nerves_hub_web/channels/device_channel.ex
* Remove `DeviceLink.disconnect/1` from channel terminate
* The device channel is monitored by DeviceLink. The extra call to `DeviceLink.disconnect/1` would sometimes timeout causing bigger issues with restarts elsewhere or race getting to the link process potentially producing DOWN messages after the monitor was cleared from link causing unmatched `handle_info` callbacks to be evaluated 
* Ignore messages from unknown socket in DeviceLink
* TCP sockets have longer timeouts. There is a chance the old socket was still around when the new one started which could result in getting this message later than expected. For cases like that and when we no longer know the ref, simply ignore
> Device link fixes

- lib/nerves_hub/rate_limit.ex
If the limit is 1, then we'll never let devices in.
> Rate limit should be inclusive

- lib/nerves_hub/devices/device_link.ex
- test/nerves_hub/devices/device_link_test.exs
Crashing DeviceLink could cause cascading problems. To fix that, this change ignores unhandled messages in `handle_info` and logs it
> Ignore unhandled messages in DeviceLink

- apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex
- apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares/delta_updater/default.ex
- apps/nerves_hub_web_core/test/nerves_hub_web_core/devices/devices_test.exs
Requires fwup >= 1.10.0
Closes #885
> Default delta updater can delta non-block resources

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/controllers/api/ca_certificate_controller.ex
- lib/nerves_hub_web/views/api/ca_certificate_view.ex
- test/nerves_hub_web/controllers/api/ca_certificate_controller_test.exs
Alternate implementation for #880
* Add `jitp` to CACertificate API response
* Support `jitp` in API CACertificate create
> API improvements for JITP

- config/runtime.exs
- mix.exs
And remove the reboot_system_after_config option since we aren't adjusting the kernel config.
To be merged along with https://github.com/nerves-hub/nerves_hub_web/pull/1151
> Remove SYNC_NODES_OPTIONAL from runtime config

- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/shared_secret_auth.ex
- lib/nerves_hub_web/channels/device_socket_shared_secret_auth.ex
- priv/repo/migrations/20240107163347_create_device_shared_secret_auth.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
Next part of #1136
Adds support for individual device secret auth. These can also be associated with a production shared secret auth to track when a device auth is created from the product auth (coming next). This will be helpful in the future to easily deactive all device tokens associated with a deactivated production token
> Add `Devices.SharedSecretAuth`

- config/runtime.exs
The default is a cleaned version of the cookie, which seems to be too long for postgres notify. Our cookie is 64 characters long, running a `NOTIFY` with a different 64 character long string also fails. To get around this we can manually set a cookie name.
> Set the channel name that libcluster_postgres uses

- config/runtime.exs
Based on what we have for Oban, it most likely doesn't need to claim as many connections as the main Repo. This let's us set it separately and scale it back.
Also fixes a typo in a variable near by
> Add an ENV for setting the Oban pool size independently

- lib/nerves_hub/devices/device_link.ex
- test/nerves_hub/devices/device_link_test.exs
- test/nerves_hub_web/channels/device_channel_test.exs
The connection between a DeviceLink and DeviceChannel is unreliable when there is a horde of devices trying to connect. A too large percentage of devices can think they have a DeviceLink but it terminated and didn't terminate the DeviceChannel. If we terminate faster, this may reduce the number of devices in this state.
> Remove the reconnect timer in DeviceLink

- config/runtime.exs
Tell the ssl_gen_statem process to hibernate after 15s of no activity, this will force a GC sweep and keep memory low. Otherwise there's a memory leak that was discovered with `:recon.bin_leak/1`. Running `:recon.bin_leak/1` on a two node cluster and 5k sockets recovered 2GB of memory per node. No memory leak was noticed with this setting and the same amount of devices.
> Have the ssl process hibernate after 15s

- config/dev.exs
- config/runtime.exs
- lib/nerves_hub/device_ssl_transport.ex
- lib/nerves_hub/ssl.ex
Delegates to the SSL transport from ThousandIsland but adds rate limiting before the handshake. To forcefully close before SSL is allowed to start doing CPU intensive tasks.
> Add a custom device transport for ThousandIsland

- lib/nerves_hub/application.ex
This used tracker shards to collection device information and needs to be updated for another method before being useful for detecting load
> Remove the load balancer from the application tree

- lib/nerves_hub_web/device_endpoint.ex
https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-common-configuration
This should shed devices in a more controlled manner than dropping all N sockets at the same time when a SIGTERM is received.
> Configure Phoenix socket drainer for devices

- lib/nerves_hub_web/channels/device_channel.ex
`socket.assigns.penalty_timer` will error unless the key exists and is nil for the `if` check
> Set a nil penalty timer in assigns

- lib/nerves_hub_web/device_endpoint.ex
Upon reading the docs again, the config should not be at the top level of the socket call.
> Move the device drainer config to be under `websocket`

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/websocket_test.exs
It's a step that we don't need and a hold over from DeviceLink
> Remove the few calls to push to a device that send messages

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
It's a very large portion of what's in the audit logs table. We should probably be storing these in another way because devices tend to flap online/offline enough with LTE connections.
> Remove connect/disconnect messages from the audit logs

- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/device_live/index.ex
- The rebooting message is a handle_in. This was missed during the DeviceLink -> DeviceChannel reset
- Device Index should ignore unknown broadcasts. It's receiving the device internal channel now and should be skipped
except for connection changes
> Device channel fixes

- config/config.exs
- lib/nerves_hub/devices.ex
- lib/nerves_hub/logger_formatter.ex
- lib/nerves_hub/metrics.ex
- lib/nerves_hub_web/channels/device_channel.ex
Add logging to devices connecting, disconnecting, receiving an update, and successfully updating. Outputs metadata as key/value pairs for parsing with something like datadog.
> More logging around device events

- .tool-versions
The `mix assets.compile` fails using python 3.11 and 3.12
```
...
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
...
```
Using 3.10 fixes the error
> add python 3.10.13 to .tool-versions

- lib/nerves_hub/tracker.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/views/api/device_view.ex
The API doesn't have the ability to wait for a response async and needs to know before it can render the JSON. If the device is online this will be fast, if it's offline it will be slow because we're waiting for the timeout to occur.
The big question is how long should we wait before assuming the device is offline?
> Add a synchronous device online check

- lib/nerves_hub/release/tasks.ex
This is used in the runtime.exs configuration and needs to be started before we load the nerves_hub application
> Start tls_certificate_check before migrating

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
related to https://github.com/nerves-hub/nerves_hub_link/pull/168
This slightly simplifies the `nerves_hub_link` config in nerves projects, as the `fwup_public_keys` can now be fetched when a device connects. 
This also opens the door for devices to poll for new fwup public keys, or for new keys to be sent to devices on mass when they are created.
> send current org keys to the device, if requested

- lib/nerves_hub_web/controllers/api/device_controller.ex
This changed recently and now matches this line https://github.com/nerves-hub/nerves_hub_web/blob/main/lib/nerves_hub_web/channels/console_channel.ex#L65
> Use the correct channel when broascasting code to devices

- lib/nerves_hub_web/views/api/script_view.ex
Hello! Noticed this got missed in the rename while trying to use the API.
> fix: script list api endpoint

- config/runtime.exs
make sure the tmp directory exists before writing to it, otherwise the `File.write` explodes
> fix a `runtime.exs` error

- config/runtime.exs
- lib/nerves_hub_web/device_endpoint.ex
- lib/nerves_hub_web/plugs/device_endpoint_redirect.ex
- test/nerves_hub_web/plugs/device_endpoint_redirect_test.exs
this stops the following log lines in the device endpoint logs due to a route not being found:
```
[info] 02:21:22.472 [error] pid=<0.47185.0> Task #PID<0.47185.0> started from #PID<0.47180.0> terminating
[info] ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
[info] (bandit 1.2.2) lib/bandit/pipeline.ex:147: Bandit.Pipeline.commit_response/1
[info] (bandit 1.2.2) lib/bandit/pipeline.ex:26: Bandit.Pipeline.run/6
[info] (bandit 1.2.2) lib/bandit/http2/stream_task.ex:69: Bandit.HTTP2.StreamTask.run/5
[info] (elixir 1.16.2) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
[info] Function: &Bandit.HTTP2.StreamTask.run/5
[info] Args: [%Bandit.HTTP2.Adapter{connection: #PID<0.47180.0>, transport_info: %Bandit.TransportInfo{secure?: true, sockname: …
```
> device endpoint: redirect on 404

- config/runtime.exs
related to https://elixirforum.com/t/how-to-troubleshoot-a-request-line-read-error/60839
this setting is due to become the default in Bandit 2.0
> silence bandit protocol errors

- lib/nerves_hub_web/device_endpoint.ex
- lib/nerves_hub_web/endpoint.ex
- lib/nerves_hub_web/plugs/im_alive.ex
I use these for my deployments to Fly.io, which require a health check for blue green deployments
> the start of a handy health check route for both endpoints

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
this is related to https://github.com/nerves-hub/nerves_hub_link/issues/47
**open questions:**
do we want to add an audit log for this?
should the event name be something more like `update:check` or `update:check_available`?
> add support for devices checking if an update is available

- lib/nerves_hub_web/device_endpoint.ex
- lib/nerves_hub_web/endpoint.ex
It seems to be in the wrong spot per the docs for `socket/3`
> Remove drainer config from device endpoint

- lib/nerves_hub_web/device_endpoint.ex
Remove drainer since it seems to be in the wrong spot and there's a default for it anyways
> Set fullsweep_after on device channel

- lib/nerves_hub_web/channels/device_socket.ex
- test/nerves_hub_web/channels/websocket_test.exs
The current way of matching was dependent on the order of headers in the list of tuples and I hit problems when testing other clients against it.
> Change pattern matching on headers for Device connection

- test/support/default_mocks.ex
- test/support/fixtures.ex
- test/support/fwup.ex
- test/support/mocks.ex
- test/test_helper.exs
I was having issues with Elixir constantly recompiling files, and I think I tracked it down to this. 
Also, this feels a bit like a code smell.
> remove use of `compiler_options`

- lib/nerves_hub/accounts.ex
- lib/nerves_hub/accounts/org.ex
- lib/nerves_hub/products/product.ex
- lib/nerves_hub_web/components/navigation.ex
- lib/nerves_hub_web/helpers/authorization.ex
- lib/nerves_hub_web/live/org/delete.ex
- lib/nerves_hub_web/live/org/delete.html.heex
- lib/nerves_hub_web/live/org/settings.html.heex
- lib/nerves_hub_web/live/orgs/index.html.heex
- lib/nerves_hub_web/router.ex
- test/nerves_hub/accounts/accounts_test.exs
- test/nerves_hub_web/controllers/api/product_controller_test.exs
- test/nerves_hub_web/live/org/settings_test.exs
- test/nerves_hub_web/live/orgs/index_test.exs
- test/nerves_hub_web/live/product/settings_test.exs
- removes the default Org named after the user
- adds a UI for deleting an Org
- and removes the validations when deleting a Product
- since Products are soft deleted, its better to keep the data around for x period of time
- this 'cleanup' will be in a later PR
> Delete Org + Product deletion validations + No default Org

- lib/nerves_hub/accounts.ex
- lib/nerves_hub_web/channels/user_console_channel.ex
- lib/nerves_hub_web/helpers/authorization.ex
- test/nerves_hub/accounts/accounts_test.exs
A security issue was found with the `UserConsoleChannel` where an authorization check was missing during the channel join function.
Without this check, any authenticated user can connect to any connected device that has the remote console channel enabled.
> device console: authorization during channel join

- test/nerves_hub/archives_test.exs
- test/nerves_hub/firmwares/firmwares_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/nerves_hub_web/controllers/archive_controller_test.exs
- test/nerves_hub_web/controllers/deployment_controller_test.exs
- test/nerves_hub_web/controllers/firmware_controller_test.exs
- test/nerves_hub_web/live/org/certificate_authorities_test.exs
- test/support/archives.ex
- test/support/browser_case.ex
- test/support/fixtures.ex
- test/support/fwup.ex
this adds the `:tmp_dir` tag on a module level for all `BrowserCase` test files
> prefer `tmp_dir` in tests

- config/dev.exs
- config/runtime.exs
enable it in `:dev`, and only check the env var when the env is `:prod`
> Open registration config tweak

- assets/js/app.js
- config/runtime.exs
- lib/nerves_hub/accounts.ex
- lib/nerves_hub/application.ex
- lib/nerves_hub/archives.ex
- lib/nerves_hub/deployments.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/scripts.ex
- lib/nerves_hub_web.ex
- lib/nerves_hub_web/errors.ex
- lib/nerves_hub_web/live/archives.ex
- lib/nerves_hub_web/live/deployments/edit.ex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/live/devices/settings.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/firmware.ex
- lib/nerves_hub_web/live/support_scripts/edit.ex
- lib/nerves_hub_web/mounts/fetch_org_user.ex
- lib/nerves_hub_web/mounts/fetch_product.ex
- lib/nerves_hub_web/sentry_event_filter.ex
- lib/nerves_hub_web/templates/error/500.html.heex
- lib/nerves_hub_web/views/error_view.ex
- test/nerves_hub_web/views/error_view_test.exs
by using Ectos `!` functions, we can use Phoenix's error handling to show 404 pages.
This is cleaner, and follow convention.
This PR also includes some Sentry tidy ups, including the ignoring of all errors with a code below 500.
> Rely on the power of `Ecto.NoResultsError` for 404s

- lib/nerves_hub_web/channels/device_channel.ex
these tags help with filtering sentry errors
> set some tags before sending a sentry error

- lib/nerves_hub_web/components/device_header.ex
- lib/nerves_hub_web/components/fwup_progress.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
During the move to LiveView I borked a condition check for showing the Fwup progress.
This PR fixes the issues, adds tests, and improves the message. 
(when the progress hits 100, the bar is hidden and a flash is shown saying that the device is about to reboot)
> Fix an issue with fwup progress not being shown

- lib/nerves_hub/firmwares.ex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/live/devices/show_test.exs
I was getting a little annoyed at having to refresh the Device show page when new firmware was uploaded (I was using "send update" a bit)
I've added support for updating this selection box without having to refresh the page. (plus tests)
> dynamically update firmware selection on the Device page

- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/inflight_update.ex
- lib/nerves_hub/workers/expire_inflight_updates.ex
- test/nerves_hub/devices_test.exs
- test/support/fixtures.ex
The Oban worker that cleans up expired `InflightUpdate`s should not be using Ecto directly.
This PR also moves the changeset for creating `InflightUpdate`s to `InflightUpdate`, and adds a test for `delete_expired_inflight_updates/0` which the Oban worker now uses.
> Remove Ecto from the InflightUpdate expiry worker

- lib/nerves_hub/archives/archive.ex
- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/fwup.ex
- test/nerves_hub/fwup_test.exs
- test/support/fwup.ex
This is for @fhunleth 
I removed the multiple Regex compiles and named captures and switched to a single compile and single run.
I also removed duplicated code in `Firmwares` which was doing the exact same thing, line for line.
And added tests.
> Fwup metadata deduplication + tests

- api-spec.yml
- assets/css/_custom.scss
- config/config.exs
- config/runtime.exs
- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/tracker.ex
- lib/nerves_hub/workers/clean_device_connection_states.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/components/device_header.ex
- lib/nerves_hub_web/live/devices/index.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/views/api/device_view.ex
- priv/repo/migrations/20240710220630_add_connection_information_to_devices.exs
- priv/repo/migrations/20240711034526_add_connection_status_index_to_devices.exs
- priv/repo/migrations/20240711034640_remove_last_communication_from_devices.exs
- priv/repo/seeds.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- sync when a device establishes a connection, when it disconnects, and its 'heartbeat' (powered by the device channel)
- sync 'connected', 'disconnected', and 'not_seen' based on the device connecting, disconnecting, and the heartbeat
- add a connection status filter to the device list
- an oban worker that runs each minute to clean up device connection statuses if they haven't been seen in 6 minutes (configurable)
- updated the device show UI to include the last connected at and last seen at
This change will mean that each connected device will write to the devices table once each 5 minutes (configurable) based on a heartbeat timer in `DeviceChannel`. 
While this change isn't expected to be a performance issue, the impact is a little unknown. For example, 100,000 devices updating every …
> sync a devices connection status

- lib/nerves_hub_web/channels/device_channel.ex
Devices with older NervesHubLink versions will crash because it doesn't know what a `check_health` message is and doesn't have the catch all. If the NervesHub instance has the feature disabled it will still send a message because this call was not checked for application config. If the instance does have it enabled then it will be scheduled and can start collecting health metrics as expected.
> Don't send `:health_check` on device connect

- lib/nerves_hub/release/tasks.ex
- priv/repo/migrations/20240711034640_remove_last_communication_from_devices.exs
Adding the migration for removing `last_communication` which was included in https://github.com/nerves-hub/nerves_hub_web/pull/1386 and then removed by https://github.com/nerves-hub/nerves_hub_web/pull/1441 in order to support deploying the removal in a separate step following the guide in https://fly.io/phoenix-files/migration-recipes/#removing-a-column
This also adds more migration control for others using the mix release so that they can step through whatever migration versions needed, whether via commit isolation or manually utilizing the migration task.
This can be separated into 2 PRs, but they seemed related enough to review together
> Remove `last_communication` and allow more migration control

- lib/nerves_hub/devices.ex
- test/nerves_hub/devices_test.exs
This is mostly for race conditions between finishing the DB write of related firmware metadata or deployment update and reading the record back in with a firmware_status (i.e via API request) In those rare cases we might have missing data and need to be able to handle it
Discovered when hitting production with a series of API updates followed by reads
> Safe access when checking uuids in `Devices.firmware_status/1`

- lib/nerves_hub_web/live/support_scripts/edit.html.heex
- lib/nerves_hub_web/live/support_scripts/new.html.heex
Since scripts can include line breaks the new/edit forms should use textareas to allow for easy editing.
> Scripts should use a text area

- lib/nerves_hub_web/live/dashboard/index.ex
- lib/nerves_hub_web/live/dashboard/index.html.heex
- test/nerves_hub_web/live/product/dashboard_test.exs
- Adds basic tests to dashboard map.
- Make sure markers are only generated when both longitude and latitude is provided, as numbers.
- Adds simple marker counter next to map (suggestions on how to display this in a prettier way is welcomed).
> Add tests for dashboard map

- config/config.exs
This is fixing a mistake I introduced into the code base.
The Audit Log truncation worker is using a different name, which means we aren't actually processing this queue, and jobs are backing up.
This fixes it.
Sorry.
> Fix the oban config for the audit log truncation queue

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/index.html.heex
- test/nerves_hub_web/live/devices/index_test.exs
If all deployments are tagged it becomes relevant to add tags to new devices. Finding devices which are untagged has been impossible using the current set of filters.
This adds a filter for Untagged devices.
> Add devices filter to list untagged devices

- lib/nerves_hub_web/live/devices/index.html.heex
`set_tags` is used for the filters and bulk setting tags, and was causing some warnings in the web inspector console.
> Fix a warning about duplicate tag ids

- lib/nerves_hub/devices/device_metric.ex
- lib/nerves_hub/devices/metrics.ex
- lib/nerves_hub/workers/device_health_truncation.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/components/device_health/health_header.ex
- lib/nerves_hub_web/live/devices/device_health.ex
- lib/nerves_hub_web/live/devices/device_health.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- priv/repo/migrations/20240905113948_create_device_metrics.exs
- test/nerves_hub/device_metrics_test.exs
- test/nerves_hub/workers/device_health_truncation_test.exs
- test/nerves_hub_web/controllers/api/key_controller_test.exs
- test/nerves_hub_web/live/devices/health_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
Adds context for metrics, and support to liveviews to use metrics instead of health report (for metrics purposes).
No visual changes are made, the Contex graphs are still used but with a new data fetching approach which will make it easier to create more varied graphs from here, even for product metrics.
> Split metrics into separate context

- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/devices/show.ex
Split out of the same message that normal inflight deployments will send.
Breaking some things out of #1476
> Rename the manual push message for devices

- lib/nerves_hub/deployments.ex
- lib/nerves_hub/deployments/calculator.ex
- test/nerves_hub/deployments/calculator_test.exs
- Skip any device that hasn't connected previously, which also means they don't have firmware metadata to look at
- If a device has a deployment that doesn't match the inflight check's deployment, return a different value than `:skipped` to avoid waiting 15s before processing the next device
> Deployment calculator fixes around which devices are looked at

- lib/nerves_hub/metrics.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
Its possible for websocket connections to be established to multiple devices using the same identifier. This either happens when a websocket connection dies (eg. network error) but the server takes a while to know about it and shut down the connection, while in the meantime the device has already reconnected. Its also possible to mess up your device settings and set the same identifier for multiple physical devices.
This PR send a PubSub event that a device has connected, and responds to the event by shutting down. I've used `broadcast_from` so `self()` doesn't get the `connected` message.
> Tell duplicate device connections to shutdown

- lib/nerves_hub_web/channels/device_channel.ex
- Move the `Registry.register` from `:boot` to `:after_join`. The use of `Registry.update_values` in `:boot` were always failing because the device wasn't registered yet.
- Match successful return values for `Registry.update_value`. This is good practice.
- Run a `Registry.unregister` before a `.registry`. This fixes an issue where device connections, which are yet to be cleaned up, causes the reconnecting device not to be added to the `Registry` due to the unique keys requirement.
> Device registry fixes

- lib/nerves_hub/application.ex
- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub_web/channels/device_channel.ex
There is naming conflict with the Devices context, which is confusing at times.
> Improve the Device Registry name

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
This short circuits Ecto change tracking by assigning dummy values before updating the data.
This is one part of the full fix related to a race condition in which two device connections could exist and both update the connection's status.
It could be argued that this isn't needed now that we are enforcing single connections per device, but I still think this is a good thing to have.
> Always save/update the Devices connection status fields

- assets/js/app.js
Tested on Chrome, Firefox, and Safari, and it seems to work.
> The clipboard API is a mess, but this works

- assets/css/_layout.scss
- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/live/deployments/edit.ex
- lib/nerves_hub_web/live/deployments/edit.html.heex
- lib/nerves_hub_web/live/deployments/index.ex
- lib/nerves_hub_web/live/deployments/index.html.heex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/live/deployments/show.html.heex
This allows seeing how big a deployment is in device count in listings
and detail view.
Beyond that the Edit form for Deployments will estimate the matching
devices based on the conditions set.
> Add device count and estimated device count for Deployment views

- lib/nerves_hub/metrics.ex
This trips monitors during deploys because we have a sudden surge of warning logs. Since we're exporting repo query time via telemetry_metrics this isn't required any more.
> Remove the EctoReporter

- lib/nerves_hub_web/channels/device_socket.ex
Fixes an issue where the `DeviceSocket` is used by `Endpoint` but referencing `DeviceEndpoint` isn't available.
Also use `broadcast_from` as we don't need to send this message to the current pid.
> Use the Endpoint from the `socket`

- lib/mix/tasks/fake.metrics.ex
- lib/nerves_hub/devices/device_metric.ex
Inserts randomized metrics for a device every 20 minutes between now and a week ago.
Usage: `mix fake.metrics DEVICE_ID`
> Add task for generating randomized device metrics

- .gitignore
- .iex.exs
- lib/nerves_hub_web/components/device_header.ex
- lib/nerves_hub_web/components/device_health/health_header.ex
Fixes javascript error yielded when device connection timestamp was missing.
> Only render connection tooltip when timestamp is present

- config/runtime.exs
- lib/nerves_hub_web/channels/device_socket.ex
- lib/nerves_hub_web/device_endpoint.ex
This PR is for discussion.
When NervesHub hosts are shutdown (usually for updating) the device connection telemetry and database updates may need some extra time to complete.
This previously wasn't an issue as we weren't hooking into clean shutdowns, and in the case of Fly.io, a hard kill was being used by default.
I think having these dials available is useful, and I think it's worth discussing this approach.
> Allow the socket drainer to be configured at runtime

- assets/css/app.scss
- lib/nerves_hub/devices/metrics.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
Also stop saving firmware metadata on device health.
> Reintroduce missing custom metrics and metadata to device page.

- lib/nerves_hub_web/channels/user_console_channel.ex
This fixes an error seen in Sentry where the socket isn't `joined`, possibly due to a socket termination.
https://github.com/phoenixframework/phoenix/blob/main/lib/phoenix/channel.ex#L698-L719
```
RuntimeError
push/3, reply/2, and broadcast/3 can only be called after the socket has finished joining.
To push a message on join, send to self and handle in handle_info/2. For example:
def join(topic, auth_msg, socket) do
...
send(self, :after_join)
{:ok, socket}
end
def handle_info(:after_join, socket) do
push(socket, "feed", %{list: feed_items(socket)})
{:noreply, socket}
end
```
> Only broadcast in `terminate/2` if the channel is joined

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/devices/index.html.heex
Orders platform dropdown on device filtering (solves https://github.com/nerves-hub/nerves_hub_web/issues/1597).
Also replaces blank option with Unknown together with support for selecting unknown platform as filter.
From:
To:
> Order platform dropdown and add unknown platform as selection

- lib/nerves_hub/tracker.ex
- lib/nerves_hub_web/channels/console_channel.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
An attempt to solve https://github.com/nerves-hub/nerves_hub_web/issues/1519.
Explanation for disabled button is not added, we'd might wait with that until new UI is ready?
> Disable console button when device console is not available

- lib/nerves_hub/devices/metrics.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub/device_metrics_test.exs
- test/nerves_hub_web/live/devices/health_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
This decreases the metrics event processing time by half and reduces the number of Ecto queries, including no longer needing a transaction.
(the 3 and 12 relate to the number of telemetry spans)
(the 400,000 and 1,000,000 are the number of milliseconds used for processing)
> Batch insert device metrics

- lib/nerves_hub/accounts.ex
- lib/nerves_hub_web/channels/device_channel.ex
- The Org related to the Device doesn't need to be preloaded
- Don't load the user (`created_by`) when sending the keys to devices
> Optimize the queries needed for `Accounts.list_org_keys`

- lib/nerves_hub/deployments/orchestrator.ex
This randomly spaces out the timers, which also reduces DB spikes. (minor spikes)
> Increase the Orchestrator timer, and add a jitter

- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/devices.ex
- test/nerves_hub/devices_test.exs
Fixes #1617.
If we know a device is unhealthy, we want to clear inflight updates. This unblocks the orchestrator and allows it to continue updating as many devices as possible.
> Clear inflight updates for unhealthy devices

- .github/workflows/ci.yml
This is sometimes useful for testing PRs in external systems as needed
You can either manually trigger a publish in the `Actions` table and run the workflow for your branch or include `[publish]` in any commit message to have it sent through
> Allow publishing docker images from PR

- lib/nerves_hub_web/live/firmware.ex
- lib/nerves_hub_web/live/firmware_templates/upload_firmware_template.html.heex
Fixes #1473.
This adds an error clause to provide helpful feedback when uploading firmware that has already been uploaded. [There's already a test for this constraint](https://github.com/nerves-hub/nerves_hub_web/blob/b7efd90ff828c0a6ee52b0b40ba3065cd68b6985/test/nerves_hub/firmwares_test.exs#L53), but let me know if a LiveView test is wanted/needed.
> Show helpful message when uploading duplicate firmware

- .github/workflows/ci.yml
This fixes an issue where jobs fail when built from forks which would have an incomplete ref. This changes to use the PR number instead which should get the details we need.
It also allows that step to fail to continue to job since it is such a specific, special case
> Use PR number when looking for publish commit message

- assets/css/app.scss
- lib/nerves_hub/devices/alarms.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
Display any current alarms for device.
Click on alarm to show description if provided.
> Show current alarms on device page

- config/runtime.exs
- config/test.exs
- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/devices/metrics.ex
- lib/nerves_hub/extensions.ex
- lib/nerves_hub/extensions/extensions_setting.ex
- lib/nerves_hub/extensions/geo.ex
- lib/nerves_hub/extensions/health.ex
- lib/nerves_hub/products.ex
- lib/nerves_hub/products/product.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/device_socket.ex
- lib/nerves_hub_web/channels/extensions_channel.ex
- lib/nerves_hub_web/components/utils.ex
- lib/nerves_hub_web/live/devices/settings.ex
- lib/nerves_hub_web/live/devices/settings.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- lib/nerves_hub_web/live/product/settings.ex
- lib/nerves_hub_web/live/product/settings.html.heex
- priv/repo/migrations/20241111221626_add_extensions.exs
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/extensions_channel_test.exs
- test/nerves_hub_web/live/devices/settings_test.exs
- test/nerves_hub_web/live/product/settings_test.exs
- test/support/channel_case.ex
- test/support/fixtures.ex
- test/support/socket_client.ex
Start of device extensions which allow for specialized functionality on device to report data and interactions safely outside the update mechanism.
Requires https://github.com/nerves-hub/nerves_hub_link/pull/228
Based on conversations the last while, these are some of the core design decisions so far:
* NervesHub selectively tells a device what extensions to enable
* Extensions are off by default on device
* Extensions should have no affect on socket connectivity or ability to update a device
With that in mind, this is the basic communication cycle for supporting extensions on device.
```mermaid
sequenceDiagram
participant Device as Device (NHL)
participant NH as NervesHub
Device ->> NH: Connect
NH ->> NH: Check `extensions_allowed?`
NH ->> Device: Send "extensions:get"
Device ->> NH: …
```
> Add device extensions support

- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/index.html.heex
- test/nerves_hub_web/live/devices/index_test.exs
Implements filtering on metric values.
What we want is to:
get all devices where the latest associated device metric for specified key is matching the provided filter (greater or less than X)
<s>The current query gives the latest device metric where the requirements are met, so if there are at least one metric report that match for a device, that device will be included in result, no matter the timestamp.</s>
Queries the latest inserted record for given metrics key, and checks if it matches the filter.
Includes a simple little functionality for testing in browser, just add params like `?metric=cpu_temp&metric_operator=gt&metric_value=37.0` to devices URL.
> Add metrics filtering to devices query

- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/views/layout_view.ex
Solves #1678
- Reverts handling of pagination params in devices list that was broken due to a faulty rebase.
- Remove pagination button that displays total pages
- Only display pagination links if total pages is more than 0.
> Fix broken paginator

- Dockerfile
The new UI uses Tailwind and ESbuild via the `assets.deploy` task which needs to be run when building the release.
This adjusts the Dockerfile a bit to include the previous Node assets during the build phase for `mix assets.deploy` to also use
> Include New UI asset building in Dockerfile

- assets/ui-rework/app.css
- assets/ui-rework/app.js
- mix.exs
`esbuild` also generates a css file from the css thats in the js, and that was overwriting the tailwind one. This is because highlight.js has css which is included in the app.js, which esbuild detects.
> Move css imports into `app.css`

- lib/nerves_hub_web/channels/device_channel.ex
Plus clean up the timer when it succeeds
> Fix an incorrect call to retry device registration

- lib/nerves_hub_web/helpers/authorization.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
Solves #1681 
Adds a simple section on device page for listing and running support scripts.
Not too much time spent on the looks since the whole UI is redesigned.
> Add script section to device UI

- lib/nerves_hub/devices/metrics.ex
- lib/nerves_hub_web/live/devices/device_health.ex
- lib/nerves_hub_web/live/devices/show.ex
Solves #1662.
Also, the deprecated broadcast topic for health checks is replaced with correct one.
> Ignore empty metrics map in health report

- lib/nerves_hub/logger.ex
This cleans up our logs a little bit
> Ignore some otel logging metadata

- lib/nerves_hub/devices.ex
- lib/nerves_hub/extensions.ex
- lib/nerves_hub/extensions/geo.ex
- lib/nerves_hub/extensions/health.ex
- lib/nerves_hub/products.ex
- lib/nerves_hub_web/channels/extensions_channel.ex
- lib/nerves_hub_web/live/devices/device_health.ex
See #1703.
Removes all broadcasting to DeviceEndpoint.
> Replace endpoint broadcasts

- lib/nerves_hub_web/live/devices/show.ex
Fixes a UI issue where the connection status and information is removed after a device heartbeat occurs
> Make sure the latest connection is loaded

- lib/nerves_hub_web/endpoint.ex
This approach is taken from https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-connect-info
```
Additionally, session_config may be a MFA, such as {MyAppWeb.Auth, :get_session_config, []}, 
to allow loading config in runtime.
```
This allows for the signing salt to not be published and shared between all running NervesHub installs.
> Fetch the signing salt for the web socket connections from the config

- lib/nerves_hub/deployments.ex
- lib/nerves_hub/logger.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub/deployments_test.exs
This fixes a bug which was introduced by accident.
> Bring back deployment device matching when a device connects

- assets/css/_buttons.scss
- assets/static/images/icons/reconnect.svg
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
Add an SVG for the 'reconnect' button, and disable `reboot`, `reconnect`, and `identify` if the device isn't connected.
> Improve device buttons

- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/live/deployments/edit.ex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/live/deployments/show.html.heex
- test/nerves_hub_web/live/deployments/show_test.exs
This moves some info from the body into the info bar under the deployment name.
I've also fixed the device count, which wasn't excluding deleted devices.
> Move some Deployment info around

- lib/nerves_hub/audit_logs/audit_log.ex
Resolves a warning coming from a function spec in the `AuditLogs.Templates` module using `AuditLog.t()`
> Add a type to the `AuditLog` schema

- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
Eligible deployments now only match against product, platform, and architecture. When there are no eligible deployments, helper text is displayed.
> Relax restrictions when querying for eligible deployments

- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/controllers/api/deployment_controller.ex
- lib/nerves_hub_web/live/deployments/edit.ex
- lib/nerves_hub_web/live/deployments/index.ex
- lib/nerves_hub_web/live/deployments/show.ex
- test/nerves_hub_web/channels/websocket_test.exs
- Add specs to all functions
- Fix a function return
- Simplify some function arguments
> `Deployments` context specs (and some improvements)

- lib/nerves_hub/deployments/orchestrator.ex
- lib/nerves_hub/devices.ex
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
- test/support/fixtures.ex
> Make orchestrator and resolve_update respect deployment.is_active

- lib/nerves_hub_web/live/dashboard/index.ex
I'm not sure how I missed this, but I did.
This PR is a quick fix for a recently changed (by me) function argument.
> Fix a function signature call which recently changed

- config/runtime.exs
- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/firmwares/upload/s3.ex
- lib/nerves_hub_web/dymanic_config_multipart.ex
- lib/nerves_hub_web/endpoint.ex
- lib/nerves_hub_web/live/firmware.ex
This allows for the firmware file size upload limit to be adjusted via runtime env var.
This also restrictions large file uploads to only the firmwares api route.
I'd also like this to be configurable per org, such that free users can only upload smaller firmware sizes, but thats for a different discussion.
> Allow for the firmware file size limit to be configurable

- lib/nerves_hub/devices/connections.ex
- lib/nerves_hub/workers/clean_device_connection_states.ex
I noticed in the DB that we have several old/stale device connections. 
Upon looking into this more, I realised that when we added the `DeviceConnection` schema and relationships, we didn't add a way to clean the stale connections, which might linger due to unforeseen circumstances, like the app crashing.
> Clean stale `DeviceConnection`s

- assets/css/_custom.scss
- assets/css/app.scss
- lib/nerves_hub_web/components/device_header.ex
- lib/nerves_hub_web/live/devices/show.html.heex
'Last seen' wasn't clear in its meaning (based on a user conversation), so I instead moved this within a tooltip and refer to it as a heartbeat.
https://github.com/user-attachments/assets/87e14ee4-2677-44a1-9d86-c9efce77d2d0
> A small device header simplification

- lib/nerves_hub/deployments.ex
- test/nerves_hub_web/live/devices/show_test.exs
Fixes a bug (#1748 ) where the liveview crashes when trying to show a device without firmware metadata.
> Allow devices to have empty firmware when checking for deployments

- lib/nerves_hub/devices/alarms.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub_web/live/devices/show_test.exs
Makes UI for device show "No active alarms" when that's the case.
Also adds test case for this.
In #1734 there's a suggestion of displaying a link to docs or code explaining how to setup alarms on devices, but I couldn't find any examples good enough.
> Make it clear device has no active alarms

- assets/ui-rework/app.js
- assets/ui-rework/console.js
- config/runtime.exs
- lib/mix/tasks/gen.metrics.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/components/device_page/activity.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/components/device_page/settings.ex
- lib/nerves_hub_web/components/pager.ex
- lib/nerves_hub_web/helpers/authorization.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- Fully working 'delete', 'restore', and 'permanently delete' device UI/UX
- Fix some device location marker conditional logic
- Some small list pager UI issues squashed
- Allow for the health polling interval in the UI to be configured at runtime
- Added support for 'set deployment' to the details tab
- Fixed some UI updating issues with removing and setting deployments
- Fixed a bug with checking if a health report is empty
> New UI : Device page improvements - part 3

- assets/ui-rework/hooks/console.js
- assets/ui-rework/hooks/updatingTimeAgo.js
- lib/nerves_hub_web/components/device_page/console.ex
- Fix the `updatingTimeAgo` hook (missing import)
- Fix the console hook trying to updating the console header with some metadata
> New UI: JS hook fixes

- assets/ui-rework/hooks/console.js
`debounce` needed to be passed a function to execute later. 
I also bumped up the font size and removed the default rows and cols.
> New UI: Fix the console resizing logic

- assets/tailwind.config.js
- lib/nerves_hub_web/components/device_page/details.ex
Add CPU percentage as the primary CPU indicator with temperature as secondary.
> Change use of CPU metrics in health indicator

- lib/nerves_hub/audit_logs/templates.ex
- lib/nerves_hub/audit_logs/templates/deployment_templates.ex
- lib/nerves_hub/audit_logs/templates/device_templates.ex
- lib/nerves_hub/deployments.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/controllers/api/deployment_controller.ex
- lib/nerves_hub_web/controllers/api/device_controller.ex
- lib/nerves_hub_web/live/deployments/edit.ex
- lib/nerves_hub_web/live/deployments/new.ex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/channels/websocket_test.exs
Moves all audit logging to the template module.
One exception is in the function `Devices.update_device_with_audit/4` where the audit log description is passed via the updating action (like `tag_device`for example). I don't know if it's worth it adding this to templates, since the templates themselves (the description) are defined outside the templates module. Any input on this is welcomed!
> Move all audit logging to templates

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
Allows for unprovisioned devices to list and set deployments belonging to product. (#1760)
- List all product deployments instead of eligible deployments when device status is `:registered`
- When a deployment is set, an info text tells the user it will be removed from device if firmware and aarch don't match on connection
- Add test for this case
- Set device to `:provisioned` when testing eligible deployments
> Allow unprovisioned devices to set deployments

- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
The video capture went slightly goofy. Both progress bars were green at the time of recording :D 
https://github.com/user-attachments/assets/c144f2d9-5ae9-4e21-b450-e426772fdf7f
We already collect these events and just ignore them from what I can tell. I think this would be quite satisfying and generally helpful for seeing which devices are updating. And the gradient background helps indicate which device the line is for. Also looks fancy.
> Add fancy progress bar for devices list

- lib/nerves_hub_web/components/layouts/sidebar.html.heex
The org name and "avatar" block is now also a link to the org page. As one would expect.
> Add sidebar link for org in org/product menu

- lib/nerves_hub/audit_logs/templates/product_templates.ex
- lib/nerves_hub/scripts.ex
- lib/nerves_hub_web/live/support_scripts/edit.ex
- lib/nerves_hub_web/live/support_scripts/new.ex
- test/nerves_hub/scripts_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
- test/nerves_hub_web/live/support_scripts_test.exs
Adds audit logging when a user creates or updates a script.
Adds a templates file for Product audit logging.
Adding the user as a parameter to creation and updates of scripts is also a preparation for #1799 :)
> Add audit logs when creating or updating script

- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
If you can't tell I really like the thin progress bar :D 
This uses the fix of the background from: https://github.com/nerves-hub/nerves_hub_web/pull/1814
But it also uses the thin stripe.
For simplicity I cut the % display in the label. I think the label is helpful but it was making the whole table jiggle and it would be a bunch of faffing about to make it behave nice.
> Variant of the progress bar tweaks

- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
Before:
https://github.com/user-attachments/assets/6206bb99-05c1-4d64-9c85-f758f056f529
I felt the radial background was too muted, and it wasn't clear which device the solid green bar was for (think of a device that is half way down the list)
Now:
https://github.com/user-attachments/assets/034b7d83-8209-4048-bb28-61e5adf3a702
I've added a progress bar label, removed the top line, and tweaked the gradient a little
> New UI: Improve the readability of the device list progress bar

- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/components/device_page/health.ex
Adds custom metrics for display:
> Custom metrics when viewing device

- lib/nerves_hub_web/dynamic_template_renderer.ex
> Remove a noisy log line

- lib/nerves_hub_web/live/devices/index-new.html.heex
The `invisible` CSS class keeps the element in the dom but just doesn't show it.
Its useful for cases where adding or removing it (or even using hidden) changes sizing and positioning of other elements.
> Stop the `updating` label from messing with the table column

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/dashboard/index.ex
- Include a missing alias, and fix the field used
- Fetch all devices for a product who have a 'latest connection' (ensuring they have, or are, connected to nerves hub)
- Remove the location where clauses (this is filtered later on)
- And adjust the `generate_map_marker` pattern match (the result isn't a Device)
> Fix the Dashboard map query and filtering

- lib/nerves_hub/audit_logs/templates/device_templates.ex
- lib/nerves_hub_web/channels/device_channel.ex
Older versions of NervesHubLink would crash if an unknown messages was pushed down over the socket. Since extensions required a new message, this could fail badly on older devices and so a check was put in place to verify the Device API version NHL was reporting to know if it is safe to request extension info or not.
This removes the audit log _and_ logger statement that was happening when this safe check would not pass meaning the device version was too old to request. However, this happens with _every_ socket connection and can produce incredible amount of noise.
If that level of info is needed, I suggest a future change which shows the device version reported and what that means for support on the device (i.e. in the Device settings page perhaps?)
> Remove audit and logger statement from extensions request check

- lib/nerves_hub/devices/connections.ex
- lib/nerves_hub_web/channels/device_socket.ex
- test/nerves_hub/devices/connections_test.exs
This rejigs the `device_heartbeat` function a little, moving the broadcast into the function and out of the socket.
This also removes the `Repo.get!`, instead using `Repo.update_all`
A `join` has been added so we can fetch the device identifier to use for the broadcast.
> Remove the need to get a connection before updating it

- lib/nerves_hub/deployments.ex
- lib/nerves_hub/firmwares.ex
- lib/nerves_hub_web/live/deployments/index-new.html.heex
- lib/nerves_hub_web/live/deployments/newz.ex
- lib/nerves_hub_web/live/deployments/newz.html.heex
- lib/nerves_hub_web/live/deployments/show-new.html.heex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/router.ex
I rejigged the UI a little.
I've had to use a `deployments/newz` for the route, for now, as the liveview and UI were different enough.
> New UI: Add support for creating deployments

- lib/nerves_hub_web/live/deployments/show-new.html.heex
- lib/nerves_hub_web/live/deployments/show.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
Using `patch` means the same process liveview can be used, saving on the need to destroy a liveview and start one back up.
> New UI: Speed up the loading of the device and deployment page tabs

- lib/nerves_hub/devices/device.ex
- test/nerves_hub_web/channels/extensions_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/support/utils.ex
This relates to an issue found via Sentry.
```
UndefinedFunctionError nil.__struct__/0
lib/nerves_hub_web/channels/extensions_channel.ex in anonymous fn/3 in NervesHubWeb.ExtensionsChannel.parse_extensions/2 at line 34
```
This only occurred when the device was created during connection, eg. shared secrets jitp. The `:extensions` `embeds_one` in Device was nil on creation. The fix was just asking Ecto to set a default.
> Fix: New devices connecting shouldn't cause extension errors

- lib/nerves_hub/devices.ex
- lib/nerves_hub/repo.ex
- lib/nerves_hub_web/channels/device_socket.ex
Optimize some queries used during device connection, with a focus on making sure the product assoc is returned with the device.
> Reduce queries made during device socket connection

- config/config.exs
- lib/nerves_hub/devices/connections.ex
- Increases the frequency of `DeleteOldDeviceConnections` and offsets it by a minute to ensure we're not stacking jobs on the hour
- Sets timeout for `delete_all` to 30s so DB has enough time to work
> Adjust device_connections worker frequency, increase timeout when deleting in batches

- lib/nerves_hub/extensions/health.ex
- lib/nerves_hub_web/channels/extensions_channel.ex
- test/nerves_hub_web/channels/extensions_channel_test.exs
We don't know of a devices firmware metadata until it connects for the first time. When it does connect, the `DeviceSocket` will fetch the device and the `firmware_metadata` field will be nil. This device is the one shared with other channels.
In `Extensions.Health` we are using `socket.assigns.device.firmware_metadata` which is going to be nil during its first connection to NervesHub, and will continue to exit sending reports and creating Sentry errors.
This test replicates the scenario of a device connecting for the first time,  then its firmware metadata being updated, and then connecting to the health extension, exposing the error.
Sadly, in tests, channels share assigns, so this was much harder to replicate.
> Fix an extensions bug related to channels not sharing assigns

- lib/nerves_hub/devices.ex
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/live/devices/index_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
The device channel needs to be notified when a device's deployment changes so it can resubscribe to the proper deployment channel and send an update if available.
> Broadcast that a device has been updated when setting and clearing deployment

- lib/nerves_hub/extensions/health.ex
My suggestion is that the health report should be for data directly from the device, and thus, we shouldn't store `socket.device.firmware_metadata` in the report `metadata`
@lawik what are your thoughts?
> Health Report: Only store metadata directly from the device

- lib/mix/tasks/gen.devices.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub/devices/connections.ex
- lib/nerves_hub/devices/device.ex
- lib/nerves_hub/devices/filtering.ex
- lib/nerves_hub/extensions/geo.ex
- lib/nerves_hub_web/channels/device_channel.ex
- lib/nerves_hub_web/channels/device_socket.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
- test/nerves_hub/devices/connections_test.exs
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
This moves `connection_metadata` and `connection_types` to both use `DeviceConnection.metadata`.
Next week we can create a PR to remove unused fields from the `devices` table.
> Save the device location to `DeviceConnection.metadata`

- lib/nerves_hub/devices.ex
- lib/nerves_hub/ssl.ex
Prefer `Repo.exists?/1` if we are just confirming it is in the db. 
Preload from a `join` where possible.
> Device Cert Auth: Don't fetch data if we don't need it

- lib/nerves_hub_web/components/device_page/details.ex
This makes it easier to differentiate between firmware versions when you are using the same version number.
> Add some of the firmware UUID to the select box

- lib/nerves_hub_web/components/device_page/details.ex
Fixes a UI/UX use case where the 'send update' button can be pressed even though no firmware has been selected.
> Make sure firmware is selected when processing `push-update`

- lib/nerves_hub/archives.ex
- lib/nerves_hub/audit_logs/templates/device_templates.ex
- lib/nerves_hub/deployments.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
This is all about reducing the information stored in the assigns for the `DeviceChannel`. 
It's also allowed us to remove a bunch of preloads which were being done often and fairly aggressively.
> Remove the need to store the devices deployment in the `DeviceChannel`

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
More focused events, and use the information from the event instead of reloading data.
> Add support for clear and update deployment broadcasts

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/components/deployment_page/summary.ex
- lib/nerves_hub_web/live/deployments/show-new.html.heex
- lib/nerves_hub_web/live/deployments/show.ex
All devices up to date:
Updating:
> Improvements to the 'updating' header on the deployments summary tab

- lib/nerves_hub_web/channels/device_channel.ex
This is useful for knowing if there are devices we, as a platform, might want to recommend users/customers upgrade.
Eg. security, performance, feature set, compatibility
> Track the link api version in the connection metadata

- lib/nerves_hub_web/channels/device_channel.ex
This removes the catch all / forward all `handle_info` in `DeviceChannel`
> Be intentional with the messages we send to devices

- config/runtime.exs
From the Ecto docs:
> the number of pools to run concurrently, increase this option when the pool itself may be under contention. When running multiple pools, queries are randomly routed to different pools, without taking into account how many connections are available in each. So in some circumstances, you may be routed to a fully busy pool while others have connections available. The overall number of connections used will be pool_size * pool_count. Defaults to 1
> Allow for the main DB pool to have a customized pool count

- lib/nerves_hub_web/channels/device_channel.ex
`"connection:heartbeat"` is sent to the `"device:#{result.identifier}:internal"` topic, but the `DeviceChannel` doesn't subscribe to this topic.
> Remove unused heartbeat `handle_info`

- lib/nerves_hub_web/channels/device_channel.ex
> `DeviceChannel` should ignore messages but not create Sentry errors

- lib/nerves_hub_web/channels/device_socket.ex
- test/nerves_hub/ssl_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/support/socket_client.ex
This PR covers a few test related bits I discovered:
- The SSL tests should use `tmp_dir` for cert related fixtures
- Fixed a websocket SSL cert test by making sure it attempted to connect 
Once I added the `wait_connect` I confirmed the failure was happening. 
- Fix an issue where `on_disconnect` was being called twice
I saw this when debugging the tests, but I've also been seen in production. I believe it's related to channels being told to disconnect, and if a socket has two channels, we see two disconnection messages. Or it could be Phoenix/Bandit sending it twice for some reason? Either way, this tracks when it was first called and storing it in the assigns.
- and the main issue I was working towards.... cleanly close sockets in the websocket tests
This closes sockets, and then …
> Cleanly close sockets in tests

- lib/nerves_hub/audit_logs.ex
- test/nerves_hub_web/channels/device_channel_test.exs
- test/nerves_hub_web/channels/extensions_channel_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/support/channel_case.ex
Postgres was complaining. This makes sure it doesn't happen anymore.
> Cleanly close the device connection during channel tests

- assets/ui-rework/hooks/console.js
- lib/nerves_hub_web/components/device_page/console.ex
This frees up some space on smaller screens.
In the future I would like to use toast or flash notifications for console events, like when the file upload has started or finished, or someone else has joined the console.
> New UI: Remove the chat from the console

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
This was some feedback from a NervesCloud user, and makes a lot of sense to me.
There is some code duplication which will be resolved when we start removing the old UI code.
> Switch to showing (and sorting) on a devices last connection `established_at` datetime

- lib/nerves_hub/deployments.ex
- test/nerves_hub/deployments_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
This behavior was removed in #1652 and was relied on more than expected.
> Reinstate deployment version check when device connects

- lib/nerves_hub/logger.ex
A spoonful of less logging helps the medicine go down
> Ignore logging for web requests from the Sentry uptime bot

- lib/nerves_hub/scripts/runner.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/live/devices/show.ex
Timeouts are to be expected and shouldn't raise an error in Sentry.
This also adds a friendlier message to the UI
I also increased the gap between items.
> Capture support script timeouts

- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/index.html.heex
- priv/repo/migrations/20250220222631_create_devices_firmware_metadata_architecture_index.exs
- test/nerves_hub_web/live/devices/index_test.exs
Previously, we displayed all deployments as options when batch-updating devices. This is confusing because you could see deployments that shouldn't be options. This PR now requires you to filter by platform first before having the ability to bulk move devices into a deployment. 
This change does create an extra step when moving devices to a deployment but it's important to note this is an interim feature before #1653 is finished.
> Ensure available deployments match selected devices architecture and platform when batch-updating

- lib/nerves_hub/deployments.ex
- lib/nerves_hub_web/live/devices/index.ex
Related to bulk moving devices to a deployment, and the addition of the version check when verifying a devices eligibility to a deployment.
> Bug fixes from recent PRs

- lib/nerves_hub_web/controllers/api/script_controller.ex
https://github.com/nerves-hub/nerves_hub_web/pull/1923 introduced a change to handle when scripts timeout waiting for data back. However, it missed adjusting for the change in `NervesHubWeb.API.ScriptController` so using the API is broken.
This fixes to match that new return value and adds a `504` response if it times out waiting for the script reply.
> Fix starting scripts from API endpoint

- lib/nerves_hub/devices/filtering.ex
Fixes and closes a Sentry error
```
Postgrex.Error: ERROR 42809 (wrong_object_type) op ANY/ALL (array) requires array on right side
query: SELECT d0."id", d0."org_id", d0."product_id", d0."deployment_id", d0."latest_connection_id", 
d0."latest_health_id", d0."identifier", d0."description", d0."tags", d0."connecting_code", 
d0."custom_location_coordinates", d0."extensions", d0."first_seen_at", d0."status", d0."firmware_metadata", 
d0."updates_enabled", d0."update_attempts", d0."updates_blocked_until", d0."deleted_at", d0."inserted_at", 
d0."updated_at", d1."id", d1."device_id", d1."established_at", d1."last_seen_at", d1."disconnected_at", 
d1."disconnected_reason", d1."metadata", d1."status", d2."id", d2."device_id", d2."data", d2."status", d2."status_reasons", 
d2."inserted_at" FROM …
```
> Fix a bug with how we were filtering on connection type

- lib/nerves_hub_web/live/devices/show.ex
We were checking the device extension settings, but not the product.
Part 1 of #1939
> Also check if the product has the health extension enabled

- lib/nerves_hub/devices/connections.ex
- priv/repo/migrations/20250312132817_add_device_connection_last_seen_at_indexes.exs
This PR backports two indexes on `device_connections` we've been using in production. I'm also adding an `order_by` when deleting `device_connections` so an index is used.
> Backport device_connection indexes, sort when deleting them so index is used

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
If the Device isn't connected to a Deployment:
And use toggle buttons for the update status:
https://github.com/user-attachments/assets/73ae63fa-0b69-4539-a072-23c16c72d363
Also, I've updated the logic when the penalty box is cleared so that the `updates_enabled` field is set to `true`
> Improve firmware update button on the Device show page

- assets/ui-rework/hooks/console.js
The font is specified as Ubuntu Mono which didn't resolve on my machine. I believe the old UI resolved to Montserrat and the new on Inter. Not fully clear on why not the same monospace one instead.
The fonts have different font-sizes and will wrap differently. So I reduced the font size.
This restores RingLogger.viewer functionality preventing the console from wrapping so aggressively. Vertical real-estate is still a bit limited and I think we can address that separately. Those changes will be less straightforward.
> Reduce font size in console to prevent wrap

- config/config.exs
- lib/nerves_hub/devices/connections.ex
- lib/nerves_hub/devices/device_connection.ex
- lib/nerves_hub_web/channels/device_socket.ex
- priv/repo/migrations/20250322003835_add_product_id_to_device_connections_table.exs
- priv/repo/migrations/20250324172254_index_device_connections_product_id.exs
- test/nerves_hub/devices/connections_test.exs
- test/nerves_hub/devices/distributed/orchestrator_test.exs
- test/nerves_hub_web/live/devices/show_test.exs
- test/support/fixtures.ex
This is required for improved query perf when polling for the count of connected devices grouped by `product_id`.
The way to do such a query, before these changes, required a join, and that itself just added more for the query planner to take care of.
This work is a required part of an Insights dashboard I'm working on.
> Cache the `product_id` in the `DeviceConnection`

- lib/nerves_hub_web/components/device_page/console.ex
I think this is a better immersive console.
Next step in my book is a theatre-mode, faux-fullscreen. But this is a good start on using the space.
From this:
To this:
> Remove padding and box around the console

- lib/nerves_hub/devices.ex
- lib/nerves_hub/managed_deployments/orchestrator.ex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/live/devices/show_test.exs
I introduced some poor logic which impacted 'skip queue' calls.
The message was only sent to devices if they were using the new distributed orchestrator.
This fixes the issue by leaving the message sending to `told_to_update`, and making sure the pid of the device channel is passed through if the old message passing pattern is required.
Oh, also, the message that was being sent wasn't actually doing anything, so this cleans that up.
> Make sure 'skip queue' firmware update message are sent to devices

- lib/nerves_hub/managed_deployments.ex
- lib/nerves_hub/managed_deployments/filtering.ex
- lib/nerves_hub_web/live/deployment_groups/index-new.html.heex
- lib/nerves_hub_web/live/deployment_groups/index.ex
- test/nerves_hub_web/live/deployment_groups/index_test.exs
Adds a search input that enables filtering on deployment group name (New UI only).
Added filtering mechanisms which makes it easy to add more filters in the future, much like on devices view.
> Filter deployment groups by name

- config/runtime.exs
- lib/nerves_hub_web/channels/device_socket.ex
If a horde of devices connects at the same time, this will help distribute the heartbeat updates, and the jitter will be incorporated on every check, further randomizing the spread.
> Incorporate a random jitter into the device heartbeat

- lib/nerves_hub_web/components/ca_helpers.ex
Currently certificate_status displays as expired on valid certificates.
> Fix date comparison when checking certificate status.

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/components/device_page/details.ex
- lib/nerves_hub_web/components/device_page/health.ex
- lib/nerves_hub_web/live/devices/device_health.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- test/support/channel_case.ex
A bug was discovered where support script output was being cleared without the clear button being pressed.
A deep dive found two core issues:
1. the latest health report subscriptions were wrong and weren't being sent through to the details live component
2. anytime the device updated, which would happen with heartbeats or health updates, the details page `update/2` would be called, which would rerender the live component, clearing the support script.
I also found a follow-up issue: the health live component was, well, built incorrectly (by me). Instead of the parent liveview sending data through, it was trying to subscribe to broadcasts, and thus not getting any updates. The reason it would update is because the device was updated, which propagated to the health live component, and …
> Fix how device health is updated in the UI

- lib/nerves_hub_web/live/devices/show.ex
Even though we aren't implementing new features for the old UI it should still be functional.
> Allow the old UI to continue to enable and disable firmware updates when viewing a device

- lib/nerves_hub/managed_deployments/distributed/orchestrator.ex
- lib/nerves_hub/managed_deployments/orchestrator.ex
- lib/nerves_hub/statsd_metrics_reporter.ex
- Change telemetry key names in the orchestrator to match proper terminology
- Remove `nerves_hub.devices.deployment.changed.count`, it's not used anywhere
- Rename device update count metric names so they match the telemetry keys they correspond to
> Fix some metric and telemetry keys

- lib/nerves_hub/application.ex
- lib/nerves_hub_web/channels/presence.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/live/devices/new_ui/show_test.exs
Adds Phoenix Presence, to application in general and device page specifically.
Tracks user on mount, subscribes to events for device's presence and populates user list on presence diff.
Todo:
- Better styling on user circles
> Show users currently watching device page

- lib/nerves_hub_web/channels/presence.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/live/devices/new_ui/show_test.exs
Changes topic for presence stream, from general "online-users" to "device-IDENTIFIER".
Also includes a fix for z-index on stacked user avatars.
> Only include specified device in presence stream

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/show-new.html.heex
- lib/nerves_hub_web/live/devices/show.ex
- lib/nerves_hub_web/live/devices/show.html.heex
This is a follow on from #2010 where the `phx-click` naming wasn't clear, as well as having duplicates.
> Improved function naming for toggling automatic updates

- assets/package-lock.json
We need to manually update these to keep them inline and up-to-date with their Elixir counterparts.
> Update Phoenix JS dependencies

- lib/nerves_hub/application.ex
The app can't start when trying to run the old orchestrator supervisor, which doesn't exist :) 
```
* (Mix) Could not start application nerves_hub: exited in: NervesHub.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (ArgumentError) The module NervesHub.ManagedDeployments.Supervisor was given as a child to a supervisor but it does not exist
(elixir 1.18.3) lib/supervisor.ex:797: Supervisor.init_child/1
(elixir 1.18.3) lib/enum.ex:1714: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.18.3) lib/enum.ex:1714: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.18.3) lib/supervisor.ex:783: Supervisor.init/2
(elixir 1.18.3) lib/supervisor.ex:707: Supervisor.start_link/2
(kernel 10.2.3) application_master.erl:295: :application_master.start_it_old/4
```
> Remove old orchestrator supervisor from application tree

- lib/nerves_hub/application.ex
- lib/nerves_hub_web/components/device_page/settings.ex
The key `:first_connect_code` doesn't exist on the device-changeset-to-form map. The name of the device struct's column, `:connecting_code`, must be used.
> New UI: Display first connecting code properly

- lib/nerves_hub_web/live/deployment_groups/index.ex
@esvinson pointed this out: defaulting to deployment group name descending feels unnatural as a default sort order. `name asc` feels much better.
> Default to sorting deployment groups by name while viewing DeploymentGroups.Index

- assets/ui-rework/app.css
- lib/nerves_hub_web/live/devices/index-new.html.heex
Webkit doesn't support `display: relative` on `<tr />`'s. That means that our absolute-positioned table row mask, which allows the entire table row to be clickable, takes up the entire page 😖 Using a mix of `clip-path` and `transform: translate()` is enough to tell Webkit to keep the bounds in the table row.
> Support device index table row links in webkit

- lib/nerves_hub_web/components/device_page/activity_tab.ex
- lib/nerves_hub_web/components/device_page/details_tab.ex
- lib/nerves_hub_web/components/device_page/health_tab.ex
- lib/nerves_hub_web/live/support_scripts/index-new.html.heex
- test/nerves_hub_web/live/new_ui/devices/activity_tab_test.exs
- test/nerves_hub_web/live/new_ui/devices/index_test.exs
- test/nerves_hub_web/live/new_ui/devices/show_test.exs
- test/nerves_hub_web/live/new_ui/support_scripts_test.exs
- Improve the Device Health tab empty state
- Hide the entire update section on the Details tab if there are no firmware
- Add an empty state for the Device activity tab
- Prefer `:if` over `<%= if ... %>`
- Fix the "Add Support Script" button
- Some minor piping improvements
> Empty state UI tweaks (plus a button fix)

- config/config.exs
This also addresses a warning with `mapbox-gl` and `Bigint`
> Update `esbuild` and the js target it compiles to

- lib/nerves_hub/accounts.ex
- lib/nerves_hub/accounts/user_token.ex
- lib/nerves_hub_web/plugs/api/user.ex
- test/nerves_hub/accounts/accounts_test.exs
- test/nerves_hub_web/plugs/api/user_test.exs
- test/support/utils.ex
The previous adjustment to updating UserTokens (#2024) was broken for V1 tokens. Specifically, the code to mark the `last_used` field when used in an API request would only consider the format of the new tokens and request would fail even though the old token was successfully verified.
This changes to remove extra verification of the token format before marking last_used. Instead, it returns the `UserToken` along with the user in the verification query and then updates that record separately.
It also adds an API integration test to confirm requests with the old tokens will continue to work for now
> Ensure User Token V1 continues to work for now

- priv/repo/migrations/20250414150132_remove_null_constraint_from_user_tokens_old_token.exs
- test/nerves_hub/accounts/accounts_test.exs
`old_token` needs to be able to be `NULL` when creating `user_tokens`.
> Relax null constraint on user_tokens.old_token

- lib/nerves_hub_web/live/devices/index-new.html.heex
- test/nerves_hub_web/live/new_ui/devices/index_test.exs
Solves #2043. I changed the `name` of the platform select in #2027, which broke filtering from the filter drawer.
> Fix filtering by platform in new UI

- lib/nerves_hub_web/helpers/role_validate_helpers.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
- lib/nerves_hub_web/live/devices/index.ex
- lib/nerves_hub_web/live/devices/index.html.heex
- test/nerves_hub_web/live/devices/index_test.exs
- test/nerves_hub_web/live/devices/new_test.exs
- test/nerves_hub_web/live/new_ui/devices/index_test.exs
- test/nerves_hub_web/live/org/products_test.exs
This updates both the old and new UI to support the use of `assign_async` for the device list page.
I've adjusted tests, and added some extra one.
The current UI shows a loading message, but we can change this to use faded ghost data.
> Load the device list async, for a better and faster UX

- .github/workflows/ci.yml
- mix.exs
Using the `_build` directory was causing errors with beam files being redefined.
The common practice is to use `/priv`
An example of one of the errors I was seeing: https://github.com/nerves-hub/nerves_hub_web/actions/runs/14485042748/job/40629027836#step:10:12
> Fix incorrect Dialyzer caching

- lib/nerves_hub_web/live/devices/show-new.html.heex
- Display the user's name while hovering over user initial discs
- Force cursor to default on hover; it was defaulting to the text cursor which felt terrible
> Show name of user when hovering over initials while viewing device

- lib/nerves_hub_web/components/device_page/console_tab.ex
Fixes a `missing async assign :console_active?` error when the assign is cleaned up before it is populated.
> Don't clean up the async assign on the console tab

- lib/nerves_hub/accounts/user_notifier.ex
- lib/nerves_hub/emails/confirmation_template.ex
- lib/nerves_hub/emails/login_with_google_reminder_template.ex
- lib/nerves_hub/emails/org_user_added_template.ex
- lib/nerves_hub/emails/password_reset_confirmation_template.ex
- lib/nerves_hub/emails/password_reset_template.ex
- lib/nerves_hub/emails/password_updated_template.ex
- lib/nerves_hub/emails/tell_org_user_added_template.ex
- lib/nerves_hub/emails/tell_org_user_invited_template.ex
- lib/nerves_hub/emails/tell_org_user_removed_template.ex
- lib/nerves_hub/emails/user_invite_template.ex
- lib/nerves_hub/emails/welcome_template.ex
- test/nerves_hub_web/controllers/oauth_controller_test.exs
My recent updates to the emails missed a crucial `IO.iodata_to_binary()` when processing the content of the pure text emails.
This PR fixes that, removes some email duplication, and fixes a test related to the new oauth login pages.
> Fix pure text emails

- assets/ui-rework/app.css
- lib/nerves_hub_web/components/device_page/details_tab.ex
- lib/nerves_hub_web/components/pinned_devices.ex
- lib/nerves_hub_web/live/devices/index-new.html.heex
Too many tags for a pinned device breaks the layout. The text should not wrap and it should be scrollable.
Before:
After:
> Scroll pinned-device tags when there are too many

- lib/nerves_hub/firmwares.ex
- test/nerves_hub/firmwares_test.exs
The `:distinct` on the `count` would always return 0 or 1 when it should be counting all the device rows.
> Fix firmware install count column when viewing firmwares

- lib/nerves_hub_web/router.ex
- test/nerves_hub_web/controllers/api/script_controller_test.exs
This was removed in #2057 but is needed.
> Reinstate script controller API endpoint

- lib/nerves_hub_web/controllers/api/script_controller.ex
- test/nerves_hub_web/controllers/api/script_controller_test.exs
I mistakenly modified the `conn.assigns` in the ScriptsController test, which doesn't reflect how the real world works. This PR uses `device.product` instead of relying on the product being in `conn.assigns`. I verified this works locally with Postman.
> Fix scripts index API endpoint

- lib/nerves_hub_web/components/device_page/settings_tab.ex
- test/nerves_hub_web/live/new_ui/devices/settings_tab_test.exs
Fixes a bug where device certificates could not be downloaded by changing the target link to use certificates serial number.
Also adds a test for downloading certificates in new UI.
> New UI: Fix broken certificate download

- lib/nerves_hub_web/components/device_page/details_tab.ex
This change will ignore update on dropdowns in device detail view which prevents clearing selections every time ui polling happens.
Issue https://github.com/nerves-hub/nerves_hub_web/issues/2093
> Ignore update on dropdowns in device detail view

- lib/nerves_hub/managed_deployments.ex
- lib/nerves_hub/managed_deployments/deployment_group.ex
- lib/nerves_hub_web/components/deployment_group_page/settings.ex
- lib/nerves_hub_web/controllers/api/deployment_group_controller.ex
- lib/nerves_hub_web/live/deployment_groups/edit.ex
- lib/nerves_hub_web/live/deployment_groups/index-new.html.heex
- lib/nerves_hub_web/live/deployment_groups/new.ex
- lib/nerves_hub_web/live/deployment_groups/newz.ex
- lib/nerves_hub_web/router.ex
- priv/repo/add_org_id.exs
- test/nerves_hub/managed_deployments/deployment_group_test.exs
- test/nerves_hub/managed_deployments_test.exs
- test/nerves_hub_web/controllers/api/deployment_controller_test.exs
- test/nerves_hub_web/live/deployment_groups/edit_test.exs
- test/nerves_hub_web/live/new_ui/deployment_groups/new_test.exs
- test/nerves_hub_web/live/new_ui/deployment_groups/show_test.exs
- test/support/fixtures.ex
This started as an adjustment to deployment group tag validations and ended up being a refactor of deployment group changesets. The core issue is that we handled tag validation differently in the create and update changesets.
When updating a deployment group, tags are required, even though empty tags is a valid state; you can create a deployment group with no tags. This requirement has been removed. In application code, we treat `%{"version" => ""}` as the empty state for `version`. Nothing has stopped us in the changeset or database layer from saving `conditions` to anything but a map with those two keys. Luckily, in SR prod, there are no deployment group rows with one of these keys; it's always both. I added the ability to partially update conditions so you don't have to always provide …
> Don't require tags when updating deployment group, changeset refactor

- lib/nerves_hub_web/live/devices/show-new.html.heex
Issue: https://github.com/nerves-hub/nerves_hub_web/issues/1920
Changes:  
- Align text/device-name on the right side of 'All devices', vertically centered
- Hide device-name on back-button on narrower screens, also hides 'All devices' on really small screens
- Hide title for version and firmware updates on smaller screens
https://github.com/user-attachments/assets/48e38900-8748-4cf1-99f8-dfab3bf94d71
> Improve responsivness for top bar

- lib/nerves_hub/devices.ex
- lib/nerves_hub/managed_deployments.ex
- lib/nerves_hub/managed_deployments/deployment_group.ex
- lib/nerves_hub/products.ex
- lib/nerves_hub/products/product.ex
- lib/nerves_hub_web/components/deployment_group_page/settings.ex
- lib/nerves_hub_web/controllers/api/deployment_group_json.ex
- lib/nerves_hub_web/controllers/api/product_controller.ex
- lib/nerves_hub_web/controllers/api/product_json.ex
- lib/nerves_hub_web/controllers/api/schemas/product_schemas.ex
- lib/nerves_hub_web/helpers/authorization.ex
- lib/nerves_hub_web/live/deployment_groups/show.ex
- lib/nerves_hub_web/live/product/settings-new.html.heex
- lib/nerves_hub_web/live/product/settings.ex
- lib/nerves_hub_web/live/product/settings.html.heex
- lib/nerves_hub_web/live/products/new-new.html.heex
- lib/nerves_hub_web/live/products/new.html.heex
- priv/repo/migrations/20250611082642_move_delta_updatable_to_deployment_group.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub_web/live/new_ui/deployment_groups/show_test.exs
- test/nerves_hub_web/live/product/settings_test.exs
- test/support/fixtures.ex
Adds `delta_updatable` field to `DeploymentGroup` and removes it from `Product`.
All product update functions are also deleted since Product has no more fields that can be updated (name cannot be changed, and extensions are embedded).
> Move delta_updatable setting to deployment group

- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/firmwares/delta_updater.ex
- lib/nerves_hub/firmwares/delta_updater/default.ex
- lib/nerves_hub_web/components/deployment_group_page/summary.ex
- test/nerves_hub/firmwares/delta_updater_test.exs
- test/nerves_hub/firmwares_test.exs
- test/support/fixtures.ex
This should let users see that deltas exist.
Also included the size of the delta file as well as the size of the full target firmware. Until we collect stats on how much transfer we save this is at least an indication.
It only shows up for products with deltas enabled. Older generated deltas may not have the size information so they won't show it.
> Add information about available deltas to deployment summary

- lib/nerves_hub_web/dynamic_config_multipart.ex
- test/nerves_hub_web/dynamic_config_multipart_test.exs
Trying to upload some firmware to NH 2.x, I was seeing this:
```shell
$ nh firmware publish some.fw 
NervesHub Host: example.com
Organization:   ACME
NervesHub product: Big Anvil
------------
Organization: ACME
product:      Big Anvil
version:      0.1.18
platform:     bbb
architecture: arm
uuid:         229764bc-938a-5509-d311-060497eb3a55
Publish Firmware? yN y  
|==================================================| 100% (23 / 23) MB
Unhandled error: {:error, nil}
```
Looking into the server logs:
```elixir
(Phoenix.Template.UndefinedError) Could not render "413.html" for NervesHubWeb.ErrorView...
*snip*
%{
reason: %Plug.Parsers.RequestTooLargeError{
message: "the request is too large...",
plug_status: 413
},
status: 413
...
}
```
Tracked the problem here: …
> Allow firmware uploads from products named with spaces

- lib/nerves_hub_web/components/device_page/details_tab.ex
Depending on what's displayed on the device details page, the priority updates tooltip could overlap the location map. Adding another line break keeps the width at a manageable size.
> Ensure device priority update tooltip doesn't overlap location map

- lib/nerves_hub_web/components/pinned_devices.ex
The square background would slightly clip the rounded edges on the header. Similar issue with the bottom border.
Before:
After:
> Fix visual issue with rounded corners on pinned devices table

- lib/nerves_hub_web/controllers/api/script_controller.ex
- test/nerves_hub_web/controllers/api/device_controller_test.exs
A 503 status more accurately represents what's happening server-side.
> Send 503 status when running script and device is unreachable

- config/runtime.exs
- lib/nerves_hub/application.ex
Otherwise the creation of the schema table fails, causing the application to fail to start.
> Set a default table engine suited for hosted Clickhouse installs

- lib/nerves_hub_web/channels/device_channel.ex
It's noisy, especially when you don't have control of the device.
> Don't send `Unhandled handle_in message` to Sentry

- lib/nerves_hub/managed_deployments.ex
- test/nerves_hub/managed_deployments_test.exs
Found in the NervesCloud Sentry.
An invalid version got into a DeploymentGroups condition, causing looping errors due to us not catching the error. This at least stops the looping error.
> Catch invalid version condition errors

- lib/nerves_hub_web/live/deployment_groups/newz.ex
- lib/nerves_hub_web/live/deployment_groups/newz.html.heex
- test/nerves_hub_web/live/new_ui/deployment_groups/new_test.exs
I spent way too much time trying to figure out why this was happening, but I've found the solution. When creating a deployment group with invalid params, the formatting call to `tags_to_string/1` doesn't work as expected. It will simply return the `deployment_group.conditions` map, thus blowing up `NervesHubWeb.CoreComponents.input/1` downstream. 
If you feel inclined, please feel free to nerd snipe me 🫡
> Fix rendering tags with invalid deployment group params so errors display properly

- priv/repo/migrations/20250804135512_add_actor_index_to_audit_logs.exs
Add concurrent index on `(actor_type, actor_id)` columns to `audit_logs` table 
to dramatically improve performance of audit log queries for devices and users.
The missing index was causing full table scans on **5M+** record tables, 
resulting in 25+ second query times. With the index, query time drops to ~10ms.
The issue on a line 75
https://github.com/nerves-hub/nerves_hub_web/blob/1191d27ad2b5003fee99c9994c1a052d61304653/lib/nerves_hub/audit_logs.ex#L70-L84
- `audit_logs_org_id_inserted_at_index`: [inserted_at, org_id]  
- `audit_logs_pkey` (PRIMARY KEY): [id]
- `audit_logs_resource_type_resource_id_index`: [resource_id, resource_type]
- Uses CREATE INDEX CONCURRENTLY to avoid table locks during deployment
- Uses create_if_not_exists for idempotency 
- Includes proper migration options …
> Add missing Actor index to Audit Logs table

- .gitignore
- lib/nerves_hub_web/components/device_page/activity_tab.ex
- lib/nerves_hub_web/live/devices/show.ex
- test/nerves_hub_web/live/devices/show_test.exs
- test/nerves_hub_web/live/new_ui/devices/activity_tab_test.exs
Fix pagination functionality for Audit Logs on Device pages in both old and new UI implementations.
- Pagination buttons were not working on device pages
- Old UI and new UI had different default page sizes causing incorrect page counts
- URL parameters were not being read properly
✅ **Old UI**: Fixed `handle_params` to read URL pagination parameters  
✅ **New UI**: Fixed `ActivityTab.tab_params` to extract pagination from URL  
✅ **Dynamic defaults**: `page_size=5` for old UI, `page_size=25` for new UI  
✅ **URL handling**: Pagination now stays on correct pages
- Before: Pagination buttons did not work, always showed page 1
- After: Full pagination functionality with correct page counts for each UI
> Fix Audit Logs pagination on Device pages

- lib/nerves_hub_web/channels/device_socket.ex
- test/nerves_hub_web/channels/websocket_test.exs
This was found in the NervesCloud Sentry.
If an invalid device identifier, this this case an Erlang term, is encoded in the shared secret auth,  `Plug.Crypto.non_executable_binary_to_term/2` correctly catches it, but an error is raised which we don't handle nicely.
This PR rescues `ArgumentError`s, logs a message, and rejects the auth request.
> Handle `ArgumentError`s from `Plug.Crypto.non_executable_binary_to_term`

- lib/nerves_hub_web/channels/device_events_stream_channel.ex
- lib/nerves_hub_web/helpers/authorization.ex
- test/nerves_hub_web/channels/device_events_stream_channel_test.exs
The device event channel is read only and simply forwards events, no need for it to map to a manage role.
> Relax user role for device event channel

- lib/nerves_hub/devices.ex
- lib/nerves_hub/logger.ex
- lib/nerves_hub_web/channels/device_socket.ex
Improve the logging for duplicate device identifiers from:
```
2025-08-14T00:45:50Z app[48e4199b764518] iad level=info msg="Device auth failed" reason="{:error, #Ecto.Changeset<action: :insert, changes: %{status: :registered, extensions: #Ecto.Changeset<action: :insert, changes: %{}, errors: [], data: #NervesHub.Extensions.DeviceExtensionsSetting<>, valid?: true, ...>, identifier: \"abc123\", org_id: 123, priority_updates: false, product_id: 123, update_attempts: [], updates_enabled: true}, errors: [identifier: {\"has already been taken\", [constraint: :unique, constraint_name: \"devices_identifier_index\"]}], data: #NervesHub.Devices.Device<>, valid?: false, ...>}" auth=shared_secrets event=nerves_hub.devices.invalid_auth product_key=nhp_abc123
```
to
```
2025-08-14T00:45:50Z …
```
> Improve the logging for duplicate device identifier connection errors

- lib/nerves_hub/firmwares.ex
- lib/nerves_hub/firmwares/update_tool/fwup.ex
- test/nerves_hub/firmwares/update_tool_test.exs
Switch from system shelling out for `zip` and `unzip` and use `:zip` instead.
Also, favour `Plug.Upload.random_file/1` for safe cleanup of downloaded or generated files.
> Use `:zip` and `Plug.Upload.random_file/1` where appropriate

- lib/nerves_hub/devices.ex
- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub/devices_test.exs
The `DeviceChannel` doesn't use the `update_attempts` information, so instead of reloading the device and updating the field via a changeset, I've taken advantage of Postgres's ability to append to the array via and SQL `update` query.
> A small optimization to `Devices.update_attempted/2`

- lib/nerves_hub_web/channels/device_channel.ex
- test/nerves_hub_web/channels/device_channel_test.exs
Link communicates firmware validation status differently, https://github.com/nerves-hub/nerves_hub_link/pull/335
This PR updates the contract to match
> Reflect changes from how Link communicates firmware validation

- lib/nerves_hub_web/components/device_page/details_tab.ex
This should help stop LV thinking the checkbox has changed and firing an event.
> Switch from `phx-change` to `phx-click`

- lib/nerves_hub/accounts/org.ex
- lib/nerves_hub/devices.ex
- lib/nerves_hub/events/device_events.ex
- lib/nerves_hub/managed_deployments.ex
- lib/nerves_hub_web/components/device_page/details_tab.ex
- lib/nerves_hub_web/live/devices/show.ex
- priv/repo/migrations/20250919001236_add_org_settings.exs
- test/nerves_hub/devices_test.exs
- test/nerves_hub/managed_deployments_test.exs
- test/nerves_hub_web/channels/websocket_test.exs
- test/nerves_hub_web/live/new_ui/devices/index_test.exs
- test/nerves_hub_web/live/new_ui/devices/show_test.exs
This is a customer request that I felt had merit.
A NervesCloud customer requires custom firmware download URLs due to some of the complexities associated with whitelisting URLs with their customers.
This PR addresses this feature request by adding a `settings` field (and embedded schema) to the `Org` schema, adding a `firmware_proxy_url` field, and using this URL when creating the update payloads we send to devices.
> Org settings: Firmware proxy URL

- config/runtime.exs
- lib/nerves_hub/application.ex
- lib/nerves_hub/logger.ex
In some setups, you may not want the full verbosity of events in the logs. This adds a mechanism to include a `LOGGER_EXCLUSIONS` env var with a list of event keys that will be filtered out before telemetry attachment so that they will not be logged as well
> Support log event exclusions

- lib/nerves_hub_web/channels/device_socket.ex
Just a small change from `DateTime.utc_now` as we don't need 100% accurate dates and times.
> Use `System.monotonic_time/1` for quick interval calculations
